# Generated by Django 6.0 on 2026-01-09 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sku', models.CharField(help_text='Stock Keeping Unit (unique per tenant)', max_length=100)),
                ('name', models.CharField(help_text='Item name', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Detailed description')),
                ('is_inventory', models.BooleanField(default=True, help_text='Is this a stocked/inventoried item?')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive items are hidden from selections')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='UnitOfMeasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text="Short code (e.g., 'ea', 'cs', 'plt')", max_length=10)),
                ('name', models.CharField(help_text="Full name (e.g., 'Each', 'Case', 'Pallet')", max_length=50)),
                ('description', models.CharField(blank=True, help_text='Optional description', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive UOMs are hidden from selections')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Unit of Measure',
                'verbose_name_plural': 'Units of Measure',
            },
        ),
        migrations.CreateModel(
            name='ItemUOM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('multiplier_to_base', models.PositiveIntegerField(help_text='How many base units in this UOM (e.g., 12 for CASE)')),
                ('item', models.ForeignKey(help_text='The item this conversion applies to', on_delete=django.db.models.deletion.CASCADE, related_name='uom_conversions', to='items.item')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
                ('uom', models.ForeignKey(help_text='The alternate UOM', on_delete=django.db.models.deletion.PROTECT, related_name='item_conversions', to='items.unitofmeasure')),
            ],
            options={
                'verbose_name': 'Item UOM Conversion',
                'verbose_name_plural': 'Item UOM Conversions',
            },
        ),
        migrations.AddField(
            model_name='item',
            name='base_uom',
            field=models.ForeignKey(help_text='Base unit of measure (typically EACH)', on_delete=django.db.models.deletion.PROTECT, related_name='items', to='items.unitofmeasure'),
        ),
        migrations.AddIndex(
            model_name='unitofmeasure',
            index=models.Index(fields=['tenant', 'code'], name='items_unito_tenant__3ce5b9_idx'),
        ),
        migrations.AddIndex(
            model_name='unitofmeasure',
            index=models.Index(fields=['tenant', 'is_active'], name='items_unito_tenant__c60425_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='unitofmeasure',
            unique_together={('tenant', 'code')},
        ),
        migrations.AddIndex(
            model_name='itemuom',
            index=models.Index(fields=['tenant', 'item', 'uom'], name='items_itemu_tenant__eebaa3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='itemuom',
            unique_together={('tenant', 'item', 'uom')},
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['tenant', 'sku'], name='items_item_tenant__c39cf9_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['tenant', 'name'], name='items_item_tenant__37da01_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['tenant', 'is_active'], name='items_item_tenant__00b3fd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='item',
            unique_together={('tenant', 'sku')},
        ),
    ]
