# Generated by Django 6.0 on 2026-01-28 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
        ('parties', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorrugatedFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text="Short code (e.g., 'handhole', 'perf')", max_length=20)),
                ('name', models.CharField(help_text='Display name', max_length=100)),
                ('requires_details', models.BooleanField(default=False, help_text='If True, ItemFeature.details should be filled')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive features are hidden from selections')),
            ],
            options={
                'verbose_name': 'Corrugated Feature',
                'verbose_name_plural': 'Corrugated Features',
            },
        ),
        migrations.CreateModel(
            name='CorrugatedItem',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='items.item')),
                ('test', models.CharField(blank=True, choices=[('ect29', 'ECT 29'), ('ect32', 'ECT 32'), ('ect40', 'ECT 40'), ('ect44', 'ECT 44'), ('ect48', 'ECT 48'), ('ect51', 'ECT 51'), ('ect55', 'ECT 55'), ('ect112', 'ECT 112'), ('200t', '200T')], help_text='ECT rating', max_length=10)),
                ('flute', models.CharField(blank=True, choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('e', 'E'), ('f', 'F'), ('bc', 'BC DW'), ('eb', 'EB DW'), ('tw', 'TW')], help_text='Flute type', max_length=5)),
                ('paper', models.CharField(blank=True, choices=[('k', 'Kraft'), ('mw', 'Mottled White')], help_text='Paper type', max_length=5)),
                ('is_printed', models.BooleanField(default=False, help_text='Is this item printed?')),
                ('panels_printed', models.PositiveSmallIntegerField(blank=True, help_text='Number of panels printed', null=True)),
                ('colors_printed', models.PositiveSmallIntegerField(blank=True, help_text='Number of colors', null=True)),
                ('ink_list', models.TextField(blank=True, help_text='List of ink colors used')),
            ],
            options={
                'verbose_name': 'Corrugated Item',
                'verbose_name_plural': 'Corrugated Items',
            },
            bases=('items.item',),
        ),
        migrations.CreateModel(
            name='ItemFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField(blank=True, help_text="Additional details (e.g., 'extra score 1+1/2 inches from top')")),
            ],
            options={
                'verbose_name': 'Item Feature',
                'verbose_name_plural': 'Item Features',
            },
        ),
        migrations.CreateModel(
            name='ItemVendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mpn', models.CharField(blank=True, help_text='Manufacturer/Vendor part number', max_length=100)),
                ('lead_time_days', models.PositiveIntegerField(blank=True, help_text='Lead time in days', null=True)),
                ('min_order_qty', models.PositiveIntegerField(blank=True, help_text='Minimum order quantity', null=True)),
                ('is_preferred', models.BooleanField(default=False, help_text='Preferred vendor for this item')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive vendor links are hidden from selections')),
            ],
            options={
                'verbose_name': 'Item Vendor',
                'verbose_name_plural': 'Item Vendors',
            },
        ),
        migrations.AddField(
            model_name='item',
            name='attachment',
            field=models.FileField(blank=True, help_text='File attachment (spec sheet, drawing, etc.)', null=True, upload_to='items/attachments/'),
        ),
        migrations.AddField(
            model_name='item',
            name='customer',
            field=models.ForeignKey(blank=True, help_text='Optional customer for customer-specific items', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='parties.party'),
        ),
        migrations.AddField(
            model_name='item',
            name='division',
            field=models.CharField(choices=[('corrugated', 'Corrugated'), ('packaging', 'Packaging'), ('tooling', 'Tooling'), ('janitorial', 'Janitorial'), ('misc', 'Miscellaneous')], default='misc', help_text='Business division', max_length=20),
        ),
        migrations.AddField(
            model_name='item',
            name='layers_per_pallet',
            field=models.PositiveIntegerField(blank=True, help_text='Layers per pallet', null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='pallet_footprint',
            field=models.CharField(blank=True, help_text="Pallet size (e.g., '48x40')", max_length=20),
        ),
        migrations.AddField(
            model_name='item',
            name='pallet_height',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Total pallet height (inches)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='purch_desc',
            field=models.TextField(blank=True, help_text='Purchase description (shown on POs)'),
        ),
        migrations.AddField(
            model_name='item',
            name='revision',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Version/revision number', null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='sell_desc',
            field=models.TextField(blank=True, help_text='Sales description (shown on invoices)'),
        ),
        migrations.AddField(
            model_name='item',
            name='unit_height',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Height of one unit (inches)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='units_per_layer',
            field=models.PositiveIntegerField(blank=True, help_text='Units per pallet layer', null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='units_per_pallet',
            field=models.PositiveIntegerField(blank=True, help_text='Total units per pallet', null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True, help_text='General description'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['tenant', 'division'], name='items_item_tenant__5d0548_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['tenant', 'customer'], name='items_item_tenant__83e0e8_idx'),
        ),
        migrations.AddField(
            model_name='corrugatedfeature',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant'),
        ),
        migrations.CreateModel(
            name='DCItem',
            fields=[
                ('corrugateditem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='items.corrugateditem')),
                ('length', models.DecimalField(decimal_places=4, help_text='Length dimension (inches)', max_digits=10)),
                ('width', models.DecimalField(decimal_places=4, help_text='Width dimension (inches)', max_digits=10)),
                ('blank_length', models.DecimalField(blank=True, decimal_places=4, help_text='Blank length (inches)', max_digits=10, null=True)),
                ('blank_width', models.DecimalField(blank=True, decimal_places=4, help_text='Blank width (inches)', max_digits=10, null=True)),
                ('out_per_rotary', models.PositiveSmallIntegerField(blank=True, help_text='Number out per rotary die', null=True)),
            ],
            options={
                'verbose_name': 'Die Cut Item',
                'verbose_name_plural': 'Die Cut Items',
            },
            bases=('items.corrugateditem',),
        ),
        migrations.CreateModel(
            name='FOLItem',
            fields=[
                ('corrugateditem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='items.corrugateditem')),
                ('length', models.DecimalField(decimal_places=4, help_text='Length dimension (inches)', max_digits=10)),
                ('width', models.DecimalField(decimal_places=4, help_text='Width dimension (inches)', max_digits=10)),
                ('height', models.DecimalField(decimal_places=4, help_text='Height dimension (inches)', max_digits=10)),
            ],
            options={
                'verbose_name': 'FOL Item',
                'verbose_name_plural': 'FOL Items',
            },
            bases=('items.corrugateditem',),
        ),
        migrations.CreateModel(
            name='HSCItem',
            fields=[
                ('corrugateditem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='items.corrugateditem')),
                ('length', models.DecimalField(decimal_places=4, help_text='Length dimension (inches)', max_digits=10)),
                ('width', models.DecimalField(decimal_places=4, help_text='Width dimension (inches)', max_digits=10)),
                ('height', models.DecimalField(decimal_places=4, help_text='Height dimension (inches)', max_digits=10)),
            ],
            options={
                'verbose_name': 'HSC Item',
                'verbose_name_plural': 'HSC Items',
            },
            bases=('items.corrugateditem',),
        ),
        migrations.CreateModel(
            name='RSCItem',
            fields=[
                ('corrugateditem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='items.corrugateditem')),
                ('length', models.DecimalField(decimal_places=4, help_text='Length dimension (inches)', max_digits=10)),
                ('width', models.DecimalField(decimal_places=4, help_text='Width dimension (inches)', max_digits=10)),
                ('height', models.DecimalField(decimal_places=4, help_text='Height dimension (inches)', max_digits=10)),
            ],
            options={
                'verbose_name': 'RSC Item',
                'verbose_name_plural': 'RSC Items',
            },
            bases=('items.corrugateditem',),
        ),
        migrations.CreateModel(
            name='TeleItem',
            fields=[
                ('corrugateditem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='items.corrugateditem')),
                ('length', models.DecimalField(decimal_places=4, help_text='Length dimension (inches)', max_digits=10)),
                ('width', models.DecimalField(decimal_places=4, help_text='Width dimension (inches)', max_digits=10)),
                ('height', models.DecimalField(decimal_places=4, help_text='Height dimension (inches)', max_digits=10)),
            ],
            options={
                'verbose_name': 'Telescoping Item',
                'verbose_name_plural': 'Telescoping Items',
            },
            bases=('items.corrugateditem',),
        ),
        migrations.AddField(
            model_name='itemfeature',
            name='corrugated_item',
            field=models.ForeignKey(help_text='The corrugated item', on_delete=django.db.models.deletion.CASCADE, related_name='item_features', to='items.corrugateditem'),
        ),
        migrations.AddField(
            model_name='itemfeature',
            name='feature',
            field=models.ForeignKey(help_text='The feature', on_delete=django.db.models.deletion.PROTECT, related_name='item_features', to='items.corrugatedfeature'),
        ),
        migrations.AddField(
            model_name='itemfeature',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='corrugateditem',
            name='features',
            field=models.ManyToManyField(blank=True, help_text='Special features (handholes, perfs, etc.)', related_name='corrugated_items', through='items.ItemFeature', to='items.corrugatedfeature'),
        ),
        migrations.AddField(
            model_name='itemvendor',
            name='item',
            field=models.ForeignKey(help_text='The item', on_delete=django.db.models.deletion.CASCADE, related_name='vendors', to='items.item'),
        ),
        migrations.AddField(
            model_name='itemvendor',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='itemvendor',
            name='vendor',
            field=models.ForeignKey(help_text='The vendor who supplies this item', on_delete=django.db.models.deletion.PROTECT, related_name='supplied_items', to='parties.party'),
        ),
        migrations.AddIndex(
            model_name='corrugatedfeature',
            index=models.Index(fields=['tenant', 'code'], name='items_corru_tenant__ffb052_idx'),
        ),
        migrations.AddIndex(
            model_name='corrugatedfeature',
            index=models.Index(fields=['tenant', 'is_active'], name='items_corru_tenant__b86a5b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='corrugatedfeature',
            unique_together={('tenant', 'code')},
        ),
        migrations.AddIndex(
            model_name='itemfeature',
            index=models.Index(fields=['tenant', 'corrugated_item'], name='items_itemf_tenant__291b7f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='itemfeature',
            unique_together={('tenant', 'corrugated_item', 'feature')},
        ),
        migrations.AddIndex(
            model_name='itemvendor',
            index=models.Index(fields=['tenant', 'item'], name='items_itemv_tenant__6f8a7e_idx'),
        ),
        migrations.AddIndex(
            model_name='itemvendor',
            index=models.Index(fields=['tenant', 'vendor'], name='items_itemv_tenant__2acfde_idx'),
        ),
        migrations.AddIndex(
            model_name='itemvendor',
            index=models.Index(fields=['tenant', 'is_preferred'], name='items_itemv_tenant__44c33d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='itemvendor',
            unique_together={('tenant', 'item', 'vendor')},
        ),
    ]
