# Generated by Django 6.0 on 2026-01-28 17:03

from django.db import migrations


CORRUGATED_FEATURES = [
    # (code, name, requires_details)
    ('handhole', 'Handholes', False),
    ('gap_top', 'Gap Top', False),
    ('gap_bot', 'Gap Bottom', False),
    ('gap_both', 'Gap Top and Bottom', False),
    ('wra', 'Weather Resistant Adhesive', False),
    ('wax', 'Wax Coating', False),
    ('perf', 'Perforations', True),
    ('extra_score', 'Extra Scores', True),
    ('tape', 'Tape', False),
]


def seed_features(apps, schema_editor):
    """Seed corrugated features for all existing tenants."""
    CorrugatedFeature = apps.get_model('items', 'CorrugatedFeature')
    Tenant = apps.get_model('tenants', 'Tenant')

    # Get all tenants
    tenants = Tenant.objects.all()

    for tenant in tenants:
        for code, name, requires_details in CORRUGATED_FEATURES:
            CorrugatedFeature.objects.get_or_create(
                tenant=tenant,
                code=code,
                defaults={
                    'name': name,
                    'requires_details': requires_details,
                    'is_active': True,
                }
            )


def reverse_seed(apps, schema_editor):
    """Remove seeded features (optional - keeps manually added ones)."""
    CorrugatedFeature = apps.get_model('items', 'CorrugatedFeature')
    codes = [code for code, _, _ in CORRUGATED_FEATURES]
    CorrugatedFeature.objects.filter(code__in=codes).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_corrugatedfeature_corrugateditem_itemfeature_and_more'),
        ('tenants', '0001_initial'),  # Ensure tenants app is migrated
    ]

    operations = [
        migrations.RunPython(seed_features, reverse_seed),
    ]
