# Generated by Django 6.0 on 2026-02-05 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
        ('items', '0003_seed_corrugated_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='asset_account',
            field=models.ForeignKey(blank=True, help_text='Override inventory asset account (uses default if blank)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_asset', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='item',
            name='expense_account',
            field=models.ForeignKey(blank=True, help_text='Override COGS account for purchases (uses default if blank)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_expense', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='item',
            name='income_account',
            field=models.ForeignKey(blank=True, help_text='Override income account for sales (uses default if blank)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_income', to='accounting.account'),
        ),
    ]
