# Generated by Django 6.0 on 2026-02-10 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_add_gl_accounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Parent item for hierarchy', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='items.item'),
        ),
    ]
