# Generated by Django 6.0 on 2026-02-16 15:11

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
        ('items', '0005_add_parent_field'),
        ('parties', '0004_customer_default_tax_zone'),
        ('tenants', '0002_add_vendor_bills'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='min_stock',
            field=models.PositiveIntegerField(blank=True, help_text='Minimum acceptable stock level', null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='reorder_point',
            field=models.PositiveIntegerField(blank=True, help_text='When on_hand falls to this level, trigger reorder alert', null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='safety_stock',
            field=models.PositiveIntegerField(blank=True, help_text='Safety stock buffer above min_stock', null=True),
        ),
        migrations.CreateModel(
            name='HistoricalItem',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('sku', models.CharField(help_text='Stock Keeping Unit (unique per tenant)', max_length=100)),
                ('name', models.CharField(help_text='Item name', max_length=255)),
                ('division', models.CharField(choices=[('corrugated', 'Corrugated'), ('packaging', 'Packaging'), ('tooling', 'Tooling'), ('janitorial', 'Janitorial'), ('misc', 'Miscellaneous')], default='misc', help_text='Business division', max_length=20)),
                ('revision', models.PositiveSmallIntegerField(blank=True, help_text='Version/revision number', null=True)),
                ('description', models.TextField(blank=True, help_text='General description')),
                ('purch_desc', models.TextField(blank=True, help_text='Purchase description (shown on POs)')),
                ('sell_desc', models.TextField(blank=True, help_text='Sales description (shown on invoices)')),
                ('units_per_layer', models.PositiveIntegerField(blank=True, help_text='Units per pallet layer', null=True)),
                ('layers_per_pallet', models.PositiveIntegerField(blank=True, help_text='Layers per pallet', null=True)),
                ('units_per_pallet', models.PositiveIntegerField(blank=True, help_text='Total units per pallet', null=True)),
                ('unit_height', models.DecimalField(blank=True, decimal_places=4, help_text='Height of one unit (inches)', max_digits=10, null=True)),
                ('pallet_height', models.DecimalField(blank=True, decimal_places=4, help_text='Total pallet height (inches)', max_digits=10, null=True)),
                ('pallet_footprint', models.CharField(blank=True, help_text="Pallet size (e.g., '48x40')", max_length=20)),
                ('is_inventory', models.BooleanField(default=True, help_text='Is this a stocked/inventoried item?')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive items are hidden from selections')),
                ('reorder_point', models.PositiveIntegerField(blank=True, help_text='When on_hand falls to this level, trigger reorder alert', null=True)),
                ('min_stock', models.PositiveIntegerField(blank=True, help_text='Minimum acceptable stock level', null=True)),
                ('safety_stock', models.PositiveIntegerField(blank=True, help_text='Safety stock buffer above min_stock', null=True)),
                ('attachment', models.TextField(blank=True, help_text='File attachment (spec sheet, drawing, etc.)', max_length=100, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('asset_account', models.ForeignKey(blank=True, db_constraint=False, help_text='Override inventory asset account (uses default if blank)', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounting.account')),
                ('base_uom', models.ForeignKey(blank=True, db_constraint=False, help_text='Base unit of measure (typically EACH)', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='items.unitofmeasure')),
                ('customer', models.ForeignKey(blank=True, db_constraint=False, help_text='Optional customer for customer-specific items', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='parties.party')),
                ('expense_account', models.ForeignKey(blank=True, db_constraint=False, help_text='Override COGS account for purchases (uses default if blank)', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounting.account')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('income_account', models.ForeignKey(blank=True, db_constraint=False, help_text='Override income account for sales (uses default if blank)', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounting.account')),
                ('parent', models.ForeignKey(blank=True, db_constraint=False, help_text='Parent item for hierarchy', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='items.item')),
                ('tenant', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'historical item',
                'verbose_name_plural': 'historical items',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
