# Generated by Django 6.0 on 2026-03-13 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_item_min_stock_item_reorder_point_item_safety_stock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalitem',
            name='product_card_notes',
            field=models.TextField(blank=True, help_text='Free-form notes displayed on the product card'),
        ),
        migrations.AddField(
            model_name='item',
            name='product_card_notes',
            field=models.TextField(blank=True, help_text='Free-form notes displayed on the product card'),
        ),
    ]
