# Generated by Django 6.0 on 2026-03-26 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0010_add_packaging_item'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='packagingitem',
            name='items_packa_tenant__923f50_idx',
        ),
    ]
