# Generated by Django 6.0 on 2026-03-26 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0010_add_packaging_item'),
    ]

    # The RemoveIndex op this migration used to perform paired with an
    # AddIndex in 0010 that has been removed (it was a Django bug under
    # multi-table inheritance — see note in 0010). On dev DBs both
    # migrations are already recorded as applied; on fresh DBs they are
    # both no-ops. Either way the end state matches the model (no index
    # on packagingitem).
    operations = []
