# Generated by Django 6.0 on 2026-03-26 19:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_accountingsettings_default_sales_tax_account'),
        ('items', '0011_fix_packaging_item_index'),
        ('parties', '0008_update_customer_type_choices'),
        ('tenants', '0004_add_approval_settings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalitem',
            name='lifecycle_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_design', 'Design Requested'), ('in_design', 'In Design'), ('design_complete', 'Design Complete'), ('pending_approval', 'Pending Approval'), ('active', 'Active')], default='active', help_text='Item lifecycle stage: draft → design → approval → active', max_length=20),
        ),
        migrations.AddField(
            model_name='historicalitem',
            name='revision_changed_by',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Who created the current revision', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalitem',
            name='revision_date',
            field=models.DateTimeField(blank=True, help_text='When the current revision was created', null=True),
        ),
        migrations.AddField(
            model_name='historicalitem',
            name='revision_reason',
            field=models.TextField(blank=True, help_text='What changed in the current revision'),
        ),
        migrations.AddField(
            model_name='historicalpackagingitem',
            name='lifecycle_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_design', 'Design Requested'), ('in_design', 'In Design'), ('design_complete', 'Design Complete'), ('pending_approval', 'Pending Approval'), ('active', 'Active')], default='active', help_text='Item lifecycle stage: draft → design → approval → active', max_length=20),
        ),
        migrations.AddField(
            model_name='historicalpackagingitem',
            name='revision_changed_by',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Who created the current revision', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalpackagingitem',
            name='revision_date',
            field=models.DateTimeField(blank=True, help_text='When the current revision was created', null=True),
        ),
        migrations.AddField(
            model_name='historicalpackagingitem',
            name='revision_reason',
            field=models.TextField(blank=True, help_text='What changed in the current revision'),
        ),
        migrations.AddField(
            model_name='item',
            name='lifecycle_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_design', 'Design Requested'), ('in_design', 'In Design'), ('design_complete', 'Design Complete'), ('pending_approval', 'Pending Approval'), ('active', 'Active')], default='active', help_text='Item lifecycle stage: draft → design → approval → active', max_length=20),
        ),
        migrations.AddField(
            model_name='item',
            name='revision_changed_by',
            field=models.ForeignKey(blank=True, help_text='Who created the current revision', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_revisions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='item',
            name='revision_date',
            field=models.DateTimeField(blank=True, help_text='When the current revision was created', null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='revision_reason',
            field=models.TextField(blank=True, help_text='What changed in the current revision'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['tenant', 'lifecycle_status'], name='items_item_tenant__2c5557_idx'),
        ),
    ]
