# Generated by Django 6.0 on 2026-03-26 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0012_add_lifecycle_and_revision_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'permissions': [('can_design_item', 'Can claim and complete design work on items'), ('can_approve_item', 'Can approve items to active status'), ('can_bump_revision', 'Can bump revision on active items')]},
        ),
    ]
