# Generated by Django 6.0 on 2026-04-01 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0013_add_lifecycle_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='dcitem',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Height dimension (inches)', max_digits=10, null=True),
        ),
    ]
