# Generated by Django 6.0 on 2026-05-07 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0015_add_secondary_ident_and_extra_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalitem',
            name='extra_info_lines',
            field=models.JSONField(blank=True, default=list, help_text='Structured per-item complications (handhole, score, perforation, WRA, etc.)'),
        ),
        migrations.AddField(
            model_name='historicalitem',
            name='secondary_ident',
            field=models.CharField(blank=True, help_text='Optional secondary identifier (customer part #, alt name, etc.)', max_length=255),
        ),
        migrations.AddField(
            model_name='historicalpackagingitem',
            name='extra_info_lines',
            field=models.JSONField(blank=True, default=list, help_text='Structured per-item complications (handhole, score, perforation, WRA, etc.)'),
        ),
        migrations.AddField(
            model_name='historicalpackagingitem',
            name='secondary_ident',
            field=models.CharField(blank=True, help_text='Optional secondary identifier (customer part #, alt name, etc.)', max_length=255),
        ),
    ]
