# Generated by Django 6.0 on 2026-01-29 13:43

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0003_seed_corrugated_features'),
        ('orders', '0003_add_scheduler_sequence'),
        ('parties', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract_number', models.CharField(help_text='Internal contract number (auto-generated, unique per tenant)', max_length=50)),
                ('blanket_po', models.CharField(blank=True, help_text="Customer's blanket PO reference number", max_length=100)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('complete', 'Completed'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='draft', help_text='Current contract status', max_length=20)),
                ('issue_date', models.DateField(default=django.utils.timezone.now, help_text='Date contract was issued/created')),
                ('start_date', models.DateField(blank=True, help_text='Contract effective start date', null=True)),
                ('end_date', models.DateField(blank=True, help_text='Contract expiration date (null = no expiration)', null=True)),
                ('notes', models.TextField(blank=True, help_text='Contract terms, notes, special instructions')),
                ('customer', models.ForeignKey(help_text='Customer this contract belongs to', on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='parties.customer')),
                ('ship_to', models.ForeignKey(blank=True, help_text='Default shipping location for releases', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts_ship_to', to='parties.location')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Contract',
                'verbose_name_plural': 'Contracts',
            },
        ),
        migrations.CreateModel(
            name='ContractLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('line_number', models.PositiveIntegerField(help_text='Line sequence (10, 20, 30...)')),
                ('blanket_qty', models.PositiveIntegerField(help_text='Total committed quantity for this item')),
                ('unit_price', models.DecimalField(blank=True, decimal_places=4, help_text='Contracted unit price (optional, can be overridden on release)', max_digits=12, null=True)),
                ('notes', models.TextField(blank=True, help_text='Line-specific notes')),
                ('contract', models.ForeignKey(help_text='Parent contract', on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='contracts.contract')),
                ('item', models.ForeignKey(help_text='Item covered by this contract line', on_delete=django.db.models.deletion.PROTECT, related_name='contract_lines', to='items.item')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
                ('uom', models.ForeignKey(help_text='Unit of measure for quantities', on_delete=django.db.models.deletion.PROTECT, related_name='contract_lines', to='items.unitofmeasure')),
            ],
            options={
                'verbose_name': 'Contract Line',
                'verbose_name_plural': 'Contract Lines',
                'ordering': ['line_number'],
            },
        ),
        migrations.CreateModel(
            name='ContractRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity_ordered', models.PositiveIntegerField(help_text='Quantity drawn from contract (mirrors sales order line qty)')),
                ('release_date', models.DateField(default=django.utils.timezone.now, help_text='Date release was created')),
                ('balance_before', models.PositiveIntegerField(help_text='Contract line balance before this release')),
                ('balance_after', models.PositiveIntegerField(help_text='Contract line balance after this release')),
                ('notes', models.TextField(blank=True, help_text='Release-specific notes')),
                ('contract_line', models.ForeignKey(help_text='Contract line this release draws from', on_delete=django.db.models.deletion.PROTECT, related_name='releases', to='contracts.contractline')),
                ('sales_order_line', models.OneToOneField(help_text='Sales order line fulfilling this release', on_delete=django.db.models.deletion.CASCADE, related_name='contract_release', to='orders.salesorderline')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Contract Release',
                'verbose_name_plural': 'Contract Releases',
                'ordering': ['release_date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalContract',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('contract_number', models.CharField(help_text='Internal contract number (auto-generated, unique per tenant)', max_length=50)),
                ('blanket_po', models.CharField(blank=True, help_text="Customer's blanket PO reference number", max_length=100)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('complete', 'Completed'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='draft', help_text='Current contract status', max_length=20)),
                ('issue_date', models.DateField(default=django.utils.timezone.now, help_text='Date contract was issued/created')),
                ('start_date', models.DateField(blank=True, help_text='Contract effective start date', null=True)),
                ('end_date', models.DateField(blank=True, help_text='Contract expiration date (null = no expiration)', null=True)),
                ('notes', models.TextField(blank=True, help_text='Contract terms, notes, special instructions')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('customer', models.ForeignKey(blank=True, db_constraint=False, help_text='Customer this contract belongs to', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='parties.customer')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('ship_to', models.ForeignKey(blank=True, db_constraint=False, help_text='Default shipping location for releases', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='parties.location')),
                ('tenant', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'historical Contract',
                'verbose_name_plural': 'historical Contracts',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['tenant', 'contract_number'], name='contracts_c_tenant__0fbac8_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['tenant', 'customer', 'status'], name='contracts_c_tenant__19a9ce_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['tenant', 'blanket_po'], name='contracts_c_tenant__26c730_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['tenant', 'status'], name='contracts_c_tenant__8ef07c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='contract',
            unique_together={('tenant', 'contract_number')},
        ),
        migrations.AddIndex(
            model_name='contractline',
            index=models.Index(fields=['tenant', 'contract', 'line_number'], name='contracts_c_tenant__f9b7d3_idx'),
        ),
        migrations.AddIndex(
            model_name='contractline',
            index=models.Index(fields=['tenant', 'item'], name='contracts_c_tenant__d08758_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='contractline',
            unique_together={('tenant', 'contract', 'line_number')},
        ),
        migrations.AddIndex(
            model_name='contractrelease',
            index=models.Index(fields=['tenant', 'contract_line'], name='contracts_c_tenant__99b725_idx'),
        ),
        migrations.AddIndex(
            model_name='contractrelease',
            index=models.Index(fields=['tenant', 'release_date'], name='contracts_c_tenant__da19a7_idx'),
        ),
    ]
