# Generated by Django 6.0 on 2026-03-06 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
        ('orders', '0010_contract_type_and_direct_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='contract_type',
            field=models.CharField(choices=[('blanket', 'Blanket'), ('direct', 'Direct')], default='blanket', help_text='Contract type: blanket (negotiated, multi-release) or direct (auto-created, single-use)', max_length=20),
        ),
        migrations.AddField(
            model_name='contract',
            name='source_estimate',
            field=models.ForeignKey(blank=True, help_text='Estimate this contract was converted from (if any)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='converted_contracts', to='orders.estimate'),
        ),
        migrations.AddField(
            model_name='historicalcontract',
            name='contract_type',
            field=models.CharField(choices=[('blanket', 'Blanket'), ('direct', 'Direct')], default='blanket', help_text='Contract type: blanket (negotiated, multi-release) or direct (auto-created, single-use)', max_length=20),
        ),
        migrations.AddField(
            model_name='historicalcontract',
            name='source_estimate',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Estimate this contract was converted from (if any)', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='orders.estimate'),
        ),
    ]
