# Generated by Django 6.0 on 2026-03-13 17:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0003_onboarding_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity_type', models.CharField(choices=[('customer', 'Customer'), ('vendor', 'Vendor'), ('item', 'Item'), ('contact', 'Contact'), ('contract', 'Contract'), ('sales_order', 'Sales Order'), ('purchase_order', 'Purchase Order'), ('rfq', 'RFQ'), ('estimate', 'Estimate'), ('invoice', 'Invoice'), ('price_list', 'Price List'), ('design_request', 'Design Request'), ('account', 'Account'), ('journal_entry', 'Journal Entry')], max_length=30)),
                ('object_id', models.PositiveBigIntegerField()),
                ('label', models.CharField(help_text='Cached display name for fast rendering', max_length=255)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'user', 'entity_type'], name='favorites_u_tenant__ec1f2d_idx')],
                'unique_together': {('tenant', 'user', 'entity_type', 'object_id')},
            },
        ),
        migrations.CreateModel(
            name='UserRecentView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('customer', 'Customer'), ('vendor', 'Vendor'), ('item', 'Item'), ('contact', 'Contact'), ('contract', 'Contract'), ('sales_order', 'Sales Order'), ('purchase_order', 'Purchase Order'), ('rfq', 'RFQ'), ('estimate', 'Estimate'), ('invoice', 'Invoice'), ('price_list', 'Price List'), ('design_request', 'Design Request'), ('account', 'Account'), ('journal_entry', 'Journal Entry')], max_length=30)),
                ('object_id', models.PositiveBigIntegerField()),
                ('label', models.CharField(help_text='Cached display name for fast rendering', max_length=255)),
                ('view_count', models.PositiveIntegerField(default=1)),
                ('last_viewed_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recent_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_viewed_at'],
                'indexes': [models.Index(fields=['tenant', 'user', 'entity_type', 'last_viewed_at'], name='favorites_u_tenant__b45f85_idx')],
                'unique_together': {('tenant', 'user', 'entity_type', 'object_id')},
            },
        ),
    ]
