# Generated by Django 6.0 on 2025-12-12 19:07

import simple_history.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPurchaseOrder',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('order_type', models.CharField(choices=[('PO', 'Purchase Order'), ('REL', 'Release')], max_length=3)),
                ('number', models.CharField(db_index=True, max_length=50)),
                ('status', models.CharField(choices=[('open', 'Open'), ('ready', 'Ready'), ('complete', 'Complete')], default='open', max_length=20)),
                ('scheduled_date', models.DateField(blank=True, default=None, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical purchase order',
                'verbose_name_plural': 'historical purchase orders',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalReleaseOrder',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('order_type', models.CharField(choices=[('PO', 'Purchase Order'), ('REL', 'Release')], max_length=3)),
                ('number', models.CharField(db_index=True, max_length=50)),
                ('status', models.CharField(choices=[('open', 'Open'), ('ready', 'Ready'), ('complete', 'Complete')], default='open', max_length=20)),
                ('scheduled_date', models.DateField(blank=True, default=None, null=True)),
                ('priority', models.PositiveSmallIntegerField(default=5)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical release order',
                'verbose_name_plural': 'historical release orders',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.CharField(choices=[('PO', 'Purchase Order'), ('REL', 'Release')], max_length=3)),
                ('number', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('ready', 'Ready'), ('complete', 'Complete')], default='open', max_length=20)),
                ('scheduled_date', models.DateField(blank=True, default=None, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReleaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.CharField(choices=[('PO', 'Purchase Order'), ('REL', 'Release')], max_length=3)),
                ('number', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('ready', 'Ready'), ('complete', 'Complete')], default='open', max_length=20)),
                ('scheduled_date', models.DateField(blank=True, default=None, null=True)),
                ('priority', models.PositiveSmallIntegerField(default=5)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
