# Generated by Django 6.0 on 2025-12-12 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalpurchaseorder',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Purchase Order', 'verbose_name_plural': 'historical Purchase Orders'},
        ),
        migrations.AlterModelOptions(
            name='historicalreleaseorder',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Release Order', 'verbose_name_plural': 'historical Release Orders'},
        ),
        migrations.AlterModelOptions(
            name='purchaseorder',
            options={'verbose_name': 'Purchase Order', 'verbose_name_plural': 'Purchase Orders'},
        ),
        migrations.AlterModelOptions(
            name='releaseorder',
            options={'verbose_name': 'Release Order', 'verbose_name_plural': 'Release Orders'},
        ),
        migrations.AddField(
            model_name='historicalpurchaseorder',
            name='num_pallets',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicalreleaseorder',
            name='num_pallets',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='num_pallets',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='releaseorder',
            name='num_pallets',
            field=models.SmallIntegerField(default=0),
        ),
    ]
