# Generated by Django 6.0 on 2025-12-16 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0003_alter_historicalpurchaseorder_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpurchaseorder',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalreleaseorder',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='releaseorder',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalpurchaseorder',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('scheduled', 'Scheduled'), ('picking', 'Pick Ticket'), ('shipped', 'Shipped'), ('complete', 'Completed'), ('crossdock', 'Crossdock')], default='open', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalreleaseorder',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('scheduled', 'Scheduled'), ('picking', 'Pick Ticket'), ('shipped', 'Shipped'), ('complete', 'Completed'), ('crossdock', 'Crossdock')], default='open', max_length=20),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('scheduled', 'Scheduled'), ('picking', 'Pick Ticket'), ('shipped', 'Shipped'), ('complete', 'Completed'), ('crossdock', 'Crossdock')], default='open', max_length=20),
        ),
        migrations.AlterField(
            model_name='releaseorder',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('scheduled', 'Scheduled'), ('picking', 'Pick Ticket'), ('shipped', 'Shipped'), ('complete', 'Completed'), ('crossdock', 'Crossdock')], default='open', max_length=20),
        ),
    ]
