# Generated by Django 6.0 on 2025-12-16 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0004_historicalpurchaseorder_notes_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaseorder',
            options={'verbose_name': 'Purchase Order'},
        ),
        migrations.AlterModelOptions(
            name='releaseorder',
            options={'verbose_name': 'Release Order'},
        ),
        migrations.AlterField(
            model_name='historicalpurchaseorder',
            name='num_pallets',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='historicalpurchaseorder',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('picking', 'Pick Ticket'), ('shipped', 'Shipped'), ('complete', 'Completed'), ('crossdock', 'Crossdock')], default='scheduled', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalreleaseorder',
            name='num_pallets',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='historicalreleaseorder',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('picking', 'Pick Ticket'), ('shipped', 'Shipped'), ('complete', 'Completed'), ('crossdock', 'Crossdock')], default='scheduled', max_length=20),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='num_pallets',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('picking', 'Pick Ticket'), ('shipped', 'Shipped'), ('complete', 'Completed'), ('crossdock', 'Crossdock')], default='scheduled', max_length=20),
        ),
        migrations.AlterField(
            model_name='releaseorder',
            name='num_pallets',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='releaseorder',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('picking', 'Pick Ticket'), ('shipped', 'Shipped'), ('complete', 'Completed'), ('crossdock', 'Crossdock')], default='scheduled', max_length=20),
        ),
    ]
