# Generated by Django 6.0 on 2025-12-16 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0005_alter_purchaseorder_options_and_more'),
        ('warehousing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpurchaseorder',
            name='scheduled_truck',
            field=models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='warehousing.truck'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='scheduled_truck',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehousing.truck'),
        ),
    ]
