# Generated by Django 6.0 on 2026-01-09 18:48

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0001_initial'),
        ('parties', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPurchaseOrder',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('confirmed', 'Confirmed'), ('scheduled', 'Scheduled'), ('picking', 'Pick Ticket'), ('shipped', 'Shipped'), ('complete', 'Completed'), ('crossdock', 'Crossdock'), ('cancelled', 'Cancelled')], default='draft', help_text='Current order status', max_length=20)),
                ('scheduled_date', models.DateField(blank=True, help_text='Date scheduled on calendar', null=True)),
                ('notes', models.TextField(blank=True, help_text='Operational notes')),
                ('priority', models.PositiveSmallIntegerField(default=5, help_text='Priority 1 (high) to 10 (low)')),
                ('po_number', models.CharField(help_text='Purchase order number (unique per tenant)', max_length=50)),
                ('order_date', models.DateField(default=django.utils.timezone.now, help_text='Date PO was created')),
                ('expected_date', models.DateField(blank=True, help_text='Expected delivery date (before scheduling)', null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('scheduled_truck', models.ForeignKey(blank=True, db_constraint=False, help_text='Truck assigned for delivery/receiving', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='parties.truck')),
                ('ship_to', models.ForeignKey(blank=True, db_constraint=False, help_text='Our warehouse receiving the goods', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='parties.location')),
                ('tenant', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tenants.tenant')),
                ('vendor', models.ForeignKey(blank=True, db_constraint=False, help_text='Vendor supplying the goods', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='parties.vendor')),
            ],
            options={
                'verbose_name': 'historical purchase order',
                'verbose_name_plural': 'historical purchase orders',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalSalesOrder',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('confirmed', 'Confirmed'), ('scheduled', 'Scheduled'), ('picking', 'Pick Ticket'), ('shipped', 'Shipped'), ('complete', 'Completed'), ('crossdock', 'Crossdock'), ('cancelled', 'Cancelled')], default='draft', help_text='Current order status', max_length=20)),
                ('scheduled_date', models.DateField(blank=True, help_text='Date scheduled on calendar', null=True)),
                ('notes', models.TextField(blank=True, help_text='Operational notes')),
                ('priority', models.PositiveSmallIntegerField(default=5, help_text='Priority 1 (high) to 10 (low)')),
                ('order_number', models.CharField(help_text='Sales order number (unique per tenant)', max_length=50)),
                ('order_date', models.DateField(default=django.utils.timezone.now, help_text='Date order was created')),
                ('customer_po', models.CharField(blank=True, help_text="Customer's PO reference number", max_length=50)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('bill_to', models.ForeignKey(blank=True, db_constraint=False, help_text="Customer's billing address", null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='parties.location')),
                ('customer', models.ForeignKey(blank=True, db_constraint=False, help_text='Customer receiving the goods', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='parties.customer')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('scheduled_truck', models.ForeignKey(blank=True, db_constraint=False, help_text='Truck assigned for delivery/receiving', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='parties.truck')),
                ('ship_to', models.ForeignKey(blank=True, db_constraint=False, help_text="Customer's delivery location", null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='parties.location')),
                ('tenant', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'historical sales order',
                'verbose_name_plural': 'historical sales orders',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('confirmed', 'Confirmed'), ('scheduled', 'Scheduled'), ('picking', 'Pick Ticket'), ('shipped', 'Shipped'), ('complete', 'Completed'), ('crossdock', 'Crossdock'), ('cancelled', 'Cancelled')], default='draft', help_text='Current order status', max_length=20)),
                ('scheduled_date', models.DateField(blank=True, help_text='Date scheduled on calendar', null=True)),
                ('notes', models.TextField(blank=True, help_text='Operational notes')),
                ('priority', models.PositiveSmallIntegerField(default=5, help_text='Priority 1 (high) to 10 (low)')),
                ('po_number', models.CharField(help_text='Purchase order number (unique per tenant)', max_length=50)),
                ('order_date', models.DateField(default=django.utils.timezone.now, help_text='Date PO was created')),
                ('expected_date', models.DateField(blank=True, help_text='Expected delivery date (before scheduling)', null=True)),
                ('scheduled_truck', models.ForeignKey(blank=True, help_text='Truck assigned for delivery/receiving', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_orders', to='parties.truck')),
                ('ship_to', models.ForeignKey(help_text='Our warehouse receiving the goods', on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders_ship_to', to='parties.location')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
                ('vendor', models.ForeignKey(help_text='Vendor supplying the goods', on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='parties.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('line_number', models.PositiveIntegerField(help_text='Line sequence (10, 20, 30...)')),
                ('quantity_ordered', models.PositiveIntegerField(help_text='Quantity ordered')),
                ('unit_cost', models.DecimalField(decimal_places=4, help_text='Cost per unit', max_digits=10)),
                ('notes', models.TextField(blank=True, help_text='Line-specific notes')),
                ('item', models.ForeignKey(help_text='Item being purchased', on_delete=django.db.models.deletion.PROTECT, related_name='purchase_order_lines', to='items.item')),
                ('purchase_order', models.ForeignKey(help_text='Parent purchase order', on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='orders.purchaseorder')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
                ('uom', models.ForeignKey(help_text='Unit of measure', on_delete=django.db.models.deletion.PROTECT, related_name='purchase_order_lines', to='items.unitofmeasure')),
            ],
            options={
                'ordering': ['line_number'],
            },
        ),
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('confirmed', 'Confirmed'), ('scheduled', 'Scheduled'), ('picking', 'Pick Ticket'), ('shipped', 'Shipped'), ('complete', 'Completed'), ('crossdock', 'Crossdock'), ('cancelled', 'Cancelled')], default='draft', help_text='Current order status', max_length=20)),
                ('scheduled_date', models.DateField(blank=True, help_text='Date scheduled on calendar', null=True)),
                ('notes', models.TextField(blank=True, help_text='Operational notes')),
                ('priority', models.PositiveSmallIntegerField(default=5, help_text='Priority 1 (high) to 10 (low)')),
                ('order_number', models.CharField(help_text='Sales order number (unique per tenant)', max_length=50)),
                ('order_date', models.DateField(default=django.utils.timezone.now, help_text='Date order was created')),
                ('customer_po', models.CharField(blank=True, help_text="Customer's PO reference number", max_length=50)),
                ('bill_to', models.ForeignKey(blank=True, help_text="Customer's billing address", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_orders_bill_to', to='parties.location')),
                ('customer', models.ForeignKey(help_text='Customer receiving the goods', on_delete=django.db.models.deletion.PROTECT, related_name='sales_orders', to='parties.customer')),
                ('scheduled_truck', models.ForeignKey(blank=True, help_text='Truck assigned for delivery/receiving', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_orders', to='parties.truck')),
                ('ship_to', models.ForeignKey(help_text="Customer's delivery location", on_delete=django.db.models.deletion.PROTECT, related_name='sales_orders_ship_to', to='parties.location')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='SalesOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('line_number', models.PositiveIntegerField(help_text='Line sequence (10, 20, 30...)')),
                ('quantity_ordered', models.PositiveIntegerField(help_text='Quantity ordered')),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Price per unit', max_digits=10)),
                ('notes', models.TextField(blank=True, help_text='Line-specific notes')),
                ('item', models.ForeignKey(help_text='Item being sold', on_delete=django.db.models.deletion.PROTECT, related_name='sales_order_lines', to='items.item')),
                ('sales_order', models.ForeignKey(help_text='Parent sales order', on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='orders.salesorder')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
                ('uom', models.ForeignKey(help_text='Unit of measure', on_delete=django.db.models.deletion.PROTECT, related_name='sales_order_lines', to='items.unitofmeasure')),
            ],
            options={
                'ordering': ['line_number'],
            },
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['tenant', 'po_number'], name='orders_purc_tenant__a25a83_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['tenant', 'vendor', 'order_date'], name='orders_purc_tenant__bb85b7_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['tenant', 'scheduled_date', 'scheduled_truck'], name='orders_purc_tenant__336ed9_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['tenant', 'status'], name='orders_purc_tenant__a4f4d0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='purchaseorder',
            unique_together={('tenant', 'po_number')},
        ),
        migrations.AddIndex(
            model_name='purchaseorderline',
            index=models.Index(fields=['tenant', 'purchase_order', 'line_number'], name='orders_purc_tenant__2ee065_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorderline',
            index=models.Index(fields=['tenant', 'item'], name='orders_purc_tenant__6a2f06_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='purchaseorderline',
            unique_together={('tenant', 'purchase_order', 'line_number')},
        ),
        migrations.AddIndex(
            model_name='salesorder',
            index=models.Index(fields=['tenant', 'order_number'], name='orders_sale_tenant__1c65b7_idx'),
        ),
        migrations.AddIndex(
            model_name='salesorder',
            index=models.Index(fields=['tenant', 'customer', 'order_date'], name='orders_sale_tenant__0cf361_idx'),
        ),
        migrations.AddIndex(
            model_name='salesorder',
            index=models.Index(fields=['tenant', 'scheduled_date', 'scheduled_truck'], name='orders_sale_tenant__59077d_idx'),
        ),
        migrations.AddIndex(
            model_name='salesorder',
            index=models.Index(fields=['tenant', 'status'], name='orders_sale_tenant__03f91a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='salesorder',
            unique_together={('tenant', 'order_number')},
        ),
        migrations.AddIndex(
            model_name='salesorderline',
            index=models.Index(fields=['tenant', 'sales_order', 'line_number'], name='orders_sale_tenant__adfe7c_idx'),
        ),
        migrations.AddIndex(
            model_name='salesorderline',
            index=models.Index(fields=['tenant', 'item'], name='orders_sale_tenant__fbf3de_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='salesorderline',
            unique_together={('tenant', 'sales_order', 'line_number')},
        ),
    ]
