# Generated by Django 6.0 on 2026-01-14 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_scheduling', '__first__'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpurchaseorder',
            name='delivery_run',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Delivery run this order is assigned to', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='new_scheduling.deliveryrun'),
        ),
        migrations.AddField(
            model_name='historicalsalesorder',
            name='delivery_run',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Delivery run this order is assigned to', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='new_scheduling.deliveryrun'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='delivery_run',
            field=models.ForeignKey(blank=True, help_text='Delivery run this order is assigned to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_orders', to='new_scheduling.deliveryrun'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='delivery_run',
            field=models.ForeignKey(blank=True, help_text='Delivery run this order is assigned to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_orders', to='new_scheduling.deliveryrun'),
        ),
    ]
