# Generated by Django 6.0 on 2026-01-21 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_historicalpurchaseorder_delivery_run_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpurchaseorder',
            name='scheduler_sequence',
            field=models.PositiveIntegerField(default=0, help_text='Display order within a scheduler cell (0 = auto/end)'),
        ),
        migrations.AddField(
            model_name='historicalsalesorder',
            name='scheduler_sequence',
            field=models.PositiveIntegerField(default=0, help_text='Display order within a scheduler cell (0 = auto/end)'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='scheduler_sequence',
            field=models.PositiveIntegerField(default=0, help_text='Display order within a scheduler cell (0 = auto/end)'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='scheduler_sequence',
            field=models.PositiveIntegerField(default=0, help_text='Display order within a scheduler cell (0 = auto/end)'),
        ),
    ]
