# Generated by Django 6.0 on 2026-02-06 16:39

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0001_initial'),
        ('items', '0004_add_gl_accounts'),
        ('orders', '0003_add_scheduler_sequence'),
        ('parties', '0002_add_gl_accounts'),
        ('tenants', '0002_add_vendor_bills'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Estimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('estimate_number', models.CharField(help_text='Estimate number (unique per tenant)', max_length=50)),
                ('date', models.DateField(default=django.utils.timezone.now, help_text='Estimate date')),
                ('expiration_date', models.DateField(blank=True, help_text='Date this estimate expires', null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('converted', 'Converted'), ('expired', 'Expired')], default='draft', help_text='Estimate status', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, help_text='Sum of line amounts', max_digits=12)),
                ('tax_rate', models.DecimalField(decimal_places=4, default=0, help_text='Tax rate (e.g., 0.08 for 8%)', max_digits=5)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, help_text='Calculated tax amount', max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, help_text='Total estimate amount', max_digits=12)),
                ('customer_po', models.CharField(blank=True, help_text="Customer's PO reference number", max_length=50)),
                ('notes', models.TextField(blank=True, help_text='Internal notes')),
                ('terms_and_conditions', models.TextField(blank=True, help_text='Terms & conditions to appear on the estimate')),
                ('bill_to', models.ForeignKey(blank=True, help_text='Billing address', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estimates_bill_to', to='parties.location')),
                ('customer', models.ForeignKey(help_text='Customer this estimate is for', on_delete=django.db.models.deletion.PROTECT, related_name='estimates', to='parties.customer')),
                ('design_request', models.ForeignKey(blank=True, help_text='Design request this estimate is based on', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estimates', to='design.designrequest')),
                ('ship_to', models.ForeignKey(blank=True, help_text='Delivery location', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estimates_ship_to', to='parties.location')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='historicalsalesorder',
            name='source_estimate',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Estimate this order was converted from', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='orders.estimate'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='source_estimate',
            field=models.ForeignKey(blank=True, help_text='Estimate this order was converted from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='converted_orders', to='orders.estimate'),
        ),
        migrations.CreateModel(
            name='EstimateLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('line_number', models.PositiveIntegerField(help_text='Line sequence (10, 20, 30...)')),
                ('description', models.CharField(blank=True, help_text='Line description (defaults to item name)', max_length=255)),
                ('quantity', models.PositiveIntegerField(help_text='Quantity quoted')),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Price per unit', max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, default=0, help_text='Line amount (calculated: quantity * unit_price)', max_digits=12)),
                ('notes', models.TextField(blank=True, help_text='Line-specific notes')),
                ('estimate', models.ForeignKey(help_text='Parent estimate', on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='orders.estimate')),
                ('item', models.ForeignKey(help_text='Item being quoted', on_delete=django.db.models.deletion.PROTECT, related_name='estimate_lines', to='items.item')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
                ('uom', models.ForeignKey(help_text='Unit of measure', on_delete=django.db.models.deletion.PROTECT, related_name='estimate_lines', to='items.unitofmeasure')),
            ],
            options={
                'ordering': ['line_number'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalEstimate',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('estimate_number', models.CharField(help_text='Estimate number (unique per tenant)', max_length=50)),
                ('date', models.DateField(default=django.utils.timezone.now, help_text='Estimate date')),
                ('expiration_date', models.DateField(blank=True, help_text='Date this estimate expires', null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('converted', 'Converted'), ('expired', 'Expired')], default='draft', help_text='Estimate status', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, help_text='Sum of line amounts', max_digits=12)),
                ('tax_rate', models.DecimalField(decimal_places=4, default=0, help_text='Tax rate (e.g., 0.08 for 8%)', max_digits=5)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, help_text='Calculated tax amount', max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, help_text='Total estimate amount', max_digits=12)),
                ('customer_po', models.CharField(blank=True, help_text="Customer's PO reference number", max_length=50)),
                ('notes', models.TextField(blank=True, help_text='Internal notes')),
                ('terms_and_conditions', models.TextField(blank=True, help_text='Terms & conditions to appear on the estimate')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('bill_to', models.ForeignKey(blank=True, db_constraint=False, help_text='Billing address', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='parties.location')),
                ('customer', models.ForeignKey(blank=True, db_constraint=False, help_text='Customer this estimate is for', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='parties.customer')),
                ('design_request', models.ForeignKey(blank=True, db_constraint=False, help_text='Design request this estimate is based on', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='design.designrequest')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('ship_to', models.ForeignKey(blank=True, db_constraint=False, help_text='Delivery location', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='parties.location')),
                ('tenant', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'historical estimate',
                'verbose_name_plural': 'historical estimates',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddIndex(
            model_name='estimate',
            index=models.Index(fields=['tenant', 'estimate_number'], name='orders_esti_tenant__93f6d4_idx'),
        ),
        migrations.AddIndex(
            model_name='estimate',
            index=models.Index(fields=['tenant', 'customer', 'date'], name='orders_esti_tenant__245d0b_idx'),
        ),
        migrations.AddIndex(
            model_name='estimate',
            index=models.Index(fields=['tenant', 'status'], name='orders_esti_tenant__ae2dbd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='estimate',
            unique_together={('tenant', 'estimate_number')},
        ),
        migrations.AddIndex(
            model_name='estimateline',
            index=models.Index(fields=['tenant', 'estimate', 'line_number'], name='orders_esti_tenant__1e97e3_idx'),
        ),
        migrations.AddIndex(
            model_name='estimateline',
            index=models.Index(fields=['tenant', 'item'], name='orders_esti_tenant__ba42c5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='estimateline',
            unique_together={('tenant', 'estimate', 'line_number')},
        ),
    ]
