# Generated by Django 6.0 on 2026-02-06 16:52

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_add_gl_accounts'),
        ('orders', '0004_estimate_historicalsalesorder_source_estimate_and_more'),
        ('parties', '0002_add_gl_accounts'),
        ('tenants', '0002_add_vendor_bills'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalRFQ',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('rfq_number', models.CharField(help_text='RFQ number (unique per tenant)', max_length=50)),
                ('date', models.DateField(default=django.utils.timezone.now, help_text='RFQ date')),
                ('expected_date', models.DateField(blank=True, help_text='Date we need the goods by', null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('received', 'Received'), ('converted', 'Converted'), ('cancelled', 'Cancelled')], default='draft', help_text='RFQ status', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Instructions to vendor')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('ship_to', models.ForeignKey(blank=True, db_constraint=False, help_text='Delivery location for quoted goods', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='parties.location')),
                ('tenant', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tenants.tenant')),
                ('vendor', models.ForeignKey(blank=True, db_constraint=False, help_text='Vendor being asked for quotation', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='parties.vendor')),
            ],
            options={
                'verbose_name': 'historical rfq',
                'verbose_name_plural': 'historical rfqs',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='RFQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rfq_number', models.CharField(help_text='RFQ number (unique per tenant)', max_length=50)),
                ('date', models.DateField(default=django.utils.timezone.now, help_text='RFQ date')),
                ('expected_date', models.DateField(blank=True, help_text='Date we need the goods by', null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('received', 'Received'), ('converted', 'Converted'), ('cancelled', 'Cancelled')], default='draft', help_text='RFQ status', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Instructions to vendor')),
                ('ship_to', models.ForeignKey(blank=True, help_text='Delivery location for quoted goods', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rfqs_ship_to', to='parties.location')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
                ('vendor', models.ForeignKey(help_text='Vendor being asked for quotation', on_delete=django.db.models.deletion.PROTECT, related_name='rfqs', to='parties.vendor')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='historicalpurchaseorder',
            name='source_rfq',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='RFQ this purchase order was converted from', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='orders.rfq'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='source_rfq',
            field=models.ForeignKey(blank=True, help_text='RFQ this purchase order was converted from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='converted_purchase_orders', to='orders.rfq'),
        ),
        migrations.CreateModel(
            name='RFQLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('line_number', models.PositiveIntegerField(help_text='Line sequence (10, 20, 30...)')),
                ('description', models.CharField(blank=True, help_text='Line description (defaults to item name)', max_length=255)),
                ('quantity', models.PositiveIntegerField(help_text='Quantity requested')),
                ('target_price', models.DecimalField(blank=True, decimal_places=4, help_text='Our target price per unit (optional, internal)', max_digits=10, null=True)),
                ('quoted_price', models.DecimalField(blank=True, decimal_places=4, help_text="Vendor's quoted price per unit (filled when vendor responds)", max_digits=10, null=True)),
                ('notes', models.TextField(blank=True, help_text='Line-specific notes')),
                ('item', models.ForeignKey(help_text='Item being requested', on_delete=django.db.models.deletion.PROTECT, related_name='rfq_lines', to='items.item')),
                ('rfq', models.ForeignKey(help_text='Parent RFQ', on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='orders.rfq')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
                ('uom', models.ForeignKey(help_text='Unit of measure', on_delete=django.db.models.deletion.PROTECT, related_name='rfq_lines', to='items.unitofmeasure')),
            ],
            options={
                'ordering': ['line_number'],
            },
        ),
        migrations.AddIndex(
            model_name='rfq',
            index=models.Index(fields=['tenant', 'rfq_number'], name='orders_rfq_tenant__7db58c_idx'),
        ),
        migrations.AddIndex(
            model_name='rfq',
            index=models.Index(fields=['tenant', 'vendor', 'date'], name='orders_rfq_tenant__63a2f1_idx'),
        ),
        migrations.AddIndex(
            model_name='rfq',
            index=models.Index(fields=['tenant', 'status'], name='orders_rfq_tenant__4dde6d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rfq',
            unique_together={('tenant', 'rfq_number')},
        ),
        migrations.AddIndex(
            model_name='rfqline',
            index=models.Index(fields=['tenant', 'rfq', 'line_number'], name='orders_rfql_tenant__2a7dbe_idx'),
        ),
        migrations.AddIndex(
            model_name='rfqline',
            index=models.Index(fields=['tenant', 'item'], name='orders_rfql_tenant__770200_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rfqline',
            unique_together={('tenant', 'rfq', 'line_number')},
        ),
    ]
