# Generated by Django 6.0 on 2026-02-06 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_historicalrfq_rfq_historicalpurchaseorder_source_rfq_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpurchaseorder',
            name='is_pickup',
            field=models.BooleanField(default=False, help_text='Whether this order is a customer pickup (shown in Pick Up row on scheduler)'),
        ),
        migrations.AddField(
            model_name='historicalsalesorder',
            name='is_pickup',
            field=models.BooleanField(default=False, help_text='Whether this order is a customer pickup (shown in Pick Up row on scheduler)'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='is_pickup',
            field=models.BooleanField(default=False, help_text='Whether this order is a customer pickup (shown in Pick Up row on scheduler)'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='is_pickup',
            field=models.BooleanField(default=False, help_text='Whether this order is a customer pickup (shown in Pick Up row on scheduler)'),
        ),
    ]
