# Generated by Django 6.0 on 2026-02-17 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_add_is_pickup_to_baseorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpurchaseorder',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('confirmed', 'Confirmed'), ('scheduled', 'Scheduled'), ('picking', 'Pick Ticket'), ('shipped', 'Shipped'), ('complete', 'Completed'), ('crossdock', 'Crossdock'), ('cancelled', 'Cancelled')], default='draft', help_text='Current order status', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalsalesorder',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('confirmed', 'Confirmed'), ('scheduled', 'Scheduled'), ('picking', 'Pick Ticket'), ('shipped', 'Shipped'), ('complete', 'Completed'), ('crossdock', 'Crossdock'), ('cancelled', 'Cancelled')], default='draft', help_text='Current order status', max_length=20),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('confirmed', 'Confirmed'), ('scheduled', 'Scheduled'), ('picking', 'Pick Ticket'), ('shipped', 'Shipped'), ('complete', 'Completed'), ('crossdock', 'Crossdock'), ('cancelled', 'Cancelled')], default='draft', help_text='Current order status', max_length=20),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('confirmed', 'Confirmed'), ('scheduled', 'Scheduled'), ('picking', 'Pick Ticket'), ('shipped', 'Shipped'), ('complete', 'Completed'), ('crossdock', 'Crossdock'), ('cancelled', 'Cancelled')], default='draft', help_text='Current order status', max_length=20),
        ),
    ]
