# Generated by Django 6.0 on 2026-02-18 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_historicalpurchaseorder_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderline',
            name='quantity_received',
            field=models.PositiveIntegerField(default=0, help_text='Quantity received so far (updated on each receive)'),
        ),
        migrations.AlterField(
            model_name='historicalpurchaseorder',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('confirmed', 'Confirmed'), ('scheduled', 'Scheduled'), ('picking', 'Pick Ticket'), ('shipped', 'Shipped'), ('partially_received', 'Partially Received'), ('complete', 'Completed'), ('crossdock', 'Crossdock'), ('cancelled', 'Cancelled')], default='draft', help_text='Current order status', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalsalesorder',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('confirmed', 'Confirmed'), ('scheduled', 'Scheduled'), ('picking', 'Pick Ticket'), ('shipped', 'Shipped'), ('partially_received', 'Partially Received'), ('complete', 'Completed'), ('crossdock', 'Crossdock'), ('cancelled', 'Cancelled')], default='draft', help_text='Current order status', max_length=20),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('confirmed', 'Confirmed'), ('scheduled', 'Scheduled'), ('picking', 'Pick Ticket'), ('shipped', 'Shipped'), ('partially_received', 'Partially Received'), ('complete', 'Completed'), ('crossdock', 'Crossdock'), ('cancelled', 'Cancelled')], default='draft', help_text='Current order status', max_length=20),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('confirmed', 'Confirmed'), ('scheduled', 'Scheduled'), ('picking', 'Pick Ticket'), ('shipped', 'Shipped'), ('partially_received', 'Partially Received'), ('complete', 'Completed'), ('crossdock', 'Crossdock'), ('cancelled', 'Cancelled')], default='draft', help_text='Current order status', max_length=20),
        ),
    ]
