# Generated by Django 6.0 on 2026-02-20 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_add_partially_received_and_quantity_received'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsalesorder',
            name='order_class',
            field=models.CharField(choices=[('STANDARD', 'Standard'), ('RUSH', 'Rush'), ('BLANKET', 'Blanket'), ('SAMPLE', 'Sample'), ('INTERNAL', 'Internal')], default='STANDARD', help_text='Order classification (e.g., Standard, Rush, Blanket)', max_length=20),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='order_class',
            field=models.CharField(choices=[('STANDARD', 'Standard'), ('RUSH', 'Rush'), ('BLANKET', 'Blanket'), ('SAMPLE', 'Sample'), ('INTERNAL', 'Internal')], default='STANDARD', help_text='Order classification (e.g., Standard, Rush, Blanket)', max_length=20),
        ),
    ]
