# Generated by Django 6.0 on 2026-03-06 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_add_sales_order_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsalesorder',
            name='order_class',
            field=models.CharField(choices=[('STANDARD', 'Standard'), ('RUSH', 'Rush'), ('BLANKET', 'Blanket'), ('SAMPLE', 'Sample'), ('INTERNAL', 'Internal'), ('DIRECT', 'Direct')], default='STANDARD', help_text='Order classification (e.g., Standard, Rush, Blanket)', max_length=20),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='order_class',
            field=models.CharField(choices=[('STANDARD', 'Standard'), ('RUSH', 'Rush'), ('BLANKET', 'Blanket'), ('SAMPLE', 'Sample'), ('INTERNAL', 'Internal'), ('DIRECT', 'Direct')], default='STANDARD', help_text='Order classification (e.g., Standard, Rush, Blanket)', max_length=20),
        ),
    ]
