# Generated by Django 6.0 on 2026-06-23 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_add_fulfillment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorderline',
            name='quantity_invoiced',
            field=models.PositiveIntegerField(default=0, help_text='Quantity already rolled into invoices'),
        ),
    ]
