# Generated by Django 6.0 on 2026-01-09 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0001_initial'),
        ('parties', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceListHead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('begin_date', models.DateField(help_text='Start date for this price list')),
                ('end_date', models.DateField(blank=True, help_text='End date (null = no expiration)', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive price lists are ignored in pricing calculations')),
                ('notes', models.TextField(blank=True, help_text='Internal notes about this price list')),
                ('customer', models.ForeignKey(help_text='Customer this price list applies to', on_delete=django.db.models.deletion.CASCADE, related_name='price_lists', to='parties.customer')),
                ('item', models.ForeignKey(help_text='Item this price list applies to', on_delete=django.db.models.deletion.CASCADE, related_name='price_lists', to='items.item')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Price List',
                'verbose_name_plural': 'Price Lists',
            },
        ),
        migrations.CreateModel(
            name='PriceListLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_quantity', models.PositiveIntegerField(help_text='Minimum quantity for this price tier')),
                ('unit_price', models.DecimalField(decimal_places=4, help_text='Unit price at this quantity tier', max_digits=12)),
                ('price_list', models.ForeignKey(help_text='Parent price list header', on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='pricing.pricelisthead')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Price List Line',
                'verbose_name_plural': 'Price List Lines',
                'ordering': ['min_quantity'],
            },
        ),
        migrations.AddIndex(
            model_name='pricelisthead',
            index=models.Index(fields=['tenant', 'customer', 'item', 'begin_date'], name='pricing_pri_tenant__6004c1_idx'),
        ),
        migrations.AddIndex(
            model_name='pricelisthead',
            index=models.Index(fields=['tenant', 'is_active'], name='pricing_pri_tenant__60bcf2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pricelisthead',
            unique_together={('tenant', 'customer', 'item', 'begin_date')},
        ),
        migrations.AddIndex(
            model_name='pricelistline',
            index=models.Index(fields=['price_list', 'min_quantity'], name='pricing_pri_price_l_0eb070_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pricelistline',
            unique_together={('price_list', 'min_quantity')},
        ),
    ]
