# Generated by Django 6.0 on 2026-02-06 15:44

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0004_add_gl_accounts'),
        ('parties', '0002_add_gl_accounts'),
        ('tenants', '0002_add_vendor_bills'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalDesignRequest',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('file_number', models.CharField(blank=True, help_text='Auto-generated file number (e.g., MS20260001)', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('ident', models.CharField(blank=True, help_text='Item identifier / name', max_length=100)),
                ('style', models.CharField(blank=True, help_text='Box style (RSC, DC, FOL, etc.)', max_length=50)),
                ('length', models.DecimalField(blank=True, decimal_places=4, help_text='Length dimension', max_digits=10, null=True)),
                ('width', models.DecimalField(blank=True, decimal_places=4, help_text='Width dimension', max_digits=10, null=True)),
                ('depth', models.DecimalField(blank=True, decimal_places=4, help_text='Depth dimension', max_digits=10, null=True)),
                ('test', models.CharField(blank=True, choices=[('ect29', 'ECT 29'), ('ect32', 'ECT 32'), ('ect40', 'ECT 40'), ('ect44', 'ECT 44'), ('ect48', 'ECT 48'), ('ect51', 'ECT 51'), ('ect55', 'ECT 55'), ('ect112', 'ECT 112'), ('200t', '200T')], help_text='Board test strength', max_length=10)),
                ('flute', models.CharField(blank=True, choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('e', 'E'), ('f', 'F'), ('bc', 'BC DW'), ('eb', 'EB DW'), ('tw', 'TW')], help_text='Flute type', max_length=5)),
                ('paper', models.CharField(blank=True, choices=[('k', 'Kraft'), ('mw', 'Mottled White')], help_text='Paper grade', max_length=5)),
                ('has_ard', models.BooleanField(default=False, help_text='Has ARD (Art Ready Document)')),
                ('has_pdf', models.BooleanField(default=False, help_text='Has PDF proof')),
                ('has_eps', models.BooleanField(default=False, help_text='Has EPS file')),
                ('has_dxf', models.BooleanField(default=False, help_text='Has DXF die drawing')),
                ('has_samples', models.BooleanField(default=False, help_text='Has physical samples')),
                ('pallet_configuration', models.BooleanField(default=False, help_text='Pallet configuration determined')),
                ('sample_quantity', models.PositiveIntegerField(blank=True, help_text='Number of samples to produce', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes and requirements')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('assigned_to', models.ForeignKey(blank=True, db_constraint=False, help_text='Designer assigned to this request', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, db_constraint=False, help_text='Customer requesting the design', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='parties.party')),
                ('generated_item', models.ForeignKey(blank=True, db_constraint=False, help_text='Item created when design is promoted', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='items.item')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(blank=True, db_constraint=False, help_text='User who created the request', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'historical design request',
                'verbose_name_plural': 'historical design requests',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='DesignRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file_number', models.CharField(blank=True, help_text='Auto-generated file number (e.g., MS20260001)', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('ident', models.CharField(blank=True, help_text='Item identifier / name', max_length=100)),
                ('style', models.CharField(blank=True, help_text='Box style (RSC, DC, FOL, etc.)', max_length=50)),
                ('length', models.DecimalField(blank=True, decimal_places=4, help_text='Length dimension', max_digits=10, null=True)),
                ('width', models.DecimalField(blank=True, decimal_places=4, help_text='Width dimension', max_digits=10, null=True)),
                ('depth', models.DecimalField(blank=True, decimal_places=4, help_text='Depth dimension', max_digits=10, null=True)),
                ('test', models.CharField(blank=True, choices=[('ect29', 'ECT 29'), ('ect32', 'ECT 32'), ('ect40', 'ECT 40'), ('ect44', 'ECT 44'), ('ect48', 'ECT 48'), ('ect51', 'ECT 51'), ('ect55', 'ECT 55'), ('ect112', 'ECT 112'), ('200t', '200T')], help_text='Board test strength', max_length=10)),
                ('flute', models.CharField(blank=True, choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('e', 'E'), ('f', 'F'), ('bc', 'BC DW'), ('eb', 'EB DW'), ('tw', 'TW')], help_text='Flute type', max_length=5)),
                ('paper', models.CharField(blank=True, choices=[('k', 'Kraft'), ('mw', 'Mottled White')], help_text='Paper grade', max_length=5)),
                ('has_ard', models.BooleanField(default=False, help_text='Has ARD (Art Ready Document)')),
                ('has_pdf', models.BooleanField(default=False, help_text='Has PDF proof')),
                ('has_eps', models.BooleanField(default=False, help_text='Has EPS file')),
                ('has_dxf', models.BooleanField(default=False, help_text='Has DXF die drawing')),
                ('has_samples', models.BooleanField(default=False, help_text='Has physical samples')),
                ('pallet_configuration', models.BooleanField(default=False, help_text='Pallet configuration determined')),
                ('sample_quantity', models.PositiveIntegerField(blank=True, help_text='Number of samples to produce', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes and requirements')),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Designer assigned to this request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='design_requests_assigned', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, help_text='Customer requesting the design', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='design_requests', to='parties.party')),
                ('generated_item', models.OneToOneField(blank=True, help_text='Item created when design is promoted', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='design_request', to='items.item')),
                ('requested_by', models.ForeignKey(blank=True, help_text='User who created the request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='design_requests_created', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'status'], name='design_desi_tenant__915e43_idx'), models.Index(fields=['tenant', 'customer'], name='design_desi_tenant__fbfd8f_idx'), models.Index(fields=['tenant', 'file_number'], name='design_desi_tenant__22cdbe_idx')],
                'unique_together': {('tenant', 'file_number')},
            },
        ),
    ]
