# Generated by Django 6.0 on 2026-04-16 14:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='designrequest',
            name='checked_out_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='designrequest',
            name='checked_out_by',
            field=models.ForeignKey(blank=True, help_text='Designer who checked out this request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_out_designs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaldesignrequest',
            name='checked_out_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicaldesignrequest',
            name='checked_out_by',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Designer who checked out this request', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
