# Generated by Django 6.0 on 2026-01-12 20:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Report name', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Report description')),
                ('report_type', models.CharField(choices=[('INVENTORY_BALANCE', 'Inventory Balance'), ('INVENTORY_VALUATION', 'Inventory Valuation'), ('INVENTORY_MOVEMENT', 'Inventory Movement'), ('LOT_STATUS', 'Lot Status'), ('SALES_BY_CUSTOMER', 'Sales by Customer'), ('SALES_BY_ITEM', 'Sales by Item'), ('SALES_ORDER_STATUS', 'Sales Order Status'), ('SHIPMENT_HISTORY', 'Shipment History'), ('PURCHASES_BY_VENDOR', 'Purchases by Vendor'), ('PURCHASES_BY_ITEM', 'Purchases by Item'), ('PO_STATUS', 'PO Status'), ('AR_AGING', 'AR Aging'), ('INVOICE_STATUS', 'Invoice Status'), ('PAYMENT_HISTORY', 'Payment History'), ('CUSTOM', 'Custom Query')], help_text='Type of report (determines data source)', max_length=30)),
                ('category', models.CharField(choices=[('INVENTORY', 'Inventory'), ('SALES', 'Sales'), ('PURCHASING', 'Purchasing'), ('FINANCE', 'Finance'), ('OPERATIONS', 'Operations'), ('CUSTOM', 'Custom')], default='CUSTOM', help_text='Report category for grouping', max_length=20)),
                ('is_system', models.BooleanField(default=False, help_text='True if this is a built-in system report')),
                ('is_active', models.BooleanField(default=True, help_text='Whether report is available')),
                ('default_format', models.CharField(choices=[('TABLE', 'Table'), ('CSV', 'CSV Export'), ('PDF', 'PDF'), ('EXCEL', 'Excel')], default='TABLE', help_text='Default output format', max_length=10)),
                ('columns_config', models.JSONField(blank=True, default=list, help_text='Column definitions: [{name, label, type, sortable, width}]')),
                ('filters_config', models.JSONField(blank=True, default=list, help_text='Available filters: [{name, label, type, required, default}]')),
                ('default_filters', models.JSONField(blank=True, default=dict, help_text='Default filter values')),
                ('default_group_by', models.CharField(blank=True, help_text='Default field to group by', max_length=50)),
                ('default_sort_by', models.CharField(blank=True, help_text='Default field to sort by', max_length=50)),
                ('default_sort_order', models.CharField(choices=[('ASC', 'Ascending'), ('DESC', 'Descending')], default='ASC', help_text='Default sort order', max_length=4)),
                ('custom_query', models.TextField(blank=True, help_text='Custom SQL query (for CUSTOM type reports only)')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this report', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_reports', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Report Definition',
                'verbose_name_plural': 'Report Definitions',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ReportFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order in favorites list')),
                ('saved_filters', models.JSONField(blank=True, default=dict, help_text='Saved filter values for quick access')),
                ('report', models.ForeignKey(help_text='Favorited report', on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='reporting.reportdefinition')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
                ('user', models.ForeignKey(help_text='User', on_delete=django.db.models.deletion.CASCADE, related_name='favorite_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Report Favorite',
                'verbose_name_plural': 'Report Favorites',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='ReportSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Schedule name', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Whether schedule is active')),
                ('frequency', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly')], default='WEEKLY', help_text='How often to generate', max_length=10)),
                ('day_of_week', models.PositiveSmallIntegerField(blank=True, help_text='Day of week (0=Monday, 6=Sunday) for weekly', null=True)),
                ('day_of_month', models.PositiveSmallIntegerField(blank=True, help_text='Day of month (1-28) for monthly', null=True)),
                ('run_time', models.TimeField(default='06:00:00', help_text='Time to run (24h format)')),
                ('filter_values', models.JSONField(blank=True, default=dict, help_text='Filter values for this scheduled run')),
                ('output_format', models.CharField(choices=[('TABLE', 'Table'), ('CSV', 'CSV Export'), ('PDF', 'PDF'), ('EXCEL', 'Excel')], default='PDF', help_text='Output format', max_length=10)),
                ('email_recipients', models.TextField(blank=True, help_text='Email addresses (one per line)')),
                ('email_subject', models.CharField(blank=True, help_text='Email subject (supports {report_name}, {date})', max_length=200)),
                ('last_run', models.DateTimeField(blank=True, help_text='Last time this schedule ran', null=True)),
                ('next_run', models.DateTimeField(blank=True, help_text='Next scheduled run time', null=True)),
                ('report', models.ForeignKey(help_text='Report to generate', on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='reporting.reportdefinition')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Report Schedule',
                'verbose_name_plural': 'Report Schedules',
            },
        ),
        migrations.CreateModel(
            name='SavedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Report instance name', max_length=150)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', help_text='Generation status', max_length=10)),
                ('filter_values', models.JSONField(default=dict, help_text='Filter values used for this report')),
                ('output_format', models.CharField(choices=[('TABLE', 'Table'), ('CSV', 'CSV Export'), ('PDF', 'PDF'), ('EXCEL', 'Excel')], default='TABLE', help_text='Output format', max_length=10)),
                ('row_count', models.PositiveIntegerField(blank=True, help_text='Number of rows in result', null=True)),
                ('result_data', models.JSONField(blank=True, help_text='Report data (for TABLE format)', null=True)),
                ('file_path', models.CharField(blank=True, help_text='Path to generated file (for CSV/PDF/Excel)', max_length=500)),
                ('started_at', models.DateTimeField(blank=True, help_text='When generation started', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When generation completed', null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error message if failed')),
                ('generated_by', models.ForeignKey(blank=True, help_text='User who generated this report', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(help_text='Report definition', on_delete=django.db.models.deletion.CASCADE, related_name='saved_reports', to='reporting.reportdefinition')),
                ('schedule', models.ForeignKey(blank=True, help_text='Schedule that generated this (if scheduled)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saved_reports', to='reporting.reportschedule')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Saved Report',
                'verbose_name_plural': 'Saved Reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='reportdefinition',
            index=models.Index(fields=['tenant', 'report_type'], name='reporting_r_tenant__93b9ae_idx'),
        ),
        migrations.AddIndex(
            model_name='reportdefinition',
            index=models.Index(fields=['tenant', 'category'], name='reporting_r_tenant__0ad661_idx'),
        ),
        migrations.AddIndex(
            model_name='reportdefinition',
            index=models.Index(fields=['tenant', 'is_active'], name='reporting_r_tenant__5d5832_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='reportdefinition',
            unique_together={('tenant', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='reportfavorite',
            unique_together={('user', 'report')},
        ),
        migrations.AddIndex(
            model_name='reportschedule',
            index=models.Index(fields=['tenant', 'is_active', 'next_run'], name='reporting_r_tenant__da4b11_idx'),
        ),
        migrations.AddIndex(
            model_name='savedreport',
            index=models.Index(fields=['tenant', 'report', 'created_at'], name='reporting_s_tenant__6a5be1_idx'),
        ),
        migrations.AddIndex(
            model_name='savedreport',
            index=models.Index(fields=['tenant', 'status'], name='reporting_s_tenant__97ce9d_idx'),
        ),
        migrations.AddIndex(
            model_name='savedreport',
            index=models.Index(fields=['tenant', 'generated_by', 'created_at'], name='reporting_s_tenant__868840_idx'),
        ),
    ]
