# Generated by Django 6.0 on 2026-01-09 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parties', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text="Warehouse name (e.g., 'Main Warehouse')", max_length=100)),
                ('code', models.CharField(help_text="Short code (e.g., 'MAIN', 'COLD')", max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive warehouses are hidden from selections')),
                ('is_default', models.BooleanField(default=False, help_text='Default warehouse for receiving and shipping')),
                ('notes', models.TextField(blank=True, help_text='Notes about this warehouse')),
                ('location', models.ForeignKey(blank=True, help_text='Physical address of this warehouse', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='warehouses', to='parties.location')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name_plural': 'Warehouses',
            },
        ),
        migrations.CreateModel(
            name='Bin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text="Bin identifier (e.g., 'A-01-01')", max_length=50)),
                ('aisle', models.CharField(blank=True, help_text='Aisle identifier', max_length=10)),
                ('rack', models.CharField(blank=True, help_text='Rack/bay identifier', max_length=10)),
                ('level', models.CharField(blank=True, help_text='Level/shelf identifier', max_length=10)),
                ('bin_type', models.CharField(choices=[('STORAGE', 'Storage'), ('STAGING', 'Staging'), ('RECEIVING', 'Receiving'), ('SHIPPING', 'Shipping'), ('DAMAGED', 'Damaged/Hold')], default='STORAGE', help_text='Type of bin/location', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive bins are hidden from selections')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
                ('warehouse', models.ForeignKey(help_text='Warehouse this bin is located in', on_delete=django.db.models.deletion.CASCADE, related_name='bins', to='new_warehousing.warehouse')),
            ],
            options={
                'ordering': ['warehouse', 'code'],
            },
        ),
        migrations.AddIndex(
            model_name='warehouse',
            index=models.Index(fields=['tenant', 'code'], name='new_warehou_tenant__d167b5_idx'),
        ),
        migrations.AddIndex(
            model_name='warehouse',
            index=models.Index(fields=['tenant', 'is_active'], name='new_warehou_tenant__b768bf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='warehouse',
            unique_together={('tenant', 'code')},
        ),
        migrations.AddIndex(
            model_name='bin',
            index=models.Index(fields=['warehouse', 'code'], name='new_warehou_warehou_4a4972_idx'),
        ),
        migrations.AddIndex(
            model_name='bin',
            index=models.Index(fields=['warehouse', 'is_active'], name='new_warehou_warehou_f973d1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bin',
            unique_together={('warehouse', 'code')},
        ),
    ]
