# Generated by Django 6.0 on 2026-02-06 19:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_add_gl_accounts'),
        ('new_warehousing', '0001_initial'),
        ('tenants', '0002_add_vendor_bills'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lot_number', models.CharField(help_text='Lot or batch number', max_length=50)),
                ('vendor_batch', models.CharField(blank=True, help_text="Vendor's batch identifier", max_length=100)),
                ('expiry_date', models.DateField(blank=True, help_text='Expiration date for FEFO picking', null=True)),
                ('item', models.ForeignKey(help_text='Item this lot belongs to', on_delete=django.db.models.deletion.PROTECT, related_name='lots', to='items.item')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='WarehouseLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text="Location name (e.g., 'A-01-01')", max_length=50)),
                ('barcode', models.CharField(help_text='Scannable barcode for this location', max_length=100)),
                ('type', models.CharField(choices=[('RECEIVING_DOCK', 'Receiving Dock'), ('STORAGE', 'Storage'), ('PICKING', 'Picking'), ('PACKING', 'Packing'), ('SHIPPING_DOCK', 'Shipping Dock'), ('SCRAP', 'Scrap')], help_text='Type of warehouse zone', max_length=20)),
                ('parent_path', models.CharField(blank=True, help_text="Hierarchical path (e.g., 'Zone A / Aisle 1')", max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive locations are hidden from selections')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
                ('warehouse', models.ForeignKey(help_text='Warehouse this location belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='new_warehousing.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='StockQuant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=4, default=0, help_text='Quantity on hand at this location', max_digits=14)),
                ('item', models.ForeignKey(help_text='Item stored in this quant', on_delete=django.db.models.deletion.PROTECT, related_name='quants', to='items.item')),
                ('lot', models.ForeignKey(blank=True, help_text='Lot/batch (optional)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quants', to='new_warehousing.lot')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
                ('location', models.ForeignKey(help_text='Location where this stock is stored', on_delete=django.db.models.deletion.PROTECT, related_name='quants', to='new_warehousing.warehouselocation')),
            ],
        ),
        migrations.CreateModel(
            name='StockMoveLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=4, help_text='Quantity moved', max_digits=14)),
                ('reference', models.CharField(blank=True, help_text="Reference (e.g., 'PO-000123 putaway', 'SO-000456 pick')", max_length=200)),
                ('item', models.ForeignKey(help_text='Item that was moved', on_delete=django.db.models.deletion.PROTECT, related_name='stock_moves', to='items.item')),
                ('lot', models.ForeignKey(blank=True, help_text='Lot/batch (optional)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='moves', to='new_warehousing.lot')),
                ('moved_by', models.ForeignKey(blank=True, help_text='User who executed the move', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
                ('destination_location', models.ForeignKey(help_text='Location stock was moved to', on_delete=django.db.models.deletion.PROTECT, related_name='moves_in', to='new_warehousing.warehouselocation')),
                ('source_location', models.ForeignKey(help_text='Location stock was moved from', on_delete=django.db.models.deletion.PROTECT, related_name='moves_out', to='new_warehousing.warehouselocation')),
            ],
        ),
        migrations.AddIndex(
            model_name='lot',
            index=models.Index(fields=['tenant', 'lot_number'], name='new_warehou_tenant__418101_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='lot',
            unique_together={('tenant', 'item', 'lot_number')},
        ),
        migrations.AddIndex(
            model_name='warehouselocation',
            index=models.Index(fields=['tenant', 'warehouse', 'type'], name='new_warehou_tenant__8f5ab3_idx'),
        ),
        migrations.AddIndex(
            model_name='warehouselocation',
            index=models.Index(fields=['tenant', 'barcode'], name='new_warehou_tenant__f56b1e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='warehouselocation',
            unique_together={('tenant', 'barcode')},
        ),
        migrations.AddIndex(
            model_name='stockquant',
            index=models.Index(fields=['tenant', 'item', 'location'], name='new_warehou_tenant__be29b1_idx'),
        ),
        migrations.AddIndex(
            model_name='stockquant',
            index=models.Index(fields=['tenant', 'location'], name='new_warehou_tenant__eef02e_idx'),
        ),
        migrations.AddConstraint(
            model_name='stockquant',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 0)), name='quant_qty_non_negative'),
        ),
        migrations.AlterUniqueTogether(
            name='stockquant',
            unique_together={('tenant', 'item', 'location', 'lot')},
        ),
        migrations.AddIndex(
            model_name='stockmovelog',
            index=models.Index(fields=['tenant', 'item', 'created_at'], name='new_warehou_tenant__4587ef_idx'),
        ),
    ]
