# Generated by Django 6.0 on 2026-02-16 15:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_item_min_stock_item_reorder_point_item_safety_stock_and_more'),
        ('new_warehousing', '0002_lot_warehouselocation_stockquant_stockmovelog_and_more'),
        ('tenants', '0002_add_vendor_bills'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CycleCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('count_number', models.CharField(help_text='Cycle count session ID (e.g., CC-2026-001)', max_length=50)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, help_text='When counting began', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When count was finalized', null=True)),
                ('notes', models.TextField(blank=True, help_text='Notes about this cycle count')),
            ],
        ),
        migrations.CreateModel(
            name='CycleCountLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expected_quantity', models.DecimalField(decimal_places=4, default=0, help_text='System quantity at time of snapshot', max_digits=14)),
                ('counted_quantity', models.DecimalField(blank=True, decimal_places=4, help_text='Actual quantity counted by user', max_digits=14, null=True)),
                ('variance', models.DecimalField(decimal_places=4, default=0, help_text='counted - expected (positive = overage, negative = shortage)', max_digits=14)),
                ('is_counted', models.BooleanField(default=False, help_text='Whether this line has been counted')),
            ],
        ),
        migrations.AddField(
            model_name='lot',
            name='manufacturer_batch_id',
            field=models.CharField(blank=True, help_text="Manufacturer's original batch/lot ID", max_length=100),
        ),
        migrations.AddField(
            model_name='stockquant',
            name='reserved_quantity',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Quantity reserved for pending orders', max_digits=14),
        ),
        migrations.AddField(
            model_name='warehouselocation',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Parent location for hierarchy (Warehouse > Zone > Bin)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='new_warehousing.warehouselocation'),
        ),
        migrations.AlterField(
            model_name='warehouselocation',
            name='type',
            field=models.CharField(choices=[('VIEW', 'View (Virtual)'), ('INTERNAL', 'Internal'), ('CUSTOMER', 'Customer'), ('INVENTORY', 'Inventory'), ('PRODUCTION', 'Production'), ('RECEIVING_DOCK', 'Receiving Dock'), ('STORAGE', 'Storage'), ('PICKING', 'Picking'), ('PACKING', 'Packing'), ('SHIPPING_DOCK', 'Shipping Dock'), ('SCRAP', 'Scrap')], help_text='Type of warehouse zone', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='stockquant',
            constraint=models.CheckConstraint(condition=models.Q(('reserved_quantity__gte', 0)), name='quant_reserved_non_negative'),
        ),
        migrations.AddField(
            model_name='cyclecount',
            name='counted_by',
            field=models.ForeignKey(blank=True, help_text='User performing the count', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cycle_counts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cyclecount',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='cyclecount',
            name='warehouse',
            field=models.ForeignKey(help_text='Warehouse being counted', on_delete=django.db.models.deletion.CASCADE, related_name='cycle_counts', to='new_warehousing.warehouse'),
        ),
        migrations.AddField(
            model_name='cyclecount',
            name='zone',
            field=models.ForeignKey(blank=True, help_text='Specific zone/location to count (blank = entire warehouse)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cycle_counts', to='new_warehousing.warehouselocation'),
        ),
        migrations.AddField(
            model_name='cyclecountline',
            name='cycle_count',
            field=models.ForeignKey(help_text='Parent cycle count session', on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='new_warehousing.cyclecount'),
        ),
        migrations.AddField(
            model_name='cyclecountline',
            name='item',
            field=models.ForeignKey(help_text='Item being counted', on_delete=django.db.models.deletion.PROTECT, related_name='cycle_count_lines', to='items.item'),
        ),
        migrations.AddField(
            model_name='cyclecountline',
            name='location',
            field=models.ForeignKey(help_text='Location being counted', on_delete=django.db.models.deletion.PROTECT, related_name='cycle_count_lines', to='new_warehousing.warehouselocation'),
        ),
        migrations.AddField(
            model_name='cyclecountline',
            name='lot',
            field=models.ForeignKey(blank=True, help_text='Lot being counted (if lot-tracked)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cycle_count_lines', to='new_warehousing.lot'),
        ),
        migrations.AddField(
            model_name='cyclecountline',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddIndex(
            model_name='cyclecount',
            index=models.Index(fields=['tenant', 'status'], name='new_warehou_tenant__2ec5c7_idx'),
        ),
        migrations.AddIndex(
            model_name='cyclecount',
            index=models.Index(fields=['tenant', 'warehouse'], name='new_warehou_tenant__010470_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cyclecount',
            unique_together={('tenant', 'count_number')},
        ),
        migrations.AddIndex(
            model_name='cyclecountline',
            index=models.Index(fields=['cycle_count', 'is_counted'], name='new_warehou_cycle_c_bcf978_idx'),
        ),
    ]
