# Generated by Django 6.0 on 2026-02-16 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_item_min_stock_item_reorder_point_item_safety_stock_and_more'),
        ('new_warehousing', '0003_cyclecount_cyclecountline_lot_manufacturer_batch_id_and_more'),
        ('tenants', '0002_add_vendor_bills'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='stockquant',
            constraint=models.CheckConstraint(condition=models.Q(('reserved_quantity__lte', models.F('quantity'))), name='quant_reserved_lte_qty'),
        ),
    ]
