# Generated by Django 6.0 on 2026-06-23 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_warehousing', '0005_warehouse_pallet_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='bin',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Bin height (inches)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='bin',
            name='length',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Bin length (inches)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='bin',
            name='max_capacity',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum units/pallets this bin can hold', null=True),
        ),
        migrations.AddField(
            model_name='bin',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Bin width (inches)', max_digits=10, null=True),
        ),
    ]
