# Generated by Django 6.0 on 2025-12-12 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=255)),
                ('is_customer', models.BooleanField(default=True)),
                ('is_vendor', models.BooleanField(default=True)),
            ],
        ),
    ]
