# Generated by Django 6.0 on 2026-02-05 21:17

import django.db.models.deletion
import simple_history.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text="Account code (e.g., '1000', '1100.10')", max_length=20)),
                ('name', models.CharField(help_text="Account name (e.g., 'Cash on Hand')", max_length=255)),
                ('description', models.TextField(blank=True, help_text='Detailed description of account usage')),
                ('account_type', models.CharField(choices=[('ASSET_CURRENT', 'Current Assets'), ('ASSET_FIXED', 'Fixed Assets'), ('ASSET_OTHER', 'Other Assets'), ('CONTRA_ASSET', 'Contra Assets'), ('LIABILITY_CURRENT', 'Current Liabilities'), ('LIABILITY_LONG_TERM', 'Long-Term Liabilities'), ('EQUITY', 'Equity'), ('REVENUE', 'Revenue'), ('REVENUE_OTHER', 'Other Income'), ('CONTRA_REVENUE', 'Sales Returns & Allowances'), ('EXPENSE_COGS', 'Cost of Goods Sold'), ('EXPENSE_OPERATING', 'Operating Expenses'), ('EXPENSE_OTHER', 'Other Expenses')], help_text='Classification determining normal balance', max_length=30)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive accounts cannot receive new transactions')),
                ('is_system', models.BooleanField(default=False, help_text='System accounts cannot be deleted (AR, AP, etc.)')),
                ('entity_id', models.PositiveIntegerField(blank=True, null=True)),
                ('entity_type', models.ForeignKey(blank=True, help_text='Entity type for sub-ledger accounts', null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('parent', models.ForeignKey(blank=True, help_text='Parent account for sub-accounts', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='accounting.account')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Chart of Accounts',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='AccountingSettings',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='accounting_settings', serialize=False, to='tenants.tenant')),
                ('default_ap_account', models.ForeignKey(blank=True, help_text='Default A/P account for vendors (typically 2010 A/P Trade)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.account')),
                ('default_ar_account', models.ForeignKey(blank=True, help_text='Default A/R account for customers (typically 1110 A/R Trade)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.account')),
                ('default_cash_account', models.ForeignKey(blank=True, help_text='Default cash account for payments (typically 1020 Operating)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.account')),
                ('default_cogs_account', models.ForeignKey(blank=True, help_text='Default COGS account (typically 5000 Cost of Goods Sold)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.account')),
                ('default_freight_expense_account', models.ForeignKey(blank=True, help_text='Default account for freight costs', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.account')),
                ('default_freight_income_account', models.ForeignKey(blank=True, help_text='Default account for freight charged to customers', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.account')),
                ('default_income_account', models.ForeignKey(blank=True, help_text='Default revenue account for sales (typically 4000 Sales Revenue)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.account')),
                ('default_inventory_account', models.ForeignKey(blank=True, help_text='Default inventory asset account (typically 1230 Finished Goods)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.account')),
                ('default_purchase_discount_account', models.ForeignKey(blank=True, help_text='Default account for purchase discounts received', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.account')),
                ('default_sales_discount_account', models.ForeignKey(blank=True, help_text='Default account for sales discounts given', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.account')),
            ],
            options={
                'verbose_name': 'Accounting Settings',
                'verbose_name_plural': 'Accounting Settings',
            },
        ),
        migrations.CreateModel(
            name='FiscalPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text="Period name (e.g., 'January 2026', 'Q1 2026')", max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('soft_close', 'Soft Close'), ('closed', 'Closed')], default='open', max_length=20)),
                ('is_year_end', models.BooleanField(default=False, help_text='Mark if this is a year-end closing period')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='AccountBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_debit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total debits in period', max_digits=20)),
                ('period_credit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total credits in period', max_digits=20)),
                ('beginning_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Balance at start of period', max_digits=20)),
                ('ending_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Balance at end of period', max_digits=20)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance_cache', to='accounting.account')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
                ('fiscal_period', models.ForeignKey(blank=True, help_text='Period for period-specific balance, null for running balance', null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.fiscalperiod')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalAccount',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('code', models.CharField(help_text="Account code (e.g., '1000', '1100.10')", max_length=20)),
                ('name', models.CharField(help_text="Account name (e.g., 'Cash on Hand')", max_length=255)),
                ('description', models.TextField(blank=True, help_text='Detailed description of account usage')),
                ('account_type', models.CharField(choices=[('ASSET_CURRENT', 'Current Assets'), ('ASSET_FIXED', 'Fixed Assets'), ('ASSET_OTHER', 'Other Assets'), ('CONTRA_ASSET', 'Contra Assets'), ('LIABILITY_CURRENT', 'Current Liabilities'), ('LIABILITY_LONG_TERM', 'Long-Term Liabilities'), ('EQUITY', 'Equity'), ('REVENUE', 'Revenue'), ('REVENUE_OTHER', 'Other Income'), ('CONTRA_REVENUE', 'Sales Returns & Allowances'), ('EXPENSE_COGS', 'Cost of Goods Sold'), ('EXPENSE_OPERATING', 'Operating Expenses'), ('EXPENSE_OTHER', 'Other Expenses')], help_text='Classification determining normal balance', max_length=30)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive accounts cannot receive new transactions')),
                ('is_system', models.BooleanField(default=False, help_text='System accounts cannot be deleted (AR, AP, etc.)')),
                ('entity_id', models.PositiveIntegerField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('entity_type', models.ForeignKey(blank=True, db_constraint=False, help_text='Entity type for sub-ledger accounts', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contenttypes.contenttype')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, db_constraint=False, help_text='Parent account for sub-accounts', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounting.account')),
                ('tenant', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'historical Account',
                'verbose_name_plural': 'historical Chart of Accounts',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entry_number', models.CharField(help_text="Auto-generated entry number (e.g., 'JE-2026-0001')", max_length=30)),
                ('date', models.DateField(help_text='Transaction date')),
                ('memo', models.CharField(help_text='Description of the transaction', max_length=500)),
                ('reference_number', models.CharField(blank=True, help_text='External reference (invoice #, check #, etc.)', max_length=100)),
                ('entry_type', models.CharField(choices=[('standard', 'Standard Entry'), ('adjusting', 'Adjusting Entry'), ('closing', 'Closing Entry'), ('reversing', 'Reversing Entry'), ('recurring', 'Recurring Entry')], default='standard', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('reversed', 'Reversed')], default='draft', max_length=20)),
                ('source_id', models.PositiveIntegerField(blank=True, null=True)),
                ('posted_at', models.DateTimeField(blank=True, help_text='Timestamp when entry was posted', null=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this entry', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_journal_entries', to=settings.AUTH_USER_MODEL)),
                ('fiscal_period', models.ForeignKey(blank=True, help_text='Fiscal period for this entry', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='journal_entries', to='accounting.fiscalperiod')),
                ('posted_by', models.ForeignKey(blank=True, help_text='User who posted this entry', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='posted_journal_entries', to=settings.AUTH_USER_MODEL)),
                ('reversed_by', models.ForeignKey(blank=True, help_text='Entry that reversed this entry', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reverses', to='accounting.journalentry')),
                ('source_type', models.ForeignKey(blank=True, help_text='Type of source document', null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Journal Entry',
                'verbose_name_plural': 'Journal Entries',
                'ordering': ['-date', '-entry_number'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalJournalEntry',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('entry_number', models.CharField(help_text="Auto-generated entry number (e.g., 'JE-2026-0001')", max_length=30)),
                ('date', models.DateField(help_text='Transaction date')),
                ('memo', models.CharField(help_text='Description of the transaction', max_length=500)),
                ('reference_number', models.CharField(blank=True, help_text='External reference (invoice #, check #, etc.)', max_length=100)),
                ('entry_type', models.CharField(choices=[('standard', 'Standard Entry'), ('adjusting', 'Adjusting Entry'), ('closing', 'Closing Entry'), ('reversing', 'Reversing Entry'), ('recurring', 'Recurring Entry')], default='standard', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('reversed', 'Reversed')], default='draft', max_length=20)),
                ('source_id', models.PositiveIntegerField(blank=True, null=True)),
                ('posted_at', models.DateTimeField(blank=True, help_text='Timestamp when entry was posted', null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, help_text='User who created this entry', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('fiscal_period', models.ForeignKey(blank=True, db_constraint=False, help_text='Fiscal period for this entry', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounting.fiscalperiod')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('posted_by', models.ForeignKey(blank=True, db_constraint=False, help_text='User who posted this entry', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('source_type', models.ForeignKey(blank=True, db_constraint=False, help_text='Type of source document', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contenttypes.contenttype')),
                ('tenant', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tenants.tenant')),
                ('reversed_by', models.ForeignKey(blank=True, db_constraint=False, help_text='Entry that reversed this entry', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounting.journalentry')),
            ],
            options={
                'verbose_name': 'historical Journal Entry',
                'verbose_name_plural': 'historical Journal Entries',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='JournalEntryLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_number', models.PositiveIntegerField(default=10, help_text='Line sequence (10, 20, 30...)')),
                ('description', models.CharField(blank=True, help_text='Line-specific description', max_length=500)),
                ('debit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Debit amount (left side of T-account)', max_digits=20)),
                ('credit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Credit amount (right side of T-account)', max_digits=20)),
                ('entity_id', models.PositiveIntegerField(blank=True, null=True)),
                ('account', models.ForeignKey(help_text='Account to debit or credit', on_delete=django.db.models.deletion.PROTECT, related_name='journal_lines', to='accounting.account')),
                ('entity_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('entry', models.ForeignKey(help_text='Parent journal entry', on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='accounting.journalentry')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Journal Entry Line',
                'verbose_name_plural': 'Journal Entry Lines',
                'ordering': ['entry', 'line_number'],
            },
        ),
        migrations.CreateModel(
            name='RecurringEntryTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('memo', models.CharField(max_length=500)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annually', 'Annually')], default='monthly', max_length=20)),
                ('next_date', models.DateField(help_text='Next scheduled execution date')),
                ('end_date', models.DateField(blank=True, help_text='Stop generating after this date', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('auto_post', models.BooleanField(default=False, help_text='Automatically post generated entries')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'ordering': ['next_date'],
            },
        ),
        migrations.CreateModel(
            name='RecurringEntryLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_number', models.PositiveIntegerField(default=10)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('debit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('credit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.account')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='accounting.recurringentrytemplate')),
            ],
            options={
                'ordering': ['template', 'line_number'],
            },
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['tenant', 'code'], name='accounting__tenant__a89231_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['tenant', 'account_type'], name='accounting__tenant__e1d931_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['tenant', 'is_active'], name='accounting__tenant__c2d8e0_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['tenant', 'parent'], name='accounting__tenant__954c25_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='account',
            unique_together={('tenant', 'code')},
        ),
        migrations.AddIndex(
            model_name='fiscalperiod',
            index=models.Index(fields=['tenant', 'start_date'], name='accounting__tenant__394b94_idx'),
        ),
        migrations.AddIndex(
            model_name='fiscalperiod',
            index=models.Index(fields=['tenant', 'status'], name='accounting__tenant__d4608d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='fiscalperiod',
            unique_together={('tenant', 'start_date', 'end_date')},
        ),
        migrations.AddIndex(
            model_name='accountbalance',
            index=models.Index(fields=['tenant', 'account'], name='accounting__tenant__290545_idx'),
        ),
        migrations.AddIndex(
            model_name='accountbalance',
            index=models.Index(fields=['tenant', 'fiscal_period'], name='accounting__tenant__eee96e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='accountbalance',
            unique_together={('tenant', 'account', 'fiscal_period')},
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['tenant', 'entry_number'], name='accounting__tenant__dd4888_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['tenant', 'date'], name='accounting__tenant__e6ad26_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['tenant', 'status'], name='accounting__tenant__9f3b5b_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['tenant', 'entry_type'], name='accounting__tenant__c96631_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['source_type', 'source_id'], name='accounting__source__1fba69_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='journalentry',
            unique_together={('tenant', 'entry_number')},
        ),
        migrations.AddIndex(
            model_name='journalentryline',
            index=models.Index(fields=['tenant', 'entry'], name='accounting__tenant__eab8fa_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentryline',
            index=models.Index(fields=['tenant', 'account'], name='accounting__tenant__7397a3_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentryline',
            index=models.Index(fields=['entity_type', 'entity_id'], name='accounting__entity__4c444a_idx'),
        ),
        migrations.AddIndex(
            model_name='recurringentrytemplate',
            index=models.Index(fields=['tenant', 'is_active', 'next_date'], name='accounting__tenant__87b015_idx'),
        ),
    ]
