# Generated by Django 6.0 on 2026-02-18 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountingsettings',
            name='default_sales_tax_account',
            field=models.ForeignKey(blank=True, help_text='Default GL account for sales tax liability', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.account'),
        ),
    ]
