# Generated by Django 6.0 on 2026-05-22 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_accountingsettings_default_sales_tax_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountingsettings',
            name='default_grir_account',
            field=models.ForeignKey(blank=True, help_text='Default GR/IR (Received-Not-Billed) clearing account, typically a current liability like 2050', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.account'),
        ),
    ]
