# Generated by Django 6.0 on 2026-02-06 16:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('tenants', '0002_add_vendor_bills'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object_id', models.PositiveBigIntegerField(help_text='ID of the related object')),
                ('file', models.FileField(help_text='Uploaded file', upload_to='attachments/%Y/%m/')),
                ('filename', models.CharField(help_text='Original filename', max_length=255)),
                ('mime_type', models.CharField(blank=True, help_text='MIME type (e.g., application/pdf, image/png)', max_length=100)),
                ('file_size', models.PositiveBigIntegerField(default=0, help_text='File size in bytes')),
                ('category', models.CharField(choices=[('document', 'Document'), ('generated_pdf', 'Generated PDF'), ('image', 'Image'), ('spreadsheet', 'Spreadsheet'), ('other', 'Other')], default='document', help_text='Attachment category', max_length=20)),
                ('description', models.CharField(blank=True, help_text='Optional description', max_length=255)),
                ('content_type', models.ForeignKey(help_text='Type of the related object', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
                ('uploaded_by', models.ForeignKey(blank=True, help_text='User who uploaded this file', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'content_type', 'object_id'], name='documents_a_tenant__0f6f7f_idx'), models.Index(fields=['tenant', 'category'], name='documents_a_tenant__899241_idx')],
            },
        ),
    ]
