# Generated by Django 6.0 on 2026-06-30 17:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('documents', '0001_initial'),
        ('tenants', '0009_alter_tenantsequence_sequence_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_object_id', models.PositiveBigIntegerField(help_text='ID of the source (producing) document')),
                ('target_object_id', models.PositiveBigIntegerField(help_text='ID of the target (produced) document')),
                ('relation', models.CharField(choices=[('estimate_to_sales_order', 'Estimate → Sales Order'), ('estimate_to_contract', 'Estimate → Contract'), ('rfq_to_purchase_order', 'RFQ → Purchase Order'), ('contract_release', 'Contract → Sales Order (Release)'), ('sales_order_to_pick_ticket', 'Sales Order → Pick Ticket'), ('pick_ticket_to_shipment', 'Pick Ticket → Shipment'), ('bol_from_shipment', 'Shipment → Bill of Lading'), ('invoice_from_order', 'Sales Order → Invoice'), ('invoice_from_shipment', 'Shipment → Invoice'), ('invoice_from_picks', 'Pick Ticket → Invoice'), ('payment_for_invoice', 'Invoice → Payment'), ('po_to_item_receipt', 'Purchase Order → Item Receipt'), ('bill_from_receipt', 'Item Receipt → Vendor Bill'), ('other', 'Other')], help_text='The pipeline transition this link represents', max_length=40)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who triggered the conversion that created this link', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_document_links', to=settings.AUTH_USER_MODEL)),
                ('source_content_type', models.ForeignKey(help_text='Type of the source (producing) document', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.contenttype')),
                ('target_content_type', models.ForeignKey(help_text='Type of the target (produced) document', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.contenttype')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'source_content_type', 'source_object_id'], name='documents_d_tenant__10d68c_idx'), models.Index(fields=['tenant', 'target_content_type', 'target_object_id'], name='documents_d_tenant__3674c5_idx')],
                'unique_together': {('tenant', 'source_content_type', 'source_object_id', 'target_content_type', 'target_object_id', 'relation')},
            },
        ),
    ]
