# Generated by Django 6.0 on 2026-01-09 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0001_initial'),
        ('parties', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostListHead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('begin_date', models.DateField(help_text='Start date for this cost list')),
                ('end_date', models.DateField(blank=True, help_text='End date (null = no expiration)', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive cost lists are ignored in costing calculations')),
                ('notes', models.TextField(blank=True, help_text='Internal notes about this cost list')),
                ('item', models.ForeignKey(help_text='Item this cost list applies to', on_delete=django.db.models.deletion.CASCADE, related_name='cost_lists', to='items.item')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
                ('vendor', models.ForeignKey(help_text='Vendor this cost list is from', on_delete=django.db.models.deletion.CASCADE, related_name='cost_lists', to='parties.vendor')),
            ],
            options={
                'verbose_name': 'Cost List',
                'verbose_name_plural': 'Cost Lists',
            },
        ),
        migrations.CreateModel(
            name='CostListLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_quantity', models.PositiveIntegerField(help_text='Minimum quantity for this cost tier')),
                ('unit_cost', models.DecimalField(decimal_places=4, help_text='Unit cost at this quantity tier', max_digits=12)),
                ('cost_list', models.ForeignKey(help_text='Parent cost list header', on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='costing.costlisthead')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Cost List Line',
                'verbose_name_plural': 'Cost List Lines',
                'ordering': ['min_quantity'],
            },
        ),
        migrations.AddIndex(
            model_name='costlisthead',
            index=models.Index(fields=['tenant', 'vendor', 'item', 'begin_date'], name='costing_cos_tenant__67c13f_idx'),
        ),
        migrations.AddIndex(
            model_name='costlisthead',
            index=models.Index(fields=['tenant', 'is_active'], name='costing_cos_tenant__01718a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='costlisthead',
            unique_together={('tenant', 'vendor', 'item', 'begin_date')},
        ),
        migrations.AddIndex(
            model_name='costlistline',
            index=models.Index(fields=['cost_list', 'min_quantity'], name='costing_cos_cost_li_816b01_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='costlistline',
            unique_together={('cost_list', 'min_quantity')},
        ),
    ]
