# Generated by Django 6.0 on 2026-01-09 18:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('party_type', models.CharField(choices=[('CUSTOMER', 'Customer'), ('VENDOR', 'Vendor'), ('BOTH', 'Customer & Vendor'), ('OTHER', 'Other')], default='CUSTOMER', help_text='Primary relationship type', max_length=10)),
                ('code', models.CharField(help_text='Internal abbreviation/code (unique per tenant)', max_length=50)),
                ('display_name', models.CharField(help_text='Primary display name', max_length=255)),
                ('legal_name', models.CharField(blank=True, help_text='Official legal name', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive parties are hidden from selections')),
                ('notes', models.TextField(blank=True, help_text='General notes about this party')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name_plural': 'parties',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location_type', models.CharField(choices=[('SHIP_TO', 'Ship To'), ('BILL_TO', 'Bill To'), ('WAREHOUSE', 'Warehouse'), ('OFFICE', 'Office')], default='SHIP_TO', help_text='Type of location', max_length=20)),
                ('name', models.CharField(help_text="Location name (e.g., 'Main Warehouse', 'NY Office')", max_length=255)),
                ('code', models.CharField(blank=True, help_text='Optional location code', max_length=50)),
                ('address_line1', models.CharField(help_text='Street address line 1', max_length=255)),
                ('address_line2', models.CharField(blank=True, help_text='Street address line 2', max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=50)),
                ('postal_code', models.CharField(max_length=20)),
                ('country', models.CharField(default='USA', max_length=100)),
                ('phone', models.CharField(blank=True, help_text='Location contact phone', max_length=20)),
                ('email', models.EmailField(blank=True, help_text='Location contact email', max_length=254)),
                ('loading_dock_hours', models.CharField(blank=True, help_text="e.g., 'M-F 8am-5pm'", max_length=100)),
                ('special_instructions', models.TextField(blank=True, help_text='Delivery instructions, dock info, etc.')),
                ('is_default', models.BooleanField(default=False, help_text='Default location for this party')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive locations are hidden from selections')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
                ('party', models.ForeignKey(help_text='The party this location belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='parties.party')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_terms', models.CharField(default='NET30', help_text='Default payment terms (e.g., NET30, NET60, COD)', max_length=50)),
                ('sales_rep', models.ForeignKey(blank=True, help_text='Account manager / sales representative', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
                ('default_bill_to', models.ForeignKey(blank=True, help_text='Default billing address', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers_bill_to', to='parties.location')),
                ('default_ship_to', models.ForeignKey(blank=True, help_text='Default shipping address', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers_ship_to', to='parties.location')),
                ('party', models.OneToOneField(help_text='The party this customer record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='parties.party')),
            ],
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text="Truck name (e.g., 'Truck 1', 'Semi-Trailer A')", max_length=100)),
                ('license_plate', models.CharField(blank=True, help_text='Vehicle license plate number', max_length=20)),
                ('capacity_pallets', models.PositiveIntegerField(blank=True, help_text='Maximum pallet capacity', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive trucks are hidden from scheduling')),
                ('notes', models.TextField(blank=True, help_text='Notes about this truck')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_terms', models.CharField(default='NET30', help_text='Payment terms for orders from this vendor', max_length=50)),
                ('buyer', models.ForeignKey(blank=True, help_text='Purchasing agent / buyer responsible for this vendor', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_vendors', to=settings.AUTH_USER_MODEL)),
                ('default_ship_from', models.ForeignKey(blank=True, help_text="Vendor's primary shipping location", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendors_ship_from', to='parties.location')),
                ('party', models.OneToOneField(help_text='The party this vendor record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='vendor', to='parties.party')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
        ),
        migrations.AddIndex(
            model_name='party',
            index=models.Index(fields=['tenant', 'display_name'], name='parties_par_tenant__1e7787_idx'),
        ),
        migrations.AddIndex(
            model_name='party',
            index=models.Index(fields=['tenant', 'code'], name='parties_par_tenant__d041ac_idx'),
        ),
        migrations.AddIndex(
            model_name='party',
            index=models.Index(fields=['tenant', 'is_active'], name='parties_par_tenant__b68389_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='party',
            unique_together={('tenant', 'code')},
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['tenant', 'party', 'is_active'], name='parties_loc_tenant__cafb0e_idx'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['location_type'], name='parties_loc_locatio_edbf3c_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['tenant', 'party'], name='parties_cus_tenant__477ba5_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['sales_rep'], name='parties_cus_sales_r_4f7f78_idx'),
        ),
        migrations.AddIndex(
            model_name='truck',
            index=models.Index(fields=['tenant', 'name'], name='parties_tru_tenant__8bbdcf_idx'),
        ),
        migrations.AddIndex(
            model_name='truck',
            index=models.Index(fields=['is_active'], name='parties_tru_is_acti_e668f6_idx'),
        ),
        migrations.AddIndex(
            model_name='vendor',
            index=models.Index(fields=['tenant', 'party'], name='parties_ven_tenant__4ab69a_idx'),
        ),
        migrations.AddIndex(
            model_name='vendor',
            index=models.Index(fields=['buyer'], name='parties_ven_buyer_i_1507b0_idx'),
        ),
    ]
