# Generated by Django 6.0 on 2026-02-05 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
        ('parties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='receivable_account',
            field=models.ForeignKey(blank=True, help_text='Override A/R account for this customer (uses default if blank)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers_receivable', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='payable_account',
            field=models.ForeignKey(blank=True, help_text='Override A/P account for this vendor (uses default if blank)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendors_payable', to='accounting.account'),
        ),
    ]
