# Generated by Django 6.0 on 2026-02-16 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0005_historicalinvoice_dunning_count_and_more'),
        ('parties', '0003_add_parent_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='default_tax_zone',
            field=models.ForeignKey(blank=True, help_text='Default tax zone for this customer (used when ship-to zip has no rule)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='invoicing.taxzone'),
        ),
    ]
