# Generated by Django 6.0 on 2026-02-17 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0004_customer_default_tax_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='credit_limit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Credit limit for this customer (approval triggered when exceeded)', max_digits=12, null=True),
        ),
    ]
