# Generated by Django 6.0 on 2026-02-20 19:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_accountingsettings_default_sales_tax_account'),
        ('invoicing', '0005_historicalinvoice_dunning_count_and_more'),
        ('parties', '0005_customer_credit_limit'),
        ('tenants', '0003_onboarding_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='charge_freight',
            field=models.BooleanField(default=True, help_text="Whether freight charges are applied to this customer's orders"),
        ),
        migrations.AddField(
            model_name='customer',
            name='csr',
            field=models.ForeignKey(blank=True, help_text='Customer service representative', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='csr_customers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_type',
            field=models.CharField(choices=[('DIRECT', 'Direct'), ('DISTRIBUTOR', 'Distributor'), ('BROKER', 'Broker'), ('OEM', 'OEM'), ('GOVERNMENT', 'Government'), ('OTHER', 'Other')], default='DIRECT', help_text='Customer classification', max_length=20),
        ),
        migrations.AddField(
            model_name='customer',
            name='invoice_delivery_method',
            field=models.CharField(choices=[('EMAIL', 'Email'), ('MAIL', 'Mail'), ('FAX', 'Fax'), ('PORTAL', 'Customer Portal')], default='EMAIL', help_text='Preferred method for sending invoices', max_length=10),
        ),
        migrations.AddField(
            model_name='customer',
            name='resale_number',
            field=models.CharField(blank=True, help_text='Resale certificate number (tax-exempt resellers)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='tax_code',
            field=models.CharField(blank=True, help_text='Tax code for this customer', max_length=50),
        ),
        migrations.AddField(
            model_name='party',
            name='main_email',
            field=models.EmailField(blank=True, help_text='Primary email address', max_length=254),
        ),
        migrations.AddField(
            model_name='party',
            name='main_phone',
            field=models.CharField(blank=True, help_text='Primary phone number', max_length=30),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['csr'], name='parties_cus_csr_id_f299d3_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['customer_type'], name='parties_cus_custome_7b5f1c_idx'),
        ),
    ]
