# Generated by Django 6.0 on 2026-02-20 19:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_accountingsettings_default_sales_tax_account'),
        ('parties', '0006_add_customer_fields'),
        ('tenants', '0003_onboarding_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='charge_freight',
            field=models.BooleanField(default=True, help_text='Whether this vendor charges freight on orders'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='credit_limit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Credit limit extended by this vendor', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='invoice_delivery_method',
            field=models.CharField(choices=[('EMAIL', 'Email'), ('MAIL', 'Mail'), ('FAX', 'Fax'), ('PORTAL', 'Vendor Portal')], default='EMAIL', help_text='Preferred method for receiving vendor invoices/bills', max_length=10),
        ),
        migrations.AddField(
            model_name='vendor',
            name='tax_code',
            field=models.CharField(blank=True, help_text='Tax code for this vendor', max_length=50),
        ),
        migrations.AddField(
            model_name='vendor',
            name='tax_id',
            field=models.CharField(blank=True, help_text='Vendor tax ID / EIN', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='vendor_type',
            field=models.CharField(choices=[('SUPPLIER', 'Supplier'), ('MANUFACTURER', 'Manufacturer'), ('DISTRIBUTOR', 'Distributor'), ('BROKER', 'Broker'), ('CONTRACTOR', 'Contractor'), ('OTHER', 'Other')], default='SUPPLIER', help_text='Vendor classification', max_length=20),
        ),
        migrations.AddIndex(
            model_name='vendor',
            index=models.Index(fields=['vendor_type'], name='parties_ven_vendor__65c998_idx'),
        ),
    ]
