# Generated by Django 6.0 on 2026-02-20 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0007_add_vendor_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_type',
            field=models.CharField(blank=True, choices=[('BEAUTY_HEALTH', 'Beauty/Health'), ('CLEANING_RESTORATION', 'Cleaning/Restoration'), ('DISTRIBUTOR', 'Distributor'), ('FOOD', 'Food'), ('FREIGHT', 'Freight'), ('GOVERNMENT', 'Government'), ('INDUSTRIAL', 'Industrial'), ('JANITORIAL', 'Janitorial'), ('MANUFACTURER', 'Manufacturer'), ('MEDICAL', 'Medical'), ('PHARMACEUTICAL', 'Pharmaceutical'), ('PIZZA', 'Pizza'), ('RETAIL', 'Retail'), ('TEXTILE', 'Textile'), ('WHOLESALE', 'Wholesale'), ('AUTOMOTIVE', 'Automotive'), ('CONSTRUCTION', 'Construction'), ('HOSPITALITY', 'Hospitality'), ('OTHER', 'Other')], help_text='Customer classification', max_length=30),
        ),
    ]
