# Generated by Django 6.0 on 2026-01-09 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Company name', max_length=255)),
                ('subdomain', models.CharField(help_text="Subdomain for accessing the system (e.g., 'acme' for acme.ravensaas.com)", max_length=63, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive tenants cannot log in')),
                ('is_default', models.BooleanField(default=False, help_text='Default tenant for development (only one should be default)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['subdomain'], name='tenants_ten_subdoma_6c6a7a_idx'), models.Index(fields=['is_active'], name='tenants_ten_is_acti_8f654a_idx')],
            },
        ),
        migrations.CreateModel(
            name='TenantSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, help_text='Full legal company name', max_length=255)),
                ('logo', models.ImageField(blank=True, help_text='Company logo', null=True, upload_to='tenant_logos/')),
                ('timezone', models.CharField(default='America/New_York', help_text='Default timezone for the tenant', max_length=50)),
                ('currency', models.CharField(default='USD', help_text='Currency code (ISO 4217)', max_length=3)),
                ('default_payment_terms', models.CharField(default='NET30', help_text='Default payment terms for new customers', max_length=50)),
                ('address_line1', models.CharField(blank=True, max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=50)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(default='USA', max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='TenantSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_type', models.CharField(choices=[('SO', 'Sales Order'), ('PO', 'Purchase Order'), ('INV', 'Invoice'), ('BOL', 'Bill of Lading'), ('CONTRACT', 'Contract')], help_text='Type of sequence (SO, PO, INV, etc.)', max_length=20)),
                ('prefix', models.CharField(help_text="Prefix for the number (e.g., 'SO-', 'PO-')", max_length=10)),
                ('next_value', models.PositiveIntegerField(default=1, help_text='Next number to use')),
                ('padding', models.PositiveIntegerField(default=6, help_text="Zero-pad to this width (e.g., 6 = '000001')")),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sequences', to='tenants.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'sequence_type'], name='tenants_ten_tenant__c93005_idx')],
                'unique_together': {('tenant', 'sequence_type')},
            },
        ),
    ]
