# Generated by Django 6.0 on 2026-02-06 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantsequence',
            name='sequence_type',
            field=models.CharField(choices=[('SO', 'Sales Order'), ('PO', 'Purchase Order'), ('INV', 'Invoice'), ('BOL', 'Bill of Lading'), ('CONTRACT', 'Contract'), ('JE', 'Journal Entry')], help_text='Type of sequence (SO, PO, INV, etc.)', max_length=20),
        ),
    ]
