# Generated by Django 6.0 on 2026-02-17 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_add_vendor_bills'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='company_address',
            field=models.TextField(blank=True, help_text='Full company address'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='company_logo',
            field=models.ImageField(blank=True, help_text='Company logo', null=True, upload_to='logos/'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='company_phone',
            field=models.CharField(blank=True, help_text='Main company phone number', max_length=20),
        ),
        migrations.AddField(
            model_name='tenant',
            name='industry',
            field=models.CharField(blank=True, choices=[('manufacturing', 'Manufacturing'), ('distribution', 'Distribution'), ('corrugated', 'Corrugated Packaging'), ('food_beverage', 'Food & Beverage'), ('other', 'Other')], help_text='Industry sector', max_length=50),
        ),
        migrations.AddField(
            model_name='tenant',
            name='onboarding_completed',
            field=models.BooleanField(default=False, help_text='Whether the tenant has completed onboarding'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='onboarding_step',
            field=models.PositiveSmallIntegerField(default=0, help_text='Current onboarding step (0=not started, 1-4=in progress, 5=complete)'),
        ),
    ]
