# Generated by Django 6.0 on 2026-03-13 19:27

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_onboarding_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantsettings',
            name='approval_po_amount_threshold',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('5000.00'), help_text='PO subtotal above this amount requires approval (null to disable)', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='approval_po_send_enabled',
            field=models.BooleanField(default=False, help_text='Require approval before sending PO to vendor'),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='approval_price_list_enabled',
            field=models.BooleanField(default=False, help_text='Require approval for new/updated customer price lists'),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='approval_so_margin_threshold',
            field=models.DecimalField(blank=True, decimal_places=4, default=Decimal('0.1500'), help_text='SO margin below this percentage requires approval (null to disable)', max_digits=5, null=True),
        ),
    ]
