# Generated by Django 6.0 on 2026-05-18 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_add_approval_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantsequence',
            name='sequence_type',
            field=models.CharField(choices=[('SO', 'Sales Order'), ('PO', 'Purchase Order'), ('INV', 'Invoice'), ('BOL', 'Bill of Lading'), ('CONTRACT', 'Contract'), ('JE', 'Journal Entry'), ('EST', 'Estimate'), ('RFQ', 'Request for Quotation'), ('FA', 'Fixed Asset')], help_text='Type of sequence (SO, PO, INV, etc.)', max_length=20),
        ),
    ]
