# Generated by Django 6.0 on 2026-06-23 20:16
#
# Adds the 'PT' (Pick Ticket) sequence type and backfills a TenantSequence row
# for every existing tenant — mirroring 0008_backfill_ir_sequence.py. Without
# the backfill, existing tenants would 500 the first time someone creates a
# pick because get_next_sequence_number('PT') would raise DoesNotExist.

from django.db import migrations, models


def backfill_pt(apps, schema_editor):
    Tenant = apps.get_model('tenants', 'Tenant')
    TenantSequence = apps.get_model('tenants', 'TenantSequence')

    for tenant in Tenant.objects.all():
        TenantSequence.objects.get_or_create(
            tenant=tenant,
            sequence_type='PT',
            defaults={'prefix': 'PT-', 'next_value': 1, 'padding': 6},
        )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0008_backfill_ir_sequence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantsequence',
            name='sequence_type',
            field=models.CharField(choices=[('SO', 'Sales Order'), ('PO', 'Purchase Order'), ('INV', 'Invoice'), ('BOL', 'Bill of Lading'), ('CONTRACT', 'Contract'), ('JE', 'Journal Entry'), ('EST', 'Estimate'), ('RFQ', 'Request for Quotation'), ('FA', 'Fixed Asset'), ('IR', 'Item Receipt'), ('PT', 'Pick Ticket')], help_text='Type of sequence (SO, PO, INV, etc.)', max_length=20),
        ),
        migrations.RunPython(backfill_pt, noop_reverse),
    ]
