# Generated by Django 6.0 on 2026-02-17 14:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('tenants', '0002_add_vendor_bills'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object_id', models.PositiveIntegerField(help_text='ID of the object requiring approval')),
                ('rule_code', models.CharField(help_text="Rule code (e.g., 'po_amount_threshold', 'so_low_margin', 'credit_limit_exceeded')", max_length=50)),
                ('rule_description', models.CharField(help_text='Human-readable reason for requiring approval', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', help_text='Current approval status', max_length=20)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, help_text='One-click email approval/rejection token', unique=True)),
                ('expires_at', models.DateTimeField(help_text='When this approval request expires (default 48h from creation)')),
                ('decided_at', models.DateTimeField(blank=True, help_text='When the approval/rejection decision was made', null=True)),
                ('decision_note', models.TextField(blank=True, help_text='Optional reason for the approval/rejection decision')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, help_text='Cached order amount for display in approval list', max_digits=12, null=True)),
                ('approver', models.ForeignKey(blank=True, help_text='User assigned to approve/reject', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_requests_assigned', to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(help_text='Type of the object requiring approval', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('requestor', models.ForeignKey(help_text='User who triggered the approval request', on_delete=django.db.models.deletion.CASCADE, related_name='approval_requests_created', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'status'], name='approvals_a_tenant__9a6dd2_idx'), models.Index(fields=['tenant', 'approver', 'status'], name='approvals_a_tenant__3564ab_idx'), models.Index(fields=['token'], name='approvals_a_token_b2f294_idx')],
            },
        ),
    ]
