# Generated by Django 6.0 on 2026-02-06 20:10

import django.db.models.deletion
import simple_history.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('new_scheduling', '0003_priority_list_models'),
        ('orders', '0006_add_is_pickup_to_baseorder'),
        ('parties', '0002_add_gl_accounts'),
        ('tenants', '0002_add_vendor_bills'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalDeliveryStop',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('sequence', models.PositiveIntegerField(default=1, help_text='Stop sequence (1=first stop, 2=second, etc.)')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ARRIVED', 'Arrived'), ('COMPLETED', 'Completed'), ('SKIPPED', 'Skipped')], default='PENDING', help_text='Current stop status', max_length=20)),
                ('signature_image', models.TextField(blank=True, help_text='Captured signature image', max_length=100, null=True)),
                ('signed_by', models.CharField(blank=True, help_text='Name of person who signed', max_length=100)),
                ('delivered_at', models.DateTimeField(blank=True, help_text='When delivery was completed', null=True)),
                ('delivery_notes', models.TextField(blank=True, help_text='Driver notes at delivery')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('customer', models.ForeignKey(blank=True, db_constraint=False, help_text='Customer being delivered to', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='parties.customer')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('run', models.ForeignKey(blank=True, db_constraint=False, help_text='Delivery run this stop belongs to', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='new_scheduling.deliveryrun')),
                ('ship_to', models.ForeignKey(blank=True, db_constraint=False, help_text='Delivery address', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='parties.location')),
                ('tenant', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'historical delivery stop',
                'verbose_name_plural': 'historical delivery stops',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalLicensePlate',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('code', models.CharField(help_text="License plate code (e.g., 'LPN-10001')", max_length=50)),
                ('weight_lbs', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Pallet weight in pounds', max_digits=10)),
                ('status', models.CharField(choices=[('STAGED', 'Staged'), ('LOADED', 'Loaded'), ('DELIVERED', 'Delivered')], default='STAGED', help_text='Current pallet status', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Pallet notes')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, db_constraint=False, help_text='Sales order this pallet belongs to', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='orders.salesorder')),
                ('run', models.ForeignKey(blank=True, db_constraint=False, help_text='Delivery run this pallet is loaded on', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='new_scheduling.deliveryrun')),
                ('tenant', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'historical license plate',
                'verbose_name_plural': 'historical license plates',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='DeliveryStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sequence', models.PositiveIntegerField(default=1, help_text='Stop sequence (1=first stop, 2=second, etc.)')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ARRIVED', 'Arrived'), ('COMPLETED', 'Completed'), ('SKIPPED', 'Skipped')], default='PENDING', help_text='Current stop status', max_length=20)),
                ('signature_image', models.ImageField(blank=True, help_text='Captured signature image', null=True, upload_to='logistics/signatures/')),
                ('signed_by', models.CharField(blank=True, help_text='Name of person who signed', max_length=100)),
                ('delivered_at', models.DateTimeField(blank=True, help_text='When delivery was completed', null=True)),
                ('delivery_notes', models.TextField(blank=True, help_text='Driver notes at delivery')),
                ('customer', models.ForeignKey(help_text='Customer being delivered to', on_delete=django.db.models.deletion.PROTECT, related_name='delivery_stops', to='parties.customer')),
                ('orders', models.ManyToManyField(blank=True, help_text='Sales orders being delivered at this stop', related_name='delivery_stops', to='orders.salesorder')),
                ('run', models.ForeignKey(help_text='Delivery run this stop belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='new_scheduling.deliveryrun')),
                ('ship_to', models.ForeignKey(blank=True, help_text='Delivery address', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='delivery_stops', to='parties.location')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'ordering': ['run', 'sequence'],
                'indexes': [models.Index(fields=['tenant', 'run', 'sequence'], name='logistics_d_tenant__25b1b4_idx'), models.Index(fields=['tenant', 'customer'], name='logistics_d_tenant__92ebd3_idx'), models.Index(fields=['tenant', 'status'], name='logistics_d_tenant__902d3f_idx')],
                'unique_together': {('tenant', 'run', 'customer')},
            },
        ),
        migrations.CreateModel(
            name='LicensePlate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text="License plate code (e.g., 'LPN-10001')", max_length=50)),
                ('weight_lbs', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Pallet weight in pounds', max_digits=10)),
                ('status', models.CharField(choices=[('STAGED', 'Staged'), ('LOADED', 'Loaded'), ('DELIVERED', 'Delivered')], default='STAGED', help_text='Current pallet status', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Pallet notes')),
                ('order', models.ForeignKey(help_text='Sales order this pallet belongs to', on_delete=django.db.models.deletion.PROTECT, related_name='license_plates', to='orders.salesorder')),
                ('run', models.ForeignKey(blank=True, help_text='Delivery run this pallet is loaded on', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='license_plates', to='new_scheduling.deliveryrun')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'code'], name='logistics_l_tenant__14d81d_idx'), models.Index(fields=['tenant', 'order'], name='logistics_l_tenant__94d2fb_idx'), models.Index(fields=['tenant', 'run'], name='logistics_l_tenant__a75eae_idx'), models.Index(fields=['tenant', 'status'], name='logistics_l_tenant__c67026_idx')],
                'unique_together': {('tenant', 'code')},
            },
        ),
    ]
