# Generated by Django 6.0 on 2026-02-16 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverystop',
            name='arrived_at',
            field=models.DateTimeField(blank=True, help_text='When driver arrived at this stop', null=True),
        ),
        migrations.AddField(
            model_name='deliverystop',
            name='gps_lat',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='GPS latitude at delivery', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='deliverystop',
            name='gps_lng',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='GPS longitude at delivery', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='deliverystop',
            name='photo_image',
            field=models.ImageField(blank=True, help_text='Photo proof of delivery (pallets on dock)', null=True, upload_to='logistics/pod_photos/'),
        ),
        migrations.AddField(
            model_name='historicaldeliverystop',
            name='arrived_at',
            field=models.DateTimeField(blank=True, help_text='When driver arrived at this stop', null=True),
        ),
        migrations.AddField(
            model_name='historicaldeliverystop',
            name='gps_lat',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='GPS latitude at delivery', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='historicaldeliverystop',
            name='gps_lng',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='GPS longitude at delivery', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='historicaldeliverystop',
            name='photo_image',
            field=models.TextField(blank=True, help_text='Photo proof of delivery (pallets on dock)', max_length=100, null=True),
        ),
    ]
