# Generated by Django 6.0 on 2026-02-06 20:44

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0001_initial'),
        ('invoicing', '0004_add_vendor_bills'),
        ('parties', '0002_add_gl_accounts'),
        ('tenants', '0002_add_vendor_bills'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_number', models.CharField(help_text="Auto-generated (e.g., 'CR-202602-00001')", max_length=30)),
                ('payment_date', models.DateField(default=django.utils.timezone.now, help_text='Date payment received')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Total check/payment amount', max_digits=12)),
                ('payment_method', models.CharField(choices=[('CHECK', 'Check'), ('ACH', 'ACH/Bank Transfer'), ('WIRE', 'Wire Transfer'), ('CREDIT_CARD', 'Credit Card'), ('CASH', 'Cash'), ('CREDIT_MEMO', 'Credit Memo'), ('OTHER', 'Other')], default='CHECK', help_text='Payment method', max_length=20)),
                ('reference_number', models.CharField(blank=True, help_text='Check number, transaction ID, etc.', max_length=100)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('void', 'Void')], default='draft', help_text='Payment status', max_length=20)),
                ('unapplied_amount', models.DecimalField(decimal_places=2, default=0, help_text='Amount not yet applied to invoices', max_digits=12)),
                ('notes', models.TextField(blank=True, help_text='Payment notes')),
                ('customer', models.ForeignKey(help_text='Customer making the payment', on_delete=django.db.models.deletion.PROTECT, related_name='customer_payments', to='parties.customer')),
                ('deposit_account', models.ForeignKey(blank=True, help_text='Bank/cash account to deposit into', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_payments_deposit', to='accounting.account')),
                ('journal_entry', models.OneToOneField(blank=True, help_text='Journal entry created when payment is posted', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_payment', to='accounting.journalentry')),
                ('recorded_by', models.ForeignKey(blank=True, help_text='User who recorded this payment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_customer_payments', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Customer Payment',
                'verbose_name_plural': 'Customer Payments',
                'ordering': ['-payment_date', '-payment_number'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalCustomerPayment',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('payment_number', models.CharField(help_text="Auto-generated (e.g., 'CR-202602-00001')", max_length=30)),
                ('payment_date', models.DateField(default=django.utils.timezone.now, help_text='Date payment received')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Total check/payment amount', max_digits=12)),
                ('payment_method', models.CharField(choices=[('CHECK', 'Check'), ('ACH', 'ACH/Bank Transfer'), ('WIRE', 'Wire Transfer'), ('CREDIT_CARD', 'Credit Card'), ('CASH', 'Cash'), ('CREDIT_MEMO', 'Credit Memo'), ('OTHER', 'Other')], default='CHECK', help_text='Payment method', max_length=20)),
                ('reference_number', models.CharField(blank=True, help_text='Check number, transaction ID, etc.', max_length=100)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('void', 'Void')], default='draft', help_text='Payment status', max_length=20)),
                ('unapplied_amount', models.DecimalField(decimal_places=2, default=0, help_text='Amount not yet applied to invoices', max_digits=12)),
                ('notes', models.TextField(blank=True, help_text='Payment notes')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('customer', models.ForeignKey(blank=True, db_constraint=False, help_text='Customer making the payment', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='parties.customer')),
                ('deposit_account', models.ForeignKey(blank=True, db_constraint=False, help_text='Bank/cash account to deposit into', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounting.account')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('journal_entry', models.ForeignKey(blank=True, db_constraint=False, help_text='Journal entry created when payment is posted', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounting.journalentry')),
                ('recorded_by', models.ForeignKey(blank=True, db_constraint=False, help_text='User who recorded this payment', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'historical Customer Payment',
                'verbose_name_plural': 'historical Customer Payments',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='PaymentApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_applied', models.DecimalField(decimal_places=2, help_text='Amount of this payment applied to this invoice', max_digits=12)),
                ('invoice', models.ForeignKey(help_text='Invoice receiving the payment', on_delete=django.db.models.deletion.PROTECT, related_name='payment_applications', to='invoicing.invoice')),
                ('payment', models.ForeignKey(help_text='Customer payment being applied', on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='payments.customerpayment')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Payment Application',
                'verbose_name_plural': 'Payment Applications',
            },
        ),
        migrations.AddIndex(
            model_name='customerpayment',
            index=models.Index(fields=['tenant', 'customer', 'payment_date'], name='payments_cu_tenant__3f2907_idx'),
        ),
        migrations.AddIndex(
            model_name='customerpayment',
            index=models.Index(fields=['tenant', 'status'], name='payments_cu_tenant__9a445d_idx'),
        ),
        migrations.AddIndex(
            model_name='customerpayment',
            index=models.Index(fields=['tenant', 'payment_date'], name='payments_cu_tenant__c6069b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='customerpayment',
            unique_together={('tenant', 'payment_number')},
        ),
        migrations.AddIndex(
            model_name='paymentapplication',
            index=models.Index(fields=['tenant', 'invoice'], name='payments_pa_tenant__384582_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentapplication',
            index=models.Index(fields=['tenant', 'payment'], name='payments_pa_tenant__753649_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='paymentapplication',
            unique_together={('payment', 'invoice')},
        ),
    ]
