# Generated by Django 6.0 on 2026-04-16 17:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_accountingsettings_default_sales_tax_account'),
        ('invoicing', '0005_historicalinvoice_dunning_count_and_more'),
        ('parties', '0008_update_customer_type_choices'),
        ('payments', '0001_initial'),
        ('tenants', '0004_add_approval_settings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Full name', max_length=200)),
                ('company_name', models.CharField(blank=True, help_text='Company/organization name', max_length=200)),
                ('print_name', models.CharField(help_text='Name to print on checks', max_length=200)),
                ('address_line1', models.CharField(blank=True, max_length=200)),
                ('address_line2', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=50)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(blank=True, default='US', max_length=50)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_1099', models.BooleanField(default=False, help_text='Subject to 1099 reporting')),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Other Name',
                'verbose_name_plural': 'Other Names',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('check_number', models.PositiveIntegerField(blank=True, help_text='Auto-assigned on print', null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('printed', 'Printed'), ('voided', 'Voided'), ('cleared', 'Cleared')], default='draft', max_length=20)),
                ('payee_name', models.CharField(help_text='Name printed on check', max_length=200)),
                ('payee_address', models.TextField(blank=True)),
                ('check_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('memo', models.CharField(blank=True, max_length=200)),
                ('printed_at', models.DateTimeField(blank=True, null=True)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('void_reason', models.CharField(blank=True, max_length=200)),
                ('bank_account', models.ForeignKey(help_text='Bank account to draw from', on_delete=django.db.models.deletion.PROTECT, related_name='checks', to='accounting.account')),
                ('bill_payment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='written_check', to='invoicing.billpayment')),
                ('journal_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='written_check', to='accounting.journalentry')),
                ('printed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='printed_checks', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checks', to='parties.vendor')),
                ('other_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checks', to='payments.othername')),
            ],
            options={
                'ordering': ['-check_date', '-check_number'],
            },
        ),
    ]
