# Generated by Django 6.0 on 2026-01-09 21:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lot_number', models.CharField(help_text='Lot identifier (auto-generated or manual)', max_length=50)),
                ('received_date', models.DateField(default=django.utils.timezone.now, help_text='Date lot was received')),
                ('unit_cost', models.DecimalField(decimal_places=4, help_text='Cost per base unit (EACH)', max_digits=12)),
                ('total_quantity', models.PositiveIntegerField(default=0, help_text='Total quantity received in base units (EACH)')),
                ('notes', models.TextField(blank=True, help_text='Notes about this lot')),
            ],
            options={
                'verbose_name': 'Inventory Lot',
                'verbose_name_plural': 'Inventory Lots',
            },
        ),
        migrations.CreateModel(
            name='InventoryPallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pallet_number', models.PositiveIntegerField(help_text='Pallet number within the lot')),
                ('license_plate', models.CharField(help_text='Unique scannable identifier (barcode)', max_length=64, unique=True)),
                ('quantity_received', models.PositiveIntegerField(help_text='Original quantity received (base units)')),
                ('quantity_on_hand', models.PositiveIntegerField(help_text='Current quantity on hand (base units)')),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('ALLOCATED', 'Allocated'), ('PICKING', 'Picking'), ('SHIPPED', 'Shipped'), ('DAMAGED', 'Damaged'), ('CONSUMED', 'Consumed')], default='AVAILABLE', help_text='Current pallet status', max_length=20)),
            ],
            options={
                'verbose_name': 'Inventory Pallet',
                'verbose_name_plural': 'Inventory Pallets',
                'ordering': ['lot', 'pallet_number'],
            },
        ),
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('RECEIPT', 'Receipt'), ('ISSUE', 'Issue'), ('ALLOCATE', 'Allocate'), ('DEALLOCATE', 'Deallocate'), ('ADJUST', 'Adjust'), ('TRANSFER_OUT', 'Transfer Out'), ('TRANSFER_IN', 'Transfer In')], help_text='Type of inventory movement', max_length=20)),
                ('quantity', models.IntegerField(help_text='Quantity changed (positive=increase, negative=decrease)')),
                ('transaction_date', models.DateTimeField(auto_now_add=True, help_text='When transaction occurred')),
                ('reference_type', models.CharField(blank=True, help_text='Type of reference document (PO, SO, ADJ)', max_length=50)),
                ('reference_id', models.PositiveIntegerField(blank=True, help_text='ID of reference document', null=True)),
                ('reference_number', models.CharField(blank=True, help_text="Human-readable reference (e.g., 'PO-000123')", max_length=100)),
                ('notes', models.TextField(blank=True, help_text='Transaction notes')),
                ('balance_on_hand', models.IntegerField(blank=True, help_text='Balance on_hand after this transaction', null=True)),
                ('balance_allocated', models.IntegerField(blank=True, help_text='Balance allocated after this transaction', null=True)),
            ],
            options={
                'verbose_name': 'Inventory Transaction',
                'verbose_name_plural': 'Inventory Transactions',
                'ordering': ['-transaction_date'],
            },
        ),
        migrations.CreateModel(
            name='InventoryBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on_hand', models.IntegerField(default=0, help_text='Total physical quantity in warehouse (base units)')),
                ('allocated', models.IntegerField(default=0, help_text='Quantity reserved for pending orders (base units)')),
                ('on_order', models.IntegerField(default=0, help_text='Quantity expected from pending POs (base units)')),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='Last time balance was updated')),
                ('item', models.ForeignKey(help_text='Item', on_delete=django.db.models.deletion.CASCADE, related_name='inventory_balances', to='items.item')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Inventory Balance',
                'verbose_name_plural': 'Inventory Balances',
            },
        ),
    ]
