# Generated by Django 6.0 on 2026-01-09 21:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('items', '0001_initial'),
        ('new_warehousing', '0001_initial'),
        ('orders', '0001_initial'),
        ('parties', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorybalance',
            name='warehouse',
            field=models.ForeignKey(help_text='Warehouse', on_delete=django.db.models.deletion.CASCADE, related_name='inventory_balances', to='new_warehousing.warehouse'),
        ),
        migrations.AddField(
            model_name='inventorylot',
            name='item',
            field=models.ForeignKey(help_text='Item in this lot', on_delete=django.db.models.deletion.PROTECT, related_name='inventory_lots', to='items.item'),
        ),
        migrations.AddField(
            model_name='inventorylot',
            name='purchase_order',
            field=models.ForeignKey(blank=True, help_text='PO this lot was received against', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_lots', to='orders.purchaseorder'),
        ),
        migrations.AddField(
            model_name='inventorylot',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='inventorylot',
            name='vendor',
            field=models.ForeignKey(blank=True, help_text='Vendor this lot was received from (null for transfers)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_lots', to='parties.vendor'),
        ),
        migrations.AddField(
            model_name='inventorylot',
            name='warehouse',
            field=models.ForeignKey(help_text='Warehouse where lot is stored', on_delete=django.db.models.deletion.PROTECT, related_name='inventory_lots', to='new_warehousing.warehouse'),
        ),
        migrations.AddField(
            model_name='inventorypallet',
            name='bin',
            field=models.ForeignKey(blank=True, help_text='Current bin location', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pallets', to='new_warehousing.bin'),
        ),
        migrations.AddField(
            model_name='inventorypallet',
            name='lot',
            field=models.ForeignKey(help_text='Lot this pallet belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='pallets', to='inventory.inventorylot'),
        ),
        migrations.AddField(
            model_name='inventorypallet',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='inventorytransaction',
            name='item',
            field=models.ForeignKey(help_text='Item affected', on_delete=django.db.models.deletion.PROTECT, related_name='inventory_transactions', to='items.item'),
        ),
        migrations.AddField(
            model_name='inventorytransaction',
            name='lot',
            field=models.ForeignKey(blank=True, help_text='Lot affected (if applicable)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='inventory.inventorylot'),
        ),
        migrations.AddField(
            model_name='inventorytransaction',
            name='pallet',
            field=models.ForeignKey(blank=True, help_text='Pallet affected (if applicable)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='inventory.inventorypallet'),
        ),
        migrations.AddField(
            model_name='inventorytransaction',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='inventorytransaction',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User who performed transaction', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventorytransaction',
            name='warehouse',
            field=models.ForeignKey(help_text='Warehouse affected', on_delete=django.db.models.deletion.PROTECT, related_name='inventory_transactions', to='new_warehousing.warehouse'),
        ),
        migrations.AddIndex(
            model_name='inventorybalance',
            index=models.Index(fields=['tenant', 'item', 'warehouse'], name='inventory_i_tenant__f487db_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorybalance',
            index=models.Index(fields=['tenant', 'warehouse'], name='inventory_i_tenant__d3d253_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='inventorybalance',
            unique_together={('tenant', 'item', 'warehouse')},
        ),
        migrations.AddIndex(
            model_name='inventorylot',
            index=models.Index(fields=['tenant', 'lot_number'], name='inventory_i_tenant__53d18c_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorylot',
            index=models.Index(fields=['tenant', 'item', 'warehouse'], name='inventory_i_tenant__b97453_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorylot',
            index=models.Index(fields=['tenant', 'received_date'], name='inventory_i_tenant__431a81_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='inventorylot',
            unique_together={('tenant', 'lot_number')},
        ),
        migrations.AddIndex(
            model_name='inventorypallet',
            index=models.Index(fields=['license_plate'], name='inventory_i_license_5fe788_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorypallet',
            index=models.Index(fields=['lot', 'pallet_number'], name='inventory_i_lot_id_20088a_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorypallet',
            index=models.Index(fields=['bin', 'status'], name='inventory_i_bin_id_c3ff29_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='inventorypallet',
            unique_together={('lot', 'pallet_number')},
        ),
        migrations.AddIndex(
            model_name='inventorytransaction',
            index=models.Index(fields=['tenant', 'item', 'warehouse', 'transaction_date'], name='inventory_i_tenant__c68c4f_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorytransaction',
            index=models.Index(fields=['tenant', 'transaction_date'], name='inventory_i_tenant__d4c36e_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorytransaction',
            index=models.Index(fields=['reference_type', 'reference_id'], name='inventory_i_referen_ace22e_idx'),
        ),
    ]
