# Generated by Django 6.0 on 2026-02-06 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('inventory', '0002_initial'),
        ('items', '0004_add_gl_accounts'),
        ('new_warehousing', '0001_initial'),
        ('tenants', '0002_add_vendor_bills'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity_original', models.DecimalField(decimal_places=4, help_text='Original quantity received in this layer', max_digits=12)),
                ('quantity_remaining', models.DecimalField(decimal_places=4, help_text='Quantity still available in this layer', max_digits=12)),
                ('unit_cost', models.DecimalField(decimal_places=4, help_text='Cost per unit at time of receipt', max_digits=12)),
                ('date_received', models.DateTimeField(help_text='When this layer was created (used for FIFO ordering)')),
                ('source_id', models.PositiveIntegerField(blank=True, null=True)),
                ('item', models.ForeignKey(help_text='Item this layer belongs to', on_delete=django.db.models.deletion.PROTECT, related_name='cost_layers', to='items.item')),
                ('lot', models.ForeignKey(blank=True, help_text='Physical lot this layer corresponds to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cost_layers', to='inventory.inventorylot')),
                ('source_type', models.ForeignKey(blank=True, help_text='Type of source document', null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
                ('warehouse', models.ForeignKey(help_text='Warehouse where this layer is held', on_delete=django.db.models.deletion.PROTECT, related_name='cost_layers', to='new_warehousing.warehouse')),
            ],
            options={
                'verbose_name': 'Inventory Layer',
                'verbose_name_plural': 'Inventory Layers',
                'ordering': ['date_received'],
                'indexes': [models.Index(fields=['tenant', 'item', 'warehouse', 'date_received'], name='inv_layer_fifo_idx'), models.Index(fields=['tenant', 'item', 'quantity_remaining'], name='inv_layer_remaining_idx'), models.Index(fields=['source_type', 'source_id'], name='inventory_i_source__e40113_idx')],
            },
        ),
    ]
