# Generated by Django 6.0 on 2026-02-16 15:11

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_add_fifo_cost_layers'),
        ('items', '0005_add_parent_field'),
        ('new_warehousing', '0002_lot_warehouselocation_stockquant_stockmovelog_and_more'),
        ('tenants', '0002_add_vendor_bills'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalInventoryBalance',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('on_hand', models.IntegerField(default=0, help_text='Total physical quantity in warehouse (base units)')),
                ('allocated', models.IntegerField(default=0, help_text='Quantity reserved for pending orders (base units)')),
                ('on_order', models.IntegerField(default=0, help_text='Quantity expected from pending POs (base units)')),
                ('last_updated', models.DateTimeField(blank=True, editable=False, help_text='Last time balance was updated')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(blank=True, db_constraint=False, help_text='Item', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='items.item')),
                ('tenant', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tenants.tenant')),
                ('warehouse', models.ForeignKey(blank=True, db_constraint=False, help_text='Warehouse', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='new_warehousing.warehouse')),
            ],
            options={
                'verbose_name': 'historical Inventory Balance',
                'verbose_name_plural': 'historical Inventory Balances',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
