# Generated by Django 6.0 on 2026-05-22 15:52

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_accountingsettings_default_grir_account'),
        ('inventory', '0004_historicalinventorybalance'),
        ('items', '0016_historicalitem_extra_info_lines_and_more'),
        ('orders', '0011_add_fulfillment_method'),
        ('parties', '0008_update_customer_type_choices'),
        ('tenants', '0007_alter_tenantsequence_sequence_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalItemReceipt',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('receipt_number', models.CharField(help_text='Receipt number (unique per tenant). Generated via TenantSequence.', max_length=50)),
                ('received_date', models.DateField(default=django.utils.timezone.now, help_text='Date goods were physically received')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('partially_billed', 'Partially Billed'), ('billed', 'Billed'), ('void', 'Void')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('journal_entry', models.ForeignKey(blank=True, db_constraint=False, help_text='GR/IR accrual JE created when receipt is posted', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounting.journalentry')),
                ('purchase_order', models.ForeignKey(blank=True, db_constraint=False, help_text='Originating PO (optional — direct receipts without a PO are allowed)', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='orders.purchaseorder')),
                ('received_by', models.ForeignKey(blank=True, db_constraint=False, help_text='User who recorded the receipt', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tenants.tenant')),
                ('vendor', models.ForeignKey(blank=True, db_constraint=False, help_text='Vendor who supplied the goods', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='parties.vendor')),
                ('warehouse', models.ForeignKey(blank=True, db_constraint=False, help_text='Warehouse that received the goods', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='parties.location')),
            ],
            options={
                'verbose_name': 'historical Item Receipt',
                'verbose_name_plural': 'historical Item Receipts',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ItemReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('receipt_number', models.CharField(help_text='Receipt number (unique per tenant). Generated via TenantSequence.', max_length=50)),
                ('received_date', models.DateField(default=django.utils.timezone.now, help_text='Date goods were physically received')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('partially_billed', 'Partially Billed'), ('billed', 'Billed'), ('void', 'Void')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('journal_entry', models.ForeignKey(blank=True, help_text='GR/IR accrual JE created when receipt is posted', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_receipts', to='accounting.journalentry')),
                ('purchase_order', models.ForeignKey(blank=True, help_text='Originating PO (optional — direct receipts without a PO are allowed)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='item_receipts', to='orders.purchaseorder')),
                ('received_by', models.ForeignKey(blank=True, help_text='User who recorded the receipt', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='received_item_receipts', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
                ('vendor', models.ForeignKey(help_text='Vendor who supplied the goods', on_delete=django.db.models.deletion.PROTECT, related_name='item_receipts', to='parties.vendor')),
                ('warehouse', models.ForeignKey(help_text='Warehouse that received the goods', on_delete=django.db.models.deletion.PROTECT, related_name='item_receipts', to='parties.location')),
            ],
            options={
                'verbose_name': 'Item Receipt',
                'verbose_name_plural': 'Item Receipts',
                'ordering': ['-received_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ItemReceiptLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('line_number', models.PositiveIntegerField(help_text='Line sequence (10, 20, 30...)')),
                ('quantity', models.PositiveIntegerField(help_text='Quantity received (base units)')),
                ('unit_cost', models.DecimalField(decimal_places=4, help_text='Cost per unit at time of receipt', max_digits=10)),
                ('quantity_billed', models.PositiveIntegerField(default=0, help_text='Quantity already rolled into vendor bills')),
                ('notes', models.TextField(blank=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipt_lines', to='items.item')),
                ('purchase_order_line', models.ForeignKey(blank=True, help_text='Source PO line (null for direct receipts not against a PO)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipt_lines', to='orders.purchaseorderline')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.itemreceipt')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Item Receipt Line',
                'verbose_name_plural': 'Item Receipt Lines',
                'ordering': ['receipt', 'line_number'],
            },
        ),
        migrations.AddIndex(
            model_name='itemreceipt',
            index=models.Index(fields=['tenant', 'receipt_number'], name='inventory_i_tenant__bbe39e_idx'),
        ),
        migrations.AddIndex(
            model_name='itemreceipt',
            index=models.Index(fields=['tenant', 'vendor', 'received_date'], name='inventory_i_tenant__5d5248_idx'),
        ),
        migrations.AddIndex(
            model_name='itemreceipt',
            index=models.Index(fields=['tenant', 'status'], name='inventory_i_tenant__257106_idx'),
        ),
        migrations.AddIndex(
            model_name='itemreceipt',
            index=models.Index(fields=['tenant', 'purchase_order'], name='inventory_i_tenant__353469_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='itemreceipt',
            unique_together={('tenant', 'receipt_number')},
        ),
        migrations.AddIndex(
            model_name='itemreceiptline',
            index=models.Index(fields=['tenant', 'receipt'], name='inventory_i_tenant__316302_idx'),
        ),
        migrations.AddIndex(
            model_name='itemreceiptline',
            index=models.Index(fields=['tenant', 'purchase_order_line'], name='inventory_i_tenant__f9e742_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='itemreceiptline',
            unique_together={('receipt', 'line_number')},
        ),
    ]
