# Generated by Django 6.0 on 2026-05-22 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_historicalitemreceipt_itemreceipt_itemreceiptline_and_more'),
        ('new_warehousing', '0005_warehouse_pallet_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalitemreceipt',
            name='warehouse',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Warehouse that received the goods', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='new_warehousing.warehouse'),
        ),
        migrations.AlterField(
            model_name='itemreceipt',
            name='warehouse',
            field=models.ForeignKey(help_text='Warehouse that received the goods', on_delete=django.db.models.deletion.PROTECT, related_name='item_receipts', to='new_warehousing.warehouse'),
        ),
    ]
