# Generated by Django 6.0 on 2026-06-23 20:16

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_historicalitemreceipt_warehouse_and_more'),
        ('items', '0016_historicalitem_extra_info_lines_and_more'),
        ('new_warehousing', '0006_bin_height_bin_length_bin_max_capacity_bin_width'),
        ('orders', '0012_salesorderline_quantity_invoiced'),
        ('parties', '0009_widen_phone_fields'),
        ('tenants', '0009_alter_tenantsequence_sequence_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPickTicket',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('pick_number', models.CharField(help_text='Pick ticket number (unique per tenant). Generated via TenantSequence.', max_length=50)),
                ('picked_date', models.DateField(default=django.utils.timezone.now, help_text='Date goods were physically picked')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('partially_invoiced', 'Partially Invoiced'), ('invoiced', 'Invoiced'), ('void', 'Void')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('customer', models.ForeignKey(blank=True, db_constraint=False, help_text='Customer the goods are picked for', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='parties.customer')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('picked_by', models.ForeignKey(blank=True, db_constraint=False, help_text='User who recorded the pick', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('sales_order', models.ForeignKey(blank=True, db_constraint=False, help_text='Originating SO (optional — direct picks without an SO are allowed)', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='orders.salesorder')),
                ('tenant', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tenants.tenant')),
                ('warehouse', models.ForeignKey(blank=True, db_constraint=False, help_text='Warehouse the goods were picked from', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='new_warehousing.warehouse')),
            ],
            options={
                'verbose_name': 'historical Pick Ticket',
                'verbose_name_plural': 'historical Pick Tickets',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='PickTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pick_number', models.CharField(help_text='Pick ticket number (unique per tenant). Generated via TenantSequence.', max_length=50)),
                ('picked_date', models.DateField(default=django.utils.timezone.now, help_text='Date goods were physically picked')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('partially_invoiced', 'Partially Invoiced'), ('invoiced', 'Invoiced'), ('void', 'Void')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('customer', models.ForeignKey(help_text='Customer the goods are picked for', on_delete=django.db.models.deletion.PROTECT, related_name='pick_tickets', to='parties.customer')),
                ('picked_by', models.ForeignKey(blank=True, help_text='User who recorded the pick', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='picked_pick_tickets', to=settings.AUTH_USER_MODEL)),
                ('sales_order', models.ForeignKey(blank=True, help_text='Originating SO (optional — direct picks without an SO are allowed)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pick_tickets', to='orders.salesorder')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
                ('warehouse', models.ForeignKey(help_text='Warehouse the goods were picked from', on_delete=django.db.models.deletion.PROTECT, related_name='pick_tickets', to='new_warehousing.warehouse')),
            ],
            options={
                'verbose_name': 'Pick Ticket',
                'verbose_name_plural': 'Pick Tickets',
                'ordering': ['-picked_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PickTicketLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('line_number', models.PositiveIntegerField(help_text='Line sequence (10, 20, 30...)')),
                ('quantity', models.PositiveIntegerField(help_text='Quantity picked (base units)')),
                ('unit_price', models.DecimalField(decimal_places=4, help_text='Price per unit (for subtotal display; sourced from SO line or item)', max_digits=10)),
                ('quantity_invoiced', models.PositiveIntegerField(default=0, help_text='Quantity already rolled into invoices')),
                ('notes', models.TextField(blank=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pick_lines', to='items.item')),
                ('pick_ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.pickticket')),
                ('sales_order_line', models.ForeignKey(blank=True, help_text='Source SO line (null for direct picks not against an SO)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pick_lines', to='orders.salesorderline')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Pick Ticket Line',
                'verbose_name_plural': 'Pick Ticket Lines',
                'ordering': ['pick_ticket', 'line_number'],
            },
        ),
        migrations.AddIndex(
            model_name='pickticket',
            index=models.Index(fields=['tenant', 'pick_number'], name='inventory_p_tenant__ebd33f_idx'),
        ),
        migrations.AddIndex(
            model_name='pickticket',
            index=models.Index(fields=['tenant', 'customer', 'picked_date'], name='inventory_p_tenant__9d14c8_idx'),
        ),
        migrations.AddIndex(
            model_name='pickticket',
            index=models.Index(fields=['tenant', 'status'], name='inventory_p_tenant__9df16a_idx'),
        ),
        migrations.AddIndex(
            model_name='pickticket',
            index=models.Index(fields=['tenant', 'sales_order'], name='inventory_p_tenant__31a4a7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pickticket',
            unique_together={('tenant', 'pick_number')},
        ),
        migrations.AddIndex(
            model_name='pickticketline',
            index=models.Index(fields=['tenant', 'pick_ticket'], name='inventory_p_tenant__1710a1_idx'),
        ),
        migrations.AddIndex(
            model_name='pickticketline',
            index=models.Index(fields=['tenant', 'sales_order_line'], name='inventory_p_tenant__d6513f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pickticketline',
            unique_together={('pick_ticket', 'line_number')},
        ),
    ]
