# Generated by Django 6.0 on 2026-01-12 20:35

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('parties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice_number', models.CharField(help_text='Invoice number (unique per tenant)', max_length=50)),
                ('invoice_date', models.DateField(default=django.utils.timezone.now, help_text='Date invoice was created')),
                ('due_date', models.DateField(help_text='Payment due date')),
                ('payment_terms', models.CharField(choices=[('NET30', 'Net 30'), ('NET15', 'Net 15'), ('NET45', 'Net 45'), ('NET60', 'Net 60'), ('DUE_ON_RECEIPT', 'Due on Receipt'), ('COD', 'Cash on Delivery')], default='NET30', help_text='Payment terms', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('paid', 'Paid'), ('partial', 'Partially Paid'), ('overdue', 'Overdue'), ('void', 'Void'), ('written_off', 'Written Off')], default='draft', help_text='Invoice status', max_length=20)),
                ('bill_to_name', models.CharField(help_text='Billing name', max_length=200)),
                ('bill_to_address', models.TextField(blank=True, help_text='Billing address')),
                ('ship_to_name', models.CharField(blank=True, help_text='Ship-to name', max_length=200)),
                ('ship_to_address', models.TextField(blank=True, help_text='Ship-to address')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, help_text='Sum of line totals', max_digits=12)),
                ('tax_rate', models.DecimalField(decimal_places=4, default=0, help_text='Tax rate (e.g., 0.08 for 8%)', max_digits=5)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, help_text='Calculated tax amount', max_digits=12)),
                ('freight_amount', models.DecimalField(decimal_places=2, default=0, help_text='Freight/shipping charges', max_digits=12)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, help_text='Discount amount', max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, help_text='Total invoice amount', max_digits=12)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, help_text='Amount paid to date', max_digits=12)),
                ('customer_po', models.CharField(blank=True, help_text="Customer's PO reference number", max_length=50)),
                ('notes', models.TextField(blank=True, help_text='Invoice notes (internal)')),
                ('customer_notes', models.TextField(blank=True, help_text='Notes to appear on invoice')),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
            },
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_number', models.PositiveIntegerField(help_text='Line sequence (10, 20, 30...)')),
                ('description', models.CharField(help_text='Line description', max_length=255)),
                ('quantity', models.PositiveIntegerField(help_text='Quantity billed')),
                ('unit_price', models.DecimalField(decimal_places=4, help_text='Price per unit', max_digits=12)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, help_text='Line discount percentage', max_digits=5)),
                ('line_total', models.DecimalField(decimal_places=2, default=0, help_text='Line total (calculated)', max_digits=12)),
            ],
            options={
                'verbose_name': 'Invoice Line',
                'verbose_name_plural': 'Invoice Lines',
                'ordering': ['line_number'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_date', models.DateField(default=django.utils.timezone.now, help_text='Date payment received')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Payment amount', max_digits=12)),
                ('payment_method', models.CharField(choices=[('CHECK', 'Check'), ('ACH', 'ACH/Bank Transfer'), ('WIRE', 'Wire Transfer'), ('CREDIT_CARD', 'Credit Card'), ('CASH', 'Cash'), ('CREDIT_MEMO', 'Credit Memo'), ('OTHER', 'Other')], default='CHECK', help_text='Payment method', max_length=20)),
                ('reference_number', models.CharField(blank=True, help_text='Check number, transaction ID, etc.', max_length=100)),
                ('notes', models.TextField(blank=True, help_text='Payment notes')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalInvoice',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('invoice_number', models.CharField(help_text='Invoice number (unique per tenant)', max_length=50)),
                ('invoice_date', models.DateField(default=django.utils.timezone.now, help_text='Date invoice was created')),
                ('due_date', models.DateField(help_text='Payment due date')),
                ('payment_terms', models.CharField(choices=[('NET30', 'Net 30'), ('NET15', 'Net 15'), ('NET45', 'Net 45'), ('NET60', 'Net 60'), ('DUE_ON_RECEIPT', 'Due on Receipt'), ('COD', 'Cash on Delivery')], default='NET30', help_text='Payment terms', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('paid', 'Paid'), ('partial', 'Partially Paid'), ('overdue', 'Overdue'), ('void', 'Void'), ('written_off', 'Written Off')], default='draft', help_text='Invoice status', max_length=20)),
                ('bill_to_name', models.CharField(help_text='Billing name', max_length=200)),
                ('bill_to_address', models.TextField(blank=True, help_text='Billing address')),
                ('ship_to_name', models.CharField(blank=True, help_text='Ship-to name', max_length=200)),
                ('ship_to_address', models.TextField(blank=True, help_text='Ship-to address')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, help_text='Sum of line totals', max_digits=12)),
                ('tax_rate', models.DecimalField(decimal_places=4, default=0, help_text='Tax rate (e.g., 0.08 for 8%)', max_digits=5)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, help_text='Calculated tax amount', max_digits=12)),
                ('freight_amount', models.DecimalField(decimal_places=2, default=0, help_text='Freight/shipping charges', max_digits=12)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, help_text='Discount amount', max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, help_text='Total invoice amount', max_digits=12)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, help_text='Amount paid to date', max_digits=12)),
                ('customer_po', models.CharField(blank=True, help_text="Customer's PO reference number", max_length=50)),
                ('notes', models.TextField(blank=True, help_text='Invoice notes (internal)')),
                ('customer_notes', models.TextField(blank=True, help_text='Notes to appear on invoice')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('customer', models.ForeignKey(blank=True, db_constraint=False, help_text='Customer being billed', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='parties.customer')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('sales_order', models.ForeignKey(blank=True, db_constraint=False, help_text='Sales order this invoice is for (optional)', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='orders.salesorder')),
            ],
            options={
                'verbose_name': 'historical Invoice',
                'verbose_name_plural': 'historical Invoices',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
