# Generated by Django 6.0 on 2026-01-12 20:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invoicing', '0001_initial'),
        ('items', '0001_initial'),
        ('orders', '0001_initial'),
        ('parties', '0001_initial'),
        ('shipping', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinvoice',
            name='shipment',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Shipment this invoice is for (optional)', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='shipping.shipment'),
        ),
        migrations.AddField(
            model_name='historicalinvoice',
            name='tenant',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='customer',
            field=models.ForeignKey(help_text='Customer being billed', on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='parties.customer'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='sales_order',
            field=models.ForeignKey(blank=True, help_text='Sales order this invoice is for (optional)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='orders.salesorder'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='shipment',
            field=models.ForeignKey(blank=True, help_text='Shipment this invoice is for (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='shipping.shipment'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='invoice',
            field=models.ForeignKey(help_text='Parent invoice', on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='invoicing.invoice'),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='item',
            field=models.ForeignKey(help_text='Item being billed', on_delete=django.db.models.deletion.PROTECT, related_name='invoice_lines', to='items.item'),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='sales_order_line',
            field=models.ForeignKey(blank=True, help_text='Source sales order line', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_lines', to='orders.salesorderline'),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='uom',
            field=models.ForeignKey(help_text='Unit of measure', on_delete=django.db.models.deletion.PROTECT, related_name='invoice_lines', to='items.unitofmeasure'),
        ),
        migrations.AddField(
            model_name='payment',
            name='invoice',
            field=models.ForeignKey(help_text='Invoice being paid', on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='invoicing.invoice'),
        ),
        migrations.AddField(
            model_name='payment',
            name='recorded_by',
            field=models.ForeignKey(blank=True, help_text='User who recorded this payment', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recorded_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['tenant', 'invoice_number'], name='invoicing_i_tenant__e88abd_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['tenant', 'customer', 'invoice_date'], name='invoicing_i_tenant__a968ca_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['tenant', 'status'], name='invoicing_i_tenant__7d1a63_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['tenant', 'due_date'], name='invoicing_i_tenant__6858ef_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='invoice',
            unique_together={('tenant', 'invoice_number')},
        ),
        migrations.AddIndex(
            model_name='invoiceline',
            index=models.Index(fields=['invoice', 'line_number'], name='invoicing_i_invoice_7437c9_idx'),
        ),
        migrations.AddIndex(
            model_name='invoiceline',
            index=models.Index(fields=['item'], name='invoicing_i_item_id_acc319_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='invoiceline',
            unique_together={('invoice', 'line_number')},
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['tenant', 'invoice'], name='invoicing_p_tenant__1dac4b_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['tenant', 'payment_date'], name='invoicing_p_tenant__a7cb26_idx'),
        ),
    ]
