# Generated by Django 6.0 on 2026-02-06 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
        ('invoicing', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinvoice',
            name='ar_account',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='A/R account for this invoice (falls back to customer/tenant default)', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='historicalinvoice',
            name='journal_entry',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Journal entry created when invoice is posted', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounting.journalentry'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='ar_account',
            field=models.ForeignKey(blank=True, help_text='A/R account for this invoice (falls back to customer/tenant default)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices_ar', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='journal_entry',
            field=models.OneToOneField(blank=True, help_text='Journal entry created when invoice is posted', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice', to='accounting.journalentry'),
        ),
        migrations.AlterField(
            model_name='historicalinvoice',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('sent', 'Sent'), ('paid', 'Paid'), ('partial', 'Partially Paid'), ('overdue', 'Overdue'), ('void', 'Void'), ('written_off', 'Written Off')], default='draft', help_text='Invoice status', max_length=20),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('sent', 'Sent'), ('paid', 'Paid'), ('partial', 'Partially Paid'), ('overdue', 'Overdue'), ('void', 'Void'), ('written_off', 'Written Off')], default='draft', help_text='Invoice status', max_length=20),
        ),
    ]
