# Generated by Django 6.0 on 2026-02-06 13:44

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
        ('invoicing', '0003_add_gl_integration'),
        ('items', '0004_add_gl_accounts'),
        ('orders', '0003_add_scheduler_sequence'),
        ('parties', '0002_add_gl_accounts'),
        ('tenants', '0002_add_vendor_bills'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalVendorBill',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('vendor_invoice_number', models.CharField(help_text="Vendor's invoice/reference number", max_length=100)),
                ('bill_number', models.CharField(help_text='Internal bill number (unique per tenant)', max_length=50)),
                ('bill_date', models.DateField(default=django.utils.timezone.now, help_text='Date bill was received')),
                ('due_date', models.DateField(help_text='Payment due date')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('paid', 'Paid'), ('partial', 'Partially Paid'), ('void', 'Void')], default='draft', help_text='Bill status', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, help_text='Sum of line totals', max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, help_text='Tax amount', max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, help_text='Total bill amount', max_digits=12)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, help_text='Amount paid to date', max_digits=12)),
                ('notes', models.TextField(blank=True, help_text='Internal notes')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('ap_account', models.ForeignKey(blank=True, db_constraint=False, help_text='A/P account for this bill (falls back to vendor/tenant default)', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounting.account')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('journal_entry', models.ForeignKey(blank=True, db_constraint=False, help_text='Journal entry created when bill is posted', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounting.journalentry')),
                ('purchase_order', models.ForeignKey(blank=True, db_constraint=False, help_text='Purchase order this bill is for (optional)', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='orders.purchaseorder')),
                ('tenant', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tenants.tenant')),
                ('vendor', models.ForeignKey(blank=True, db_constraint=False, help_text='Vendor who sent this bill', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='parties.vendor')),
            ],
            options={
                'verbose_name': 'historical Vendor Bill',
                'verbose_name_plural': 'historical Vendor Bills',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='VendorBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendor_invoice_number', models.CharField(help_text="Vendor's invoice/reference number", max_length=100)),
                ('bill_number', models.CharField(help_text='Internal bill number (unique per tenant)', max_length=50)),
                ('bill_date', models.DateField(default=django.utils.timezone.now, help_text='Date bill was received')),
                ('due_date', models.DateField(help_text='Payment due date')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('paid', 'Paid'), ('partial', 'Partially Paid'), ('void', 'Void')], default='draft', help_text='Bill status', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, help_text='Sum of line totals', max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, help_text='Tax amount', max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, help_text='Total bill amount', max_digits=12)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, help_text='Amount paid to date', max_digits=12)),
                ('notes', models.TextField(blank=True, help_text='Internal notes')),
                ('ap_account', models.ForeignKey(blank=True, help_text='A/P account for this bill (falls back to vendor/tenant default)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bills_ap', to='accounting.account')),
                ('journal_entry', models.OneToOneField(blank=True, help_text='Journal entry created when bill is posted', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_bill', to='accounting.journalentry')),
                ('purchase_order', models.ForeignKey(blank=True, help_text='Purchase order this bill is for (optional)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bills', to='orders.purchaseorder')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
                ('vendor', models.ForeignKey(help_text='Vendor who sent this bill', on_delete=django.db.models.deletion.PROTECT, related_name='bills', to='parties.vendor')),
            ],
            options={
                'verbose_name': 'Vendor Bill',
                'verbose_name_plural': 'Vendor Bills',
            },
        ),
        migrations.CreateModel(
            name='BillPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_date', models.DateField(default=django.utils.timezone.now, help_text='Date payment was made')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Payment amount', max_digits=12)),
                ('payment_method', models.CharField(choices=[('CHECK', 'Check'), ('ACH', 'ACH/Bank Transfer'), ('WIRE', 'Wire Transfer'), ('CREDIT_CARD', 'Credit Card'), ('CASH', 'Cash'), ('DEBIT_MEMO', 'Debit Memo'), ('OTHER', 'Other')], default='CHECK', help_text='Payment method', max_length=20)),
                ('reference_number', models.CharField(blank=True, help_text='Check number, transaction ID, etc.', max_length=100)),
                ('notes', models.TextField(blank=True, help_text='Payment notes')),
                ('recorded_by', models.ForeignKey(blank=True, help_text='User who recorded this payment', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recorded_bill_payments', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
                ('bill', models.ForeignKey(help_text='Vendor bill being paid', on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='invoicing.vendorbill')),
            ],
            options={
                'verbose_name': 'Bill Payment',
                'verbose_name_plural': 'Bill Payments',
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='VendorBillLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_number', models.PositiveIntegerField(help_text='Line sequence (10, 20, 30...)')),
                ('description', models.CharField(help_text='Line description', max_length=255)),
                ('quantity', models.DecimalField(decimal_places=4, default=1, help_text='Quantity', max_digits=12)),
                ('unit_price', models.DecimalField(decimal_places=4, help_text='Price per unit', max_digits=12)),
                ('amount', models.DecimalField(decimal_places=2, default=0, help_text='Line total (calculated)', max_digits=12)),
                ('bill', models.ForeignKey(help_text='Parent vendor bill', on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='invoicing.vendorbill')),
                ('expense_account', models.ForeignKey(blank=True, help_text='Expense/asset account to debit (resolved via fallback if blank)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bill_lines_expense', to='accounting.account')),
                ('item', models.ForeignKey(blank=True, help_text='Item being billed (optional for non-inventory charges)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bill_lines', to='items.item')),
                ('purchase_order_line', models.ForeignKey(blank=True, help_text='Source purchase order line', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bill_lines', to='orders.purchaseorderline')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Vendor Bill Line',
                'verbose_name_plural': 'Vendor Bill Lines',
                'ordering': ['line_number'],
            },
        ),
        migrations.AddIndex(
            model_name='vendorbill',
            index=models.Index(fields=['tenant', 'bill_number'], name='invoicing_v_tenant__7124f2_idx'),
        ),
        migrations.AddIndex(
            model_name='vendorbill',
            index=models.Index(fields=['tenant', 'vendor', 'bill_date'], name='invoicing_v_tenant__9fe42c_idx'),
        ),
        migrations.AddIndex(
            model_name='vendorbill',
            index=models.Index(fields=['tenant', 'status'], name='invoicing_v_tenant__da6146_idx'),
        ),
        migrations.AddIndex(
            model_name='vendorbill',
            index=models.Index(fields=['tenant', 'due_date'], name='invoicing_v_tenant__4e4198_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='vendorbill',
            unique_together={('tenant', 'bill_number')},
        ),
        migrations.AddIndex(
            model_name='billpayment',
            index=models.Index(fields=['tenant', 'bill'], name='invoicing_b_tenant__66c2e7_idx'),
        ),
        migrations.AddIndex(
            model_name='billpayment',
            index=models.Index(fields=['tenant', 'payment_date'], name='invoicing_b_tenant__5a029d_idx'),
        ),
        migrations.AddIndex(
            model_name='vendorbillline',
            index=models.Index(fields=['bill', 'line_number'], name='invoicing_v_bill_id_496d1e_idx'),
        ),
        migrations.AddIndex(
            model_name='vendorbillline',
            index=models.Index(fields=['item'], name='invoicing_v_item_id_1ef64a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='vendorbillline',
            unique_together={('bill', 'line_number')},
        ),
    ]
