# Generated by Django 6.0 on 2026-02-16 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
        ('invoicing', '0004_add_vendor_bills'),
        ('tenants', '0002_add_vendor_bills'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinvoice',
            name='dunning_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of dunning notices sent'),
        ),
        migrations.AddField(
            model_name='historicalinvoice',
            name='dunning_status',
            field=models.CharField(choices=[('none', 'None'), ('first_notice', 'First Notice'), ('second_notice', 'Second Notice'), ('final_notice', 'Final Notice'), ('collections', 'Collections')], default='none', help_text='Current dunning escalation level', max_length=20),
        ),
        migrations.AddField(
            model_name='historicalinvoice',
            name='last_dunning_date',
            field=models.DateTimeField(blank=True, help_text='When the last dunning notice was sent', null=True),
        ),
        migrations.AddField(
            model_name='historicalinvoice',
            name='ship_to_postal_code',
            field=models.CharField(blank=True, help_text='Ship-to postal/zip code (used for tax zone lookup)', max_length=20),
        ),
        migrations.AddField(
            model_name='invoice',
            name='dunning_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of dunning notices sent'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='dunning_status',
            field=models.CharField(choices=[('none', 'None'), ('first_notice', 'First Notice'), ('second_notice', 'Second Notice'), ('final_notice', 'Final Notice'), ('collections', 'Collections')], default='none', help_text='Current dunning escalation level', max_length=20),
        ),
        migrations.AddField(
            model_name='invoice',
            name='last_dunning_date',
            field=models.DateTimeField(blank=True, help_text='When the last dunning notice was sent', null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='ship_to_postal_code',
            field=models.CharField(blank=True, help_text='Ship-to postal/zip code (used for tax zone lookup)', max_length=20),
        ),
        migrations.CreateModel(
            name='TaxZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text="Zone name (e.g., 'Cook County IL', 'CA State')", max_length=100)),
                ('rate', models.DecimalField(decimal_places=4, help_text='Tax rate as decimal (e.g., 0.0825 for 8.25%)', max_digits=6)),
                ('is_active', models.BooleanField(default=True)),
                ('gl_account', models.ForeignKey(blank=True, help_text='GL liability account for collected tax', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tax_zones', to='accounting.account')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Tax Zone',
                'verbose_name_plural': 'Tax Zones',
            },
        ),
        migrations.CreateModel(
            name='TaxRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('postal_code', models.CharField(help_text='Zip/postal code or prefix to match', max_length=20)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
                ('tax_zone', models.ForeignKey(help_text='Tax zone this rule maps to', on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='invoicing.taxzone')),
            ],
            options={
                'verbose_name': 'Tax Rule',
                'verbose_name_plural': 'Tax Rules',
            },
        ),
        migrations.AddField(
            model_name='historicalinvoice',
            name='tax_zone',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Tax zone applied to this invoice', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='invoicing.taxzone'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='tax_zone',
            field=models.ForeignKey(blank=True, help_text='Tax zone applied to this invoice', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='invoicing.taxzone'),
        ),
        migrations.AddIndex(
            model_name='taxzone',
            index=models.Index(fields=['tenant', 'name'], name='invoicing_t_tenant__4dfb3b_idx'),
        ),
        migrations.AddIndex(
            model_name='taxzone',
            index=models.Index(fields=['tenant', 'is_active'], name='invoicing_t_tenant__b6dba4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='taxzone',
            unique_together={('tenant', 'name')},
        ),
        migrations.AddIndex(
            model_name='taxrule',
            index=models.Index(fields=['tenant', 'postal_code'], name='invoicing_t_tenant__ec875e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='taxrule',
            unique_together={('tenant', 'postal_code')},
        ),
    ]
