# Generated by Django 6.0 on 2026-05-22 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_historicalitemreceipt_itemreceipt_itemreceiptline_and_more'),
        ('invoicing', '0005_historicalinvoice_dunning_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorbillline',
            name='item_receipt_line',
            field=models.ForeignKey(blank=True, help_text="Source item-receipt line. When set, the bill clears that receipt's GR/IR accrual instead of debiting expense/asset.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bill_lines', to='inventory.itemreceiptline'),
        ),
    ]
