# Generated by Django 6.0 on 2026-06-23 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_historicalpickticket_pickticket_pickticketline_and_more'),
        ('invoicing', '0006_vendorbillline_item_receipt_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceline',
            name='pick_ticket_line',
            field=models.ForeignKey(blank=True, help_text='Source pick-ticket line (set when invoicing from a pick).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_lines', to='inventory.pickticketline'),
        ),
    ]
