# Generated by Django 6.0 on 2026-04-16 19:58

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0002_accountingsettings_default_sales_tax_account'),
        ('orders', '0011_add_fulfillment_method'),
        ('parties', '0008_update_customer_type_choices'),
        ('tenants', '0004_add_approval_settings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20)),
                ('default_useful_life_months', models.PositiveIntegerField(default=60)),
                ('default_depreciation_method', models.CharField(choices=[('straight_line', 'Straight-Line'), ('declining_balance', 'Declining Balance'), ('double_declining', 'Double Declining Balance'), ('sum_of_years', 'Sum of Years Digits'), ('units_of_production', 'Units of Production')], default='straight_line', max_length=20)),
                ('default_salvage_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Default salvage value as % of cost (e.g., 10.00 = 10%)', max_digits=5)),
                ('accumulated_depreciation_account', models.ForeignKey(help_text='Contra-asset account (e.g., 1545 Accumulated Depreciation - Vehicles)', on_delete=django.db.models.deletion.PROTECT, related_name='accum_depr_categories', to='accounting.account')),
                ('asset_account', models.ForeignKey(help_text='Balance sheet asset account (e.g., 1540 Vehicles)', on_delete=django.db.models.deletion.PROTECT, related_name='asset_categories', to='accounting.account')),
                ('depreciation_expense_account', models.ForeignKey(help_text='Income statement depreciation expense (e.g., 6830 Depreciation - Vehicles)', on_delete=django.db.models.deletion.PROTECT, related_name='depreciation_expense_categories', to='accounting.account')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name_plural': 'Asset Categories',
                'ordering': ['code'],
                'unique_together': {('tenant', 'code')},
            },
        ),
        migrations.CreateModel(
            name='FixedAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset_number', models.CharField(help_text='Unique asset tag/number', max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('fully_depreciated', 'Fully Depreciated'), ('disposed', 'Disposed'), ('written_off', 'Written Off')], default='active', max_length=20)),
                ('serial_number', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(blank=True, help_text='Physical location', max_length=200)),
                ('acquisition_date', models.DateField()),
                ('acquisition_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('invoice_reference', models.CharField(blank=True, max_length=100)),
                ('depreciation_method', models.CharField(choices=[('straight_line', 'Straight-Line'), ('declining_balance', 'Declining Balance'), ('double_declining', 'Double Declining Balance'), ('sum_of_years', 'Sum of Years Digits'), ('units_of_production', 'Units of Production')], default='straight_line', max_length=20)),
                ('useful_life_months', models.PositiveIntegerField(default=60)),
                ('salvage_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('depreciation_start_date', models.DateField(help_text='Date depreciation begins (usually same as acquisition or next month)')),
                ('accumulated_depreciation', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('disposal_date', models.DateField(blank=True, null=True)),
                ('disposal_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('disposal_method', models.CharField(blank=True, choices=[('sold', 'Sold'), ('scrapped', 'Scrapped'), ('donated', 'Donated'), ('traded_in', 'Traded In'), ('stolen', 'Stolen/Lost')], max_length=20)),
                ('disposal_notes', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('accumulated_depreciation_account', models.ForeignKey(blank=True, help_text='Override category default', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accum_depr_assets', to='accounting.account')),
                ('asset_account', models.ForeignKey(blank=True, help_text='Override category default', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fixed_assets', to='accounting.account')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='assets.assetcategory')),
                ('custodian', models.ForeignKey(blank=True, help_text='Person responsible for this asset', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_assets', to=settings.AUTH_USER_MODEL)),
                ('depreciation_expense_account', models.ForeignKey(blank=True, help_text='Override category default', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='depreciation_assets', to='accounting.account')),
                ('purchase_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acquired_assets', to='orders.purchaseorder')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sold_assets', to='parties.vendor')),
            ],
            options={
                'ordering': ['asset_number'],
                'unique_together': {('tenant', 'asset_number')},
            },
        ),
        migrations.CreateModel(
            name='AssetTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction_type', models.CharField(choices=[('acquisition', 'Acquisition'), ('improvement', 'Capital Improvement'), ('transfer', 'Location Transfer'), ('revaluation', 'Revaluation'), ('disposal', 'Disposal'), ('write_off', 'Write-Off'), ('impairment', 'Impairment')], max_length=20)),
                ('transaction_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('description', models.TextField()),
                ('from_location', models.CharField(blank=True, max_length=200)),
                ('to_location', models.CharField(blank=True, max_length=200)),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_transactions', to='accounting.journalentry')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='assets.fixedasset')),
            ],
            options={
                'ordering': ['-transaction_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DepreciationEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period_date', models.DateField(help_text='First of the month for this depreciation period')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('accumulated_after', models.DecimalField(decimal_places=2, help_text='Accumulated depreciation after this entry', max_digits=12)),
                ('net_book_value_after', models.DecimalField(decimal_places=2, help_text='Net book value after this entry', max_digits=12)),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depreciation_entries', to='accounting.journalentry')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depreciation_entries', to='assets.fixedasset')),
            ],
            options={
                'verbose_name_plural': 'Depreciation Entries',
                'ordering': ['asset', 'period_date'],
                'unique_together': {('tenant', 'asset', 'period_date')},
            },
        ),
    ]
