# Generated by Django 6.0 on 2026-01-14 22:20

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parties', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalDeliveryRun',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('name', models.CharField(help_text="Run name (e.g., 'Morning Run', 'Route A')", max_length=100)),
                ('scheduled_date', models.DateField(help_text='Date of this delivery run')),
                ('sequence', models.PositiveSmallIntegerField(default=1, help_text='Order of this run within the day (1=first run, 2=second, etc.)')),
                ('departure_time', models.TimeField(blank=True, help_text='Planned departure time', null=True)),
                ('notes', models.TextField(blank=True, help_text='Run notes/instructions')),
                ('is_complete', models.BooleanField(default=False, help_text='Whether this run has been completed')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tenants.tenant')),
                ('truck', models.ForeignKey(blank=True, db_constraint=False, help_text='Truck assigned to this run', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='parties.truck')),
            ],
            options={
                'verbose_name': 'historical delivery run',
                'verbose_name_plural': 'historical delivery runs',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='DeliveryRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text="Run name (e.g., 'Morning Run', 'Route A')", max_length=100)),
                ('scheduled_date', models.DateField(help_text='Date of this delivery run')),
                ('sequence', models.PositiveSmallIntegerField(default=1, help_text='Order of this run within the day (1=first run, 2=second, etc.)')),
                ('departure_time', models.TimeField(blank=True, help_text='Planned departure time', null=True)),
                ('notes', models.TextField(blank=True, help_text='Run notes/instructions')),
                ('is_complete', models.BooleanField(default=False, help_text='Whether this run has been completed')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
                ('truck', models.ForeignKey(help_text='Truck assigned to this run', on_delete=django.db.models.deletion.CASCADE, related_name='delivery_runs', to='parties.truck')),
            ],
            options={
                'ordering': ['scheduled_date', 'truck', 'sequence'],
                'indexes': [models.Index(fields=['tenant', 'scheduled_date'], name='new_schedul_tenant__ddde19_idx'), models.Index(fields=['tenant', 'truck', 'scheduled_date'], name='new_schedul_tenant__7391e6_idx')],
                'unique_together': {('tenant', 'truck', 'scheduled_date', 'sequence')},
            },
        ),
    ]
