# Generated by Django 6.0 on 2026-01-15 20:28

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_scheduling', '0001_initial'),
        ('orders', '0002_historicalpurchaseorder_delivery_run_and_more'),
        ('parties', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalSchedulerNote',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('content', models.TextField(help_text='Note content/text')),
                ('color', models.CharField(choices=[('yellow', 'Yellow'), ('blue', 'Blue'), ('green', 'Green'), ('red', 'Red'), ('purple', 'Purple'), ('orange', 'Orange')], default='yellow', help_text='Note color for visual distinction', max_length=20)),
                ('scheduled_date', models.DateField(blank=True, help_text='Date this note is attached to', null=True)),
                ('is_pinned', models.BooleanField(default=False, help_text='Pinned notes appear at the top')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, help_text='User who created this note', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('delivery_run', models.ForeignKey(blank=True, db_constraint=False, help_text='Delivery run this note is attached to', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='new_scheduling.deliveryrun')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('purchase_order', models.ForeignKey(blank=True, db_constraint=False, help_text='Purchase order this note is attached to', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='orders.purchaseorder')),
                ('sales_order', models.ForeignKey(blank=True, db_constraint=False, help_text='Sales order this note is attached to', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='orders.salesorder')),
                ('tenant', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tenants.tenant')),
                ('truck', models.ForeignKey(blank=True, db_constraint=False, help_text='Truck this note is attached to (combine with date for cell attachment)', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='parties.truck')),
            ],
            options={
                'verbose_name': 'historical scheduler note',
                'verbose_name_plural': 'historical scheduler notes',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='SchedulerNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField(help_text='Note content/text')),
                ('color', models.CharField(choices=[('yellow', 'Yellow'), ('blue', 'Blue'), ('green', 'Green'), ('red', 'Red'), ('purple', 'Purple'), ('orange', 'Orange')], default='yellow', help_text='Note color for visual distinction', max_length=20)),
                ('scheduled_date', models.DateField(blank=True, help_text='Date this note is attached to', null=True)),
                ('is_pinned', models.BooleanField(default=False, help_text='Pinned notes appear at the top')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this note', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduler_notes', to=settings.AUTH_USER_MODEL)),
                ('delivery_run', models.ForeignKey(blank=True, help_text='Delivery run this note is attached to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scheduler_notes', to='new_scheduling.deliveryrun')),
                ('purchase_order', models.ForeignKey(blank=True, help_text='Purchase order this note is attached to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scheduler_notes', to='orders.purchaseorder')),
                ('sales_order', models.ForeignKey(blank=True, help_text='Sales order this note is attached to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scheduler_notes', to='orders.salesorder')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
                ('truck', models.ForeignKey(blank=True, help_text='Truck this note is attached to (combine with date for cell attachment)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scheduler_notes', to='parties.truck')),
            ],
            options={
                'ordering': ['-is_pinned', '-created_at'],
                'indexes': [models.Index(fields=['tenant', 'scheduled_date'], name='new_schedul_tenant__db3f06_idx'), models.Index(fields=['tenant', 'scheduled_date', 'truck'], name='new_schedul_tenant__5ad62a_idx')],
            },
        ),
    ]
