# Generated by Django 6.0 on 2026-02-03 21:26

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_scheduling', '0002_add_scheduler_note'),
        ('orders', '0003_add_scheduler_sequence'),
        ('parties', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalDailyKickOverride',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('box_type', models.CharField(choices=[('RSC', 'RSC'), ('DC', 'D/C'), ('HSC', 'HSC'), ('FOL', 'FOL'), ('TELE', 'Tele'), ('OTHER', 'Other')], help_text='Box type this override applies to', max_length=10)),
                ('date', models.DateField(help_text='Specific date for this override')),
                ('allotment', models.PositiveIntegerField(help_text='Override allotment for this date')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tenants.tenant')),
                ('vendor', models.ForeignKey(blank=True, db_constraint=False, help_text='Vendor this override applies to', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='parties.vendor')),
            ],
            options={
                'verbose_name': 'historical daily kick override',
                'verbose_name_plural': 'historical daily kick overrides',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalPriorityLinePriority',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('scheduled_date', models.DateField(help_text='Date this line is scheduled for production')),
                ('box_type', models.CharField(choices=[('RSC', 'RSC'), ('DC', 'D/C'), ('HSC', 'HSC'), ('FOL', 'FOL'), ('TELE', 'Tele'), ('OTHER', 'Other')], help_text='Box type derived from the Item model', max_length=10)),
                ('sequence', models.PositiveIntegerField(default=0, help_text='Priority order within bin (0 = top/hottest)')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('purchase_order_line', models.ForeignKey(blank=True, db_constraint=False, help_text='The PO line being prioritized', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='orders.purchaseorderline')),
                ('tenant', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tenants.tenant')),
                ('vendor', models.ForeignKey(blank=True, db_constraint=False, help_text='Vendor for this PO line (denormalized for query efficiency)', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='parties.vendor')),
            ],
            options={
                'verbose_name': 'historical priority line priority',
                'verbose_name_plural': 'historical priority line prioritys',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalVendorKickAllotment',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('box_type', models.CharField(choices=[('RSC', 'RSC'), ('DC', 'D/C'), ('HSC', 'HSC'), ('FOL', 'FOL'), ('TELE', 'Tele'), ('OTHER', 'Other')], help_text='Box type this allotment applies to', max_length=10)),
                ('daily_allotment', models.PositiveIntegerField(default=0, help_text='Default daily kick allotment')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tenants.tenant')),
                ('vendor', models.ForeignKey(blank=True, db_constraint=False, help_text='Vendor this allotment applies to', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='parties.vendor')),
            ],
            options={
                'verbose_name': 'historical vendor kick allotment',
                'verbose_name_plural': 'historical vendor kick allotments',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='DailyKickOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('box_type', models.CharField(choices=[('RSC', 'RSC'), ('DC', 'D/C'), ('HSC', 'HSC'), ('FOL', 'FOL'), ('TELE', 'Tele'), ('OTHER', 'Other')], help_text='Box type this override applies to', max_length=10)),
                ('date', models.DateField(help_text='Specific date for this override')),
                ('allotment', models.PositiveIntegerField(help_text='Override allotment for this date')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
                ('vendor', models.ForeignKey(help_text='Vendor this override applies to', on_delete=django.db.models.deletion.CASCADE, related_name='kick_overrides', to='parties.vendor')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'vendor', 'date'], name='new_schedul_tenant__05a899_idx'), models.Index(fields=['tenant', 'date'], name='new_schedul_tenant__c2b0f2_idx')],
                'unique_together': {('tenant', 'vendor', 'box_type', 'date')},
            },
        ),
        migrations.CreateModel(
            name='PriorityLinePriority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scheduled_date', models.DateField(help_text='Date this line is scheduled for production')),
                ('box_type', models.CharField(choices=[('RSC', 'RSC'), ('DC', 'D/C'), ('HSC', 'HSC'), ('FOL', 'FOL'), ('TELE', 'Tele'), ('OTHER', 'Other')], help_text='Box type derived from the Item model', max_length=10)),
                ('sequence', models.PositiveIntegerField(default=0, help_text='Priority order within bin (0 = top/hottest)')),
                ('purchase_order_line', models.OneToOneField(help_text='The PO line being prioritized', on_delete=django.db.models.deletion.CASCADE, related_name='priority_entry', to='orders.purchaseorderline')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
                ('vendor', models.ForeignKey(help_text='Vendor for this PO line (denormalized for query efficiency)', on_delete=django.db.models.deletion.CASCADE, related_name='priority_entries', to='parties.vendor')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'vendor', 'scheduled_date', 'box_type', 'sequence'], name='new_schedul_tenant__9588e5_idx'), models.Index(fields=['tenant', 'scheduled_date'], name='new_schedul_tenant__a718a7_idx')],
                'unique_together': {('tenant', 'purchase_order_line')},
            },
        ),
        migrations.CreateModel(
            name='VendorKickAllotment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('box_type', models.CharField(choices=[('RSC', 'RSC'), ('DC', 'D/C'), ('HSC', 'HSC'), ('FOL', 'FOL'), ('TELE', 'Tele'), ('OTHER', 'Other')], help_text='Box type this allotment applies to', max_length=10)),
                ('daily_allotment', models.PositiveIntegerField(default=0, help_text='Default daily kick allotment')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
                ('vendor', models.ForeignKey(help_text='Vendor this allotment applies to', on_delete=django.db.models.deletion.CASCADE, related_name='kick_allotments', to='parties.vendor')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'vendor'], name='new_schedul_tenant__981ed8_idx')],
                'unique_together': {('tenant', 'vendor', 'box_type')},
            },
        ),
    ]
