# Generated by Django 6.0 on 2026-01-12 20:35

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0001_initial'),
        ('orders', '0001_initial'),
        ('parties', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalShipment',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('shipment_number', models.CharField(help_text='Shipment identifier (unique per tenant)', max_length=50)),
                ('ship_date', models.DateField(default=django.utils.timezone.now, help_text='Scheduled ship date')),
                ('driver_name', models.CharField(blank=True, help_text='Driver name', max_length=100)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('loading', 'Loading'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='planned', help_text='Shipment status', max_length=20)),
                ('departure_time', models.DateTimeField(blank=True, help_text='Actual departure time', null=True)),
                ('arrival_time', models.DateTimeField(blank=True, help_text='Actual arrival/delivery time', null=True)),
                ('notes', models.TextField(blank=True, help_text='Shipment notes')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tenants.tenant')),
                ('truck', models.ForeignKey(blank=True, db_constraint=False, help_text='Truck assigned for this shipment', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='parties.truck')),
            ],
            options={
                'verbose_name': 'historical Shipment',
                'verbose_name_plural': 'historical Shipments',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shipment_number', models.CharField(help_text='Shipment identifier (unique per tenant)', max_length=50)),
                ('ship_date', models.DateField(default=django.utils.timezone.now, help_text='Scheduled ship date')),
                ('driver_name', models.CharField(blank=True, help_text='Driver name', max_length=100)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('loading', 'Loading'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='planned', help_text='Shipment status', max_length=20)),
                ('departure_time', models.DateTimeField(blank=True, help_text='Actual departure time', null=True)),
                ('arrival_time', models.DateTimeField(blank=True, help_text='Actual arrival/delivery time', null=True)),
                ('notes', models.TextField(blank=True, help_text='Shipment notes')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
                ('truck', models.ForeignKey(help_text='Truck assigned for this shipment', on_delete=django.db.models.deletion.PROTECT, related_name='shipments', to='parties.truck')),
            ],
            options={
                'verbose_name': 'Shipment',
                'verbose_name_plural': 'Shipments',
            },
        ),
        migrations.CreateModel(
            name='HistoricalBillOfLading',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('bol_number', models.CharField(help_text='BOL number (unique per tenant)', max_length=50)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('signed', 'Signed'), ('void', 'Void')], default='draft', help_text='BOL status', max_length=20)),
                ('issue_date', models.DateField(default=django.utils.timezone.now, help_text='Date BOL was issued')),
                ('carrier_name', models.CharField(blank=True, help_text='Carrier/trucking company name', max_length=200)),
                ('carrier_scac', models.CharField(blank=True, help_text='Standard Carrier Alpha Code', max_length=10)),
                ('trailer_number', models.CharField(blank=True, help_text='Trailer/container number', max_length=50)),
                ('seal_number', models.CharField(blank=True, help_text='Seal number', max_length=50)),
                ('shipper_name', models.CharField(help_text='Shipper company name', max_length=200)),
                ('shipper_address', models.TextField(blank=True, help_text='Shipper address')),
                ('shipper_signature', models.CharField(blank=True, help_text='Shipper signature name', max_length=100)),
                ('shipper_signed_date', models.DateTimeField(blank=True, help_text='When shipper signed', null=True)),
                ('carrier_signature', models.CharField(blank=True, help_text='Carrier/driver signature name', max_length=100)),
                ('carrier_signed_date', models.DateTimeField(blank=True, help_text='When carrier signed', null=True)),
                ('consignee_signature', models.CharField(blank=True, help_text='Consignee signature name', max_length=100)),
                ('consignee_signed_date', models.DateTimeField(blank=True, help_text='When consignee signed', null=True)),
                ('total_pieces', models.PositiveIntegerField(default=0, help_text='Total number of pieces/packages')),
                ('total_weight', models.DecimalField(decimal_places=2, default=0, help_text='Total weight', max_digits=12)),
                ('weight_uom', models.CharField(default='LBS', help_text='Weight unit of measure', max_length=10)),
                ('notes', models.TextField(blank=True, help_text='BOL notes/special instructions')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tenants.tenant')),
                ('shipment', models.ForeignKey(blank=True, db_constraint=False, help_text='Shipment this BOL is for', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='shipping.shipment')),
            ],
            options={
                'verbose_name': 'historical Bill of Lading',
                'verbose_name_plural': 'historical Bills of Lading',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='BillOfLading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bol_number', models.CharField(help_text='BOL number (unique per tenant)', max_length=50)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('signed', 'Signed'), ('void', 'Void')], default='draft', help_text='BOL status', max_length=20)),
                ('issue_date', models.DateField(default=django.utils.timezone.now, help_text='Date BOL was issued')),
                ('carrier_name', models.CharField(blank=True, help_text='Carrier/trucking company name', max_length=200)),
                ('carrier_scac', models.CharField(blank=True, help_text='Standard Carrier Alpha Code', max_length=10)),
                ('trailer_number', models.CharField(blank=True, help_text='Trailer/container number', max_length=50)),
                ('seal_number', models.CharField(blank=True, help_text='Seal number', max_length=50)),
                ('shipper_name', models.CharField(help_text='Shipper company name', max_length=200)),
                ('shipper_address', models.TextField(blank=True, help_text='Shipper address')),
                ('shipper_signature', models.CharField(blank=True, help_text='Shipper signature name', max_length=100)),
                ('shipper_signed_date', models.DateTimeField(blank=True, help_text='When shipper signed', null=True)),
                ('carrier_signature', models.CharField(blank=True, help_text='Carrier/driver signature name', max_length=100)),
                ('carrier_signed_date', models.DateTimeField(blank=True, help_text='When carrier signed', null=True)),
                ('consignee_signature', models.CharField(blank=True, help_text='Consignee signature name', max_length=100)),
                ('consignee_signed_date', models.DateTimeField(blank=True, help_text='When consignee signed', null=True)),
                ('total_pieces', models.PositiveIntegerField(default=0, help_text='Total number of pieces/packages')),
                ('total_weight', models.DecimalField(decimal_places=2, default=0, help_text='Total weight', max_digits=12)),
                ('weight_uom', models.CharField(default='LBS', help_text='Weight unit of measure', max_length=10)),
                ('notes', models.TextField(blank=True, help_text='BOL notes/special instructions')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
                ('shipment', models.OneToOneField(help_text='Shipment this BOL is for', on_delete=django.db.models.deletion.PROTECT, related_name='bol', to='shipping.shipment')),
            ],
            options={
                'verbose_name': 'Bill of Lading',
                'verbose_name_plural': 'Bills of Lading',
            },
        ),
        migrations.CreateModel(
            name='ShipmentLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivery_sequence', models.PositiveIntegerField(default=0, help_text='Order of delivery (0=first stop)')),
                ('delivery_status', models.CharField(choices=[('pending', 'Pending'), ('loaded', 'Loaded'), ('delivered', 'Delivered'), ('refused', 'Refused'), ('partial', 'Partial Delivery')], default='pending', help_text='Delivery status for this order', max_length=20)),
                ('delivered_at', models.DateTimeField(blank=True, help_text='When this order was delivered', null=True)),
                ('signature_name', models.CharField(blank=True, help_text='Name of person who signed for delivery', max_length=100)),
                ('notes', models.TextField(blank=True, help_text='Delivery notes')),
                ('sales_order', models.ForeignKey(help_text='Sales order included in this shipment', on_delete=django.db.models.deletion.PROTECT, related_name='shipment_lines', to='orders.salesorder')),
                ('shipment', models.ForeignKey(help_text='Parent shipment', on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='shipping.shipment')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Shipment Line',
                'verbose_name_plural': 'Shipment Lines',
                'ordering': ['delivery_sequence'],
            },
        ),
        migrations.CreateModel(
            name='BOLLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_number', models.PositiveIntegerField(help_text='Line sequence')),
                ('description', models.CharField(help_text='Item description for BOL', max_length=255)),
                ('quantity', models.PositiveIntegerField(help_text='Quantity shipped')),
                ('num_packages', models.PositiveIntegerField(default=1, help_text='Number of packages/pallets')),
                ('weight', models.DecimalField(decimal_places=2, default=0, help_text='Weight of this line', max_digits=12)),
                ('freight_class', models.CharField(blank=True, help_text='Freight class (50, 55, 60, etc.)', max_length=10)),
                ('nmfc_code', models.CharField(blank=True, help_text='National Motor Freight Classification code', max_length=20)),
                ('bol', models.ForeignKey(help_text='Parent BOL', on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='shipping.billoflading')),
                ('item', models.ForeignKey(help_text='Item being shipped', on_delete=django.db.models.deletion.PROTECT, related_name='bol_lines', to='items.item')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
                ('uom', models.ForeignKey(help_text='Unit of measure', on_delete=django.db.models.deletion.PROTECT, related_name='bol_lines', to='items.unitofmeasure')),
            ],
            options={
                'verbose_name': 'BOL Line',
                'verbose_name_plural': 'BOL Lines',
                'ordering': ['line_number'],
                'indexes': [models.Index(fields=['bol', 'line_number'], name='shipping_bo_bol_id_e0c3f5_idx')],
                'unique_together': {('bol', 'line_number')},
            },
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['tenant', 'shipment_number'], name='shipping_sh_tenant__753724_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['tenant', 'ship_date'], name='shipping_sh_tenant__cb4121_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['tenant', 'truck', 'ship_date'], name='shipping_sh_tenant__2f0475_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['tenant', 'status'], name='shipping_sh_tenant__2c8bfb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='shipment',
            unique_together={('tenant', 'shipment_number')},
        ),
        migrations.AddIndex(
            model_name='billoflading',
            index=models.Index(fields=['tenant', 'bol_number'], name='shipping_bi_tenant__c335cc_idx'),
        ),
        migrations.AddIndex(
            model_name='billoflading',
            index=models.Index(fields=['tenant', 'issue_date'], name='shipping_bi_tenant__023f44_idx'),
        ),
        migrations.AddIndex(
            model_name='billoflading',
            index=models.Index(fields=['tenant', 'status'], name='shipping_bi_tenant__4a1049_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='billoflading',
            unique_together={('tenant', 'bol_number')},
        ),
        migrations.AddIndex(
            model_name='shipmentline',
            index=models.Index(fields=['shipment', 'delivery_sequence'], name='shipping_sh_shipmen_ea6cf6_idx'),
        ),
        migrations.AddIndex(
            model_name='shipmentline',
            index=models.Index(fields=['sales_order'], name='shipping_sh_sales_o_763ba8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='shipmentline',
            unique_together={('shipment', 'sales_order')},
        ),
    ]
