"""
Django settings for raven project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# In production, set DJANGO_SECRET_KEY environment variable
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-^@*l9o@fn@+^8xzbh!5e-9uf6f^r%q69zsd#m&5q1dk5sp*nk)'
)

# SECURITY WARNING: don't run with debug turned on in production!
# In production, set DJANGO_DEBUG=False
DEBUG = os.environ.get('DJANGO_DEBUG', 'True') == 'True'

# In production, set DJANGO_ALLOWED_HOSTS="yourdomain.com,*.yourdomain.com"
ALLOWED_HOSTS = os.environ.get('DJANGO_ALLOWED_HOSTS', '*').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # New SaaS apps
    'apps.tenants',
    'apps.parties',
    'apps.items',
    'apps.orders',
    'apps.scheduling',
    # Legacy apps (will be migrated)
    'core',
    'partners',
    'warehousing',
    'scheduling',
    'users',
    'simple_history',
    'tailwind',
    'theme',
    'django_browser_reload',
]

TAILWIND_APP_NAME = 'theme'

INTERNAL_IPS = [
    "127.0.0.1",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # Additional security headers (X-Content-Type-Options, Referrer-Policy, etc.)
    'shared.middleware.SecurityHeadersMiddleware',
    # CRITICAL: TenantMiddleware must come AFTER auth but BEFORE any app middleware
    'apps.tenants.middleware.TenantMiddleware',
    'django_browser_reload.middleware.BrowserReloadMiddleware',
    'simple_history.middleware.HistoryRequestMiddleware',
]

ROOT_URLCONF = 'raven.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'raven.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

AUTH_USER_MODEL = 'users.User'

# Auth Settings
LOGIN_REDIRECT_URL = 'schedulizer_dashboard'
LOGOUT_REDIRECT_URL = 'login'
LOGIN_URL = 'login'

# ==============================================================================
# SECURITY SETTINGS
# ==============================================================================
# These settings are automatically configured based on DEBUG mode.
# For production deployment, set environment variables:
#   DJANGO_DEBUG=False
#   DJANGO_SECRET_KEY=<strong-random-key>
#   DJANGO_ALLOWED_HOSTS=yourdomain.com,*.yourdomain.com

# Session Security
SESSION_COOKIE_AGE = 86400  # 24 hours
SESSION_COOKIE_HTTPONLY = True  # Prevent JavaScript access (XSS protection)
SESSION_COOKIE_SAMESITE = 'Lax'  # CSRF protection
SESSION_COOKIE_SECURE = not DEBUG  # HTTPS only in production
SESSION_COOKIE_NAME = 'raven_sessionid'  # Obscure cookie name

# CSRF Security
CSRF_COOKIE_HTTPONLY = True
CSRF_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SECURE = not DEBUG  # HTTPS only in production
CSRF_COOKIE_NAME = 'raven_csrftoken'  # Obscure cookie name

# Security Headers (production only)
if not DEBUG:
    # Redirect all HTTP to HTTPS
    SECURE_SSL_REDIRECT = True

    # HSTS (HTTP Strict Transport Security)
    # Forces browsers to use HTTPS for 1 year
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

    # Additional security headers
    SECURE_CONTENT_TYPE_NOSNIFF = True  # Prevent MIME type sniffing
    SECURE_BROWSER_XSS_FILTER = True  # Enable browser XSS protection

    # Proxy configuration (if behind reverse proxy like nginx)
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# X-Frame-Options (already set by middleware, but explicit is better)
X_FRAME_OPTIONS = 'DENY'  # Prevent clickjacking

# File Upload Security
FILE_UPLOAD_MAX_MEMORY_SIZE = 10485760  # 10MB
DATA_UPLOAD_MAX_MEMORY_SIZE = 10485760  # 10MB
FILE_UPLOAD_PERMISSIONS = 0o644

# Password Validation (strengthen minimum length)
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 12,  # Increased from default 8
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# ==============================================================================
# SECURITY NOTES FOR PRODUCTION DEPLOYMENT
# ==============================================================================
#
# REQUIRED BEFORE PRODUCTION:
# 1. Set DJANGO_DEBUG=False
# 2. Generate strong SECRET_KEY: python -c "from django.core.management.utils import get_random_secret_key; print(get_random_secret_key())"
# 3. Set DJANGO_SECRET_KEY=<generated-key>
# 4. Set DJANGO_ALLOWED_HOSTS=yourdomain.com,*.yourdomain.com
# 5. Use PostgreSQL instead of SQLite (set DATABASE_URL)
# 6. Configure static file serving (collectstatic + nginx/CDN)
# 7. Install django-axes for rate limiting: pip install django-axes
# 8. Review tenant middleware default fallback behavior
# 9. Set up SSL/TLS certificates (Let's Encrypt recommended)
# 10. Configure proper logging and monitoring
#
# RECOMMENDED:
# - Install django-csp for Content-Security-Policy headers
# - Set up Sentry or similar for error tracking
# - Configure email backend for password resets
# - Enable database connection pooling
# - Set up Redis for session storage and caching
# ==============================================================================